"""Differ for `regulate:mwc`: score the Plexus operator against the reference vector field.

Two modes, keyed off the single oracle artefact `_oracle/runs/diff_gene_network_mwc/reference.npz`
so the two runs cannot drift apart:

    python diff_gene_network_mwc.py emit-spec   # write config/atlas_jax/gene_network_mwc.yaml from the npz
    python diff_gene_network_mwc.py score       # after run_spec.py: read the engine trajectory,
                                                # compute Metric_P (trajectory) + Metric_A (adversarial
                                                # vector field), write diff.json, print PASS/FAIL

The comparison is on the vector field f (the contract's only distinguishing content), not on an
integrated trajectory: (P) uses IDENTICAL explicit-Euler integration on both sides (the engine's
own step), (A) evaluates f directly on adversarial corner cases the forward sweep cannot reach.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PLEXUS = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, os.path.join(PLEXUS, "src"))

ORACLE_RUN = os.path.join(HERE, "_oracle", "runs", "diff_gene_network_mwc")
REF_NPZ = os.path.join(ORACLE_RUN, "reference.npz")
SPEC = os.path.join(PLEXUS, "config", "atlas_jax", "gene_network_mwc.yaml")
THRESHOLD = 1.0e-4


def _load_ref():
    return dict(np.load(REF_NPZ))


def _jsonl(a):
    """A numpy array as a compact JSON literal (valid YAML flow scalar)."""
    return json.dumps(np.asarray(a).tolist())


# ------------------------------------------------------------------------------------------- #
def emit_spec():
    """Write the Plexus spec, embedding the reference's EXACT params / g0 / u0."""
    r = _load_ref()
    n_gene, n_in = int(r["n_gene"]), int(r["n_in"])
    n_cells, n_frames, dt = int(r["n_cells"]), int(r["n_frames"]), float(r["dt"])
    # positions: a small grid centred in the world; they never move (no motion operator), they
    # only keep run_spec's position-based metrics/strip from tripping on a pos-less set.
    side = int(np.ceil(np.sqrt(n_cells)))
    starts = [[20.0 + (i % side), 20.0 + (i // side)] for i in range(n_cells)]

    lines = []
    lines.append("# regulate:mwc differential -- GENERATED by diff_gene_network_mwc.py from the")
    lines.append("# oracle npz. Do not hand-edit: params/g0/u0 are the reference's own values, so")
    lines.append("# the engine (explicit-Euler) and the reference-Euler trajectory are comparable.")
    lines.append("general:")
    lines.append(f"  name: gene_network_mwc")
    lines.append(f"  seed: 0")
    lines.append(f"  n_frames: {n_frames}")
    lines.append(f"  dt: {dt}")
    lines.append(f"  boundary: free")
    lines.append(f"  dim: 2")
    lines.append(f"  world: [40.0, 40.0]")
    lines.append("sets:")
    lines.append("  cell:")
    lines.append(f"    n: {n_cells}")
    lines.append(f"    buffer: {n_cells}")
    lines.append(f"    start: {_jsonl(starts)}")
    lines.append("    state:")
    lines.append("      pos: { width: 2 }")
    lines.append(f"      gene: {{ width: {n_gene}, integration: first_order, boundary: free, record: true }}")
    lines.append(f"      sensed: {{ width: {n_in}, integration: none, boundary: free, record: false }}")
    lines.append("fields: {}")
    lines.append("operators:")
    lines.append("  # 0: initial condition -- the reference's g0 (genes) and u0 (fixed drivers).")
    lines.append(f"  - {{ op: seed_state, at: cell, before_frame: 1,")
    lines.append(f"      values: {{ gene: {_jsonl(r['g0'])}, sensed: {_jsonl(r['u0'])} }} }}")
    lines.append("  # A: the MWC gene-regulatory ODE. EMIT=velocity, INTEGRAND=gene -> the engine")
    lines.append("  #    Euler-integrates gene += dt*dg each tick (one step), matching the oracle.")
    lines.append("  - { op: regulate, implementation: mwc, at: cell, gene: gene, sensed: sensed,")
    lines.append(f"      log_rho: {_jsonl(r['P_log_rho'])},")
    lines.append(f"      log_tau: {_jsonl(r['P_log_tau'])},")
    lines.append(f"      F0: {_jsonl(r['P_F0'])},")
    lines.append(f"      H_gene: {_jsonl(r['P_H_gene'])},")
    lines.append(f"      log_K_gene: {_jsonl(r['P_log_K_gene'])},")
    lines.append(f"      H_in: {_jsonl(r['P_H_in'])},")
    lines.append(f"      log_K_in: {_jsonl(r['P_log_K_in'])} }}")
    lines.append("schedule: [seed_state, regulate]")
    lines.append("plotting:")
    lines.append("  background: black")
    lines.append("  point_size: 6.0")
    os.makedirs(os.path.dirname(SPEC), exist_ok=True)
    with open(SPEC, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {SPEC}")


# ------------------------------------------------------------------------------------------- #
def _zarr_gene():
    """The engine's recorded gene trajectory [n_rec, N, n_gene], from simulation.zarr."""
    import zarr
    from plexus.paths import graphs_data_path
    zpath = os.path.join(graphs_data_path("atlas", "gene_network_mwc"), "simulation.zarr")
    if not os.path.exists(zpath):
        raise SystemExit(f"no engine trajectory at {zpath} -- run run_spec.py gene_network_mwc first")
    root = zarr.open_group(zpath, mode="r")
    return np.asarray(root["cell"]["state"]["gene"]), zpath


_OP_MODULE = None


def _load_operator_module():
    """Import the candidate operator BY FILE PATH, bypassing plexus.operators/__init__.

    The package __init__ eagerly imports every core operator; if a concurrent operator-family
    refactor leaves one of those stale (e.g. it lists a module that is not on disk), `import
    plexus.operators.candidates.X` dies importing the parent package. This operator's own imports
    are only `plexus.models.*`, so loading its file directly sidesteps that entirely -- and it is
    the SAME bytes the engine ran (run_spec loaded it via the package, this loads it standalone).

    CACHED: `@register_operator` runs at module-exec time and raises on a second registration of
    'regulate:mwc', so the module is executed exactly ONCE per process and reused across both
    adversarial vector-field evaluations."""
    global _OP_MODULE
    if _OP_MODULE is not None:
        return _OP_MODULE
    import importlib.util
    path = os.path.join(PLEXUS, "src", "plexus", "operators", "candidates",
                        "jax_morph_gene_network_mwc.py")
    spec = importlib.util.spec_from_file_location("jm_gene_network_mwc", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    _OP_MODULE = mod
    return mod


def _torch_vf(params, Y, U):
    """The Plexus torch operator's vector field on batched state (the exact code the engine calls)."""
    import torch
    gm = _load_operator_module()
    p = {"gene": "gene", "sensed": "sensed", "_at": "cell"}
    p.update({k: np.asarray(v).tolist() for k, v in params.items()})
    op = gm.RegulateMWC(p, "cpu")
    dg = op.vector_field(torch.tensor(np.asarray(Y), dtype=torch.float32),
                         torch.tensor(np.asarray(U), dtype=torch.float32))
    return dg.detach().cpu().numpy().astype(np.float32)


def score():
    r = _load_ref()

    # --- (P) TRAJECTORY: engine (Euler) vs reference (Euler), same g0/u0/params/dt --------------
    G_eng, zpath = _zarr_gene()                      # [n_rec, N, n_gene]
    G_ref = r["G_ref"]                               # [n_frames+1, N_CELLS, n_gene]
    if G_eng.shape[0] != G_ref.shape[0]:
        raise SystemExit(f"frame-count mismatch: engine {G_eng.shape} vs ref {G_ref.shape}")
    # cells are identical replicates on both sides; broadcast-compare per (frame, cell, gene).
    traj_err = np.abs(G_eng - G_ref)
    metric_P = float(traj_err.max())

    # --- (A) VECTOR FIELD: torch vs JAX on the adversarial batches (main + extreme params) -------
    P = {k[2:]: r[k] for k in r if k.startswith("P_")}
    P2 = {k[3:]: r[k] for k in r if k.startswith("P2_")}
    dg1 = _torch_vf(P, r["Y1"], r["U1"])
    dg2 = _torch_vf(P2, r["Y2"], r["U2"])
    err1 = np.abs(dg1 - r["dg_ref1"])
    err2 = np.abs(dg2 - r["dg_ref2"])
    metric_A = float(max(err1.max(), err2.max()))
    finite = bool(np.isfinite(dg1).all() and np.isfinite(dg2).all())

    value = max(metric_P, metric_A)
    passed = bool(finite and value < THRESHOLD)
    # integration-gap diagnostic: how far the reference's OWN adaptive Dopri5 one-macro-step delta
    # sits from the explicit-Euler step -- the reason (P) compares f under matched Euler, not raw
    # trajectories. Computed from the two deltas the oracle saved.
    dopri_gap = float(np.max(np.abs(np.asarray(r["dopri_delta"]) - np.asarray(r["euler_delta"]))))

    out = {
        "threshold": THRESHOLD,
        "metric_P_trajectory_max_abs": metric_P,
        "metric_A_vectorfield_max_abs": metric_A,
        "metric_A_main_params_max_abs": float(err1.max()),
        "metric_A_extreme_params_max_abs": float(err2.max()),
        "adversarial_dg_finite": finite,
        "value": value,
        "passed": passed,
        "diagnostic_dopri_vs_euler_one_step": dopri_gap,
        "diagnostic_dopri_delta": np.asarray(r["dopri_delta"]).tolist(),
        "diagnostic_euler_delta": np.asarray(r["euler_delta"]).tolist(),
        "engine_trajectory": zpath,
        "engine_G_last_cell0": G_eng[-1, 0].tolist(),
        "ref_G_last_cell0": G_ref[-1, 0].tolist(),
        "n_frames": int(r["n_frames"]), "n_gene": int(r["n_gene"]), "n_in": int(r["n_in"]),
    }
    with open(os.path.join(ORACLE_RUN, "diff.json"), "w") as f:
        json.dump(out, f, indent=2)
    print(json.dumps(out, indent=2))
    # the Dopri gap is the whole reason we compare f under matched Euler, not raw trajectories:
    print(f"\n[diagnostic] reference Dopri5-vs-Euler ONE-step gap = "
          f"{out['diagnostic_dopri_vs_euler_one_step']:.4g}  "
          f"(>> threshold {THRESHOLD:g}: a raw engine-Euler vs reference-Dopri5 differ would "
          f"measure the integrator, not the biology)")
    print(f"[P] trajectory (matched Euler)   max|dg|-diff = {metric_P:.3e}")
    print(f"[A] vector field (adversarial)   max|dg|-diff = {metric_A:.3e}  "
          f"(main {err1.max():.3e}, extreme {err2.max():.3e})")
    print(f"\nvalue = {value:.3e}   threshold = {THRESHOLD:g}   "
          f"=> {'PASS' if passed else 'FAIL'}")
    return 0 if passed else 1


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["emit-spec", "score"])
    a = ap.parse_args()
    if a.mode == "emit-spec":
        emit_spec()
    else:
        sys.exit(score())
