"""recover.py -- TASK D: PLANTED RECOVERY.

Plant known per-cell (E, gain), run the simulation with them, INJECT the resulting particle
positions, assemble A and b, and try to get the parameters back by least squares.

WHAT "INJECT THE POSITIONS" MEANS HERE, EXACTLY
====================================================================================================
The gather advects  x_{k+1} = x_k + dt_sub * v_{k+1}  and stores  v_{k+1}.  So, with no clamp,

    v_k    = (x_k - x_{k-1}) / dt_sub
    a_k    = (v_{k+1} - v_k) / dt_sub  =  (x_{k+1} - 2 x_k + x_{k-1}) / dt_sub^2

i.e. the acceleration that the algebraic constraint  A theta = b  is written against is a SECOND
DIFFERENCE of observed positions. That is the whole point of the task: the estimator differentiates
the data twice, and dt_sub = 2e-4, so the divisor is 4e-8. Every position error is multiplied by
2.4e7 before it reaches b. This script measures that.

Three levels of honesty, all reported:

  ORACLE   b := a(theta_true) - a(0) straight out of the solver's velocities   (task C's b)
  FD       b := (x_{k+1} - 2 x_k + x_{k-1}) / dt_sub^2  - a(0), positions only (must equal ORACLE)
  N1       FD with Gaussian noise on the three position frames; A and a(0) still built from the
           CLEAN state -- the most optimistic possible noise model
  N2       the same noise ALSO written into the state that A and a(0) are built from: positions
           (p2g weights, wall masks, the activation sample) and velocity v_k = (x_k-x_{k-1})/dt_sub
           (hence drag). F and C stay at the solver's values -- they are not observable at all
           (task B blocker (a)), so N2 is still optimistic, just less so.

Only file created by this task: this one, plus recover_*.json / recover_*.png beside it.

usage:
  PYTHONPATH=/workspace/Plexus/src python recover.py --device cuda:1 --cells 100 --per-parent 100
  PYTHONPATH=/workspace/Plexus/src python recover.py --device cuda:1 --real --frame-cadence
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time

import numpy as np
import torch

sys.path.insert(0, "/workspace/Plexus/src")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from assemble import HERE, SUBSTEP_TOKENS, System, rel          # noqa: E402
from plexus.models.entities import _lame                        # noqa: E402


# --------------------------------------------------------------------------------------------- #
#  planting
# --------------------------------------------------------------------------------------------- #
def install_E(sy, E_cell):
    """Write a per-cell Young's modulus into the particles so the WARM-UP uses it too."""
    p = sy.p
    y = E_cell[sy.cid]
    p.youngs = y
    p.mu, p.la = _lame(y)


def build_planted(args, warmup, log, seed=2026):
    """A system whose trajectory was generated by a PLANTED (E, gain), with x_{k-1} recorded."""
    sy = System(device=args.device, n_cells=args.cells, per_parent=args.per_parent,
                n_grid=args.n_grid, warmup=0, dtype=args.dtype, mode=args.mode,
                real=args.real, wall_damp=args.wall_damp)
    C = sy.C
    g = torch.Generator().manual_seed(seed)
    E = (args.e_lo + (args.e_hi - args.e_lo) * torch.rand(C, generator=g)).to(sy.device, sy.dtype)
    gn = (args.g_lo + (args.g_hi - args.g_lo) * torch.rand(C, generator=g)).to(sy.device, sy.dtype)
    sy.E_planted_source = "U(%g,%g)" % (args.e_lo, args.e_hi)
    sy.E_true[1:] = E
    sy.gain_true[1:] = gn
    sy.theta_true = torch.cat([sy.E_true[1:], sy.gain_true[1:]])
    install_E(sy, sy.E_true)

    # --- warm up on the planted theta, capturing the position one substep before the snapshot ---
    x_prev = None
    for tick in range(warmup):
        sy._outer(tick, gain_cell=sy.gain_true)
        sy.H.sub_dt = sy.dt_sub
        for s in range(sy.n_sub_per_frame):
            if tick == warmup - 1 and s == sy.n_sub_per_frame - 1:
                x_prev = sy.p.get("pos").clone()
            for tok in SUBSTEP_TOKENS:
                sy._tok(tok)
        sy.H.sub_dt = None
    # also the position one FULL FRAME before the snapshot (for the frame-cadence variant)
    sy.warmup_frames = warmup
    sy._snapshot(warmup)
    sy.x_prev = x_prev
    log(f"[planted] C={sy.C} cells, Np={sy.Np}, grid {sy.g.nx}^2, dtype={sy.dtype}, "
        f"warmup={warmup} frames, dt={sy.dt} dt_sub={sy.dt_sub} ({sy.n_sub_per_frame}/frame)")
    log(f"          E planted in [{float(E.min()):.1f}, {float(E.max()):.1f}]  "
        f"gain planted in [{float(gn.min()):.3f}, {float(gn.max()):.3f}]  dx={sy.g.dx:.6g}")
    return sy


def frame_prev(args, warmup, log, seed=2026):
    """Re-run the same planted system one FRAME short, to get x at frame k-1 (frame cadence)."""
    sy = build_planted(args, warmup - 1, log=lambda *a: None, seed=seed)
    x = sy.p.get("pos").clone()
    del sy
    torch.cuda.empty_cache()
    return x


# --------------------------------------------------------------------------------------------- #
#  solving
# --------------------------------------------------------------------------------------------- #
def theta_scale(C, device, e_ref=130.0, g_ref=1.0):
    """NOMINAL column scaling (not the truth -- using theta_true here would be cheating)."""
    s = torch.ones(2 * C, device=device, dtype=torch.float64)
    s[:C] = e_ref
    s[C:] = g_ref
    return s


class Solver:
    """Normal equations for a FIXED A, at several ridge levels + a truncated pseudo-inverse.

    Column-scaled by a NOMINAL theta scale (E_ref=130, gain_ref=1) so that ridge and the rcond
    truncation mean the same thing for both blocks. Using theta_true to scale would be cheating.
    """

    LAMS = (0.0, 1e-12, 1e-10, 1e-8, 1e-6, 1e-4, 1e-2)
    RCONDS = (1e-12, 1e-10, 1e-8, 1e-6)

    def __init__(self, A, C):
        self.C = C
        self.s = theta_scale(C, A.device)
        self.Az = A.double() * self.s[None, :]
        G = self.Az.T @ self.Az
        n = G.shape[0]
        self.tr = float(torch.diagonal(G).sum() / n)
        self.I = torch.eye(n, device=G.device, dtype=torch.float64)
        self.G = G
        ev, U = torch.linalg.eigh(G)
        self.ev, self.U = ev.clamp(min=0), U
        self.cond = float(self.ev.max() / self.ev.clamp(min=1e-300).min())
        self.fac = {}
        for lam in self.LAMS:
            M = G + lam * self.tr * self.I
            try:
                L = torch.linalg.cholesky(M)
                if not torch.isfinite(L).all():
                    raise RuntimeError
                self.fac[lam] = ("chol", L)
            except Exception:                     # G is not numerically PD at lam = 0
                self.fac[lam] = ("lu", torch.linalg.lu_factor(M))

    def __call__(self, b):
        rhs = self.Az.T @ b.double()
        out = {}
        for lam in self.LAMS:
            kind, F = self.fac[lam]
            if kind == "chol":
                z = torch.cholesky_solve(rhs.unsqueeze(1), F).squeeze(1)
            else:
                z = torch.linalg.lu_solve(F[0], F[1], rhs.unsqueeze(1)).squeeze(1)
            out[f"ridge{lam:g}"] = z * self.s
        Utr = self.U.T @ rhs
        for rc in self.RCONDS:
            keep = self.ev > self.ev.max() * rc
            zi = torch.where(keep, 1.0 / self.ev.clamp(min=1e-300), torch.zeros_like(self.ev))
            out[f"pinv{rc:g}"] = (self.U @ (zi * Utr)) * self.s
        return out

    def ranks(self):
        return {f"pinv{rc:g}": int((self.ev > self.ev.max() * rc).sum()) for rc in self.RCONDS}

    def free(self):
        del self.Az
        torch.cuda.empty_cache()


def score(theta_hat, theta_true, C):
    e = ((theta_hat - theta_true) / theta_true).abs()
    eE, eg = e[:C], e[C:]
    q = lambda t, p: float(torch.quantile(t, p))
    return {"med_E": q(eE, 0.5), "p90_E": q(eE, 0.9), "max_E": float(eE.max()),
            "med_gain": q(eg, 0.5), "p90_gain": q(eg, 0.9), "max_gain": float(eg.max()),
            "rel_l2": float((theta_hat - theta_true).norm() / theta_true.norm())}


# --------------------------------------------------------------------------------------------- #
def noisy_positions(x_prev, x_k, x_next, sigma, gen):
    def n(x):
        return x + sigma * torch.randn(x.shape, generator=gen, device=x.device, dtype=x.dtype)
    return n(x_prev), n(x_k), n(x_next)


def fd_accel(x_prev, x_k, x_next, dt):
    return ((x_next - 2.0 * x_k + x_prev) / (dt * dt)).reshape(-1)


def set_state(sy, x, v, tick):
    """Write observed pos/vel into the frozen state and REFRESH the frozen body force."""
    p = sy.p
    pa, pb = p.state_schema["pos"]
    va, vb = p.state_schema["vel"]
    st = sy.state0.clone()
    st[:, pa:pb] = x
    st[:, va:vb] = v
    p.state = st
    p.F, p.C, p.Jp = sy.F0.clone(), sy.C0.clone(), sy.Jp0.clone()
    sy.state0 = p.state.clone()
    sy.x0, sy.v0 = x.clone(), v.clone()
    sy.act0, sy.pass0 = sy._outer(tick, gain_cell=None)
    sy.p.state = sy.state0.clone()          # _outer does not advect, but be explicit


# --------------------------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:1")
    ap.add_argument("--cells", type=int, default=100)
    ap.add_argument("--per-parent", type=int, default=100)
    ap.add_argument("--n-grid", type=int, default=128)
    ap.add_argument("--warmup", type=int, default=12)
    ap.add_argument("--dtype", default="float64")
    ap.add_argument("--mode", default="full", choices=["full", "inset"])
    ap.add_argument("--real", action="store_true")
    ap.add_argument("--wall-damp", type=float, default=None)
    ap.add_argument("--e-lo", type=float, default=40.0)
    ap.add_argument("--e-hi", type=float, default=220.0)
    ap.add_argument("--g-lo", type=float, default=0.5)
    ap.add_argument("--g-hi", type=float, default=1.5)
    ap.add_argument("--sigmas", default="1e-8,1e-7,1e-6,1e-5,1e-4,1e-3,1e-2",
                    help="noise std in units of ONE GRID CELL dx")
    ap.add_argument("--reps", type=int, default=3)
    ap.add_argument("--n2", action="store_true", help="also the state-noise (realistic) model")
    ap.add_argument("--n2-sigmas", default="1e-6,1e-4,1e-2")
    ap.add_argument("--frame-cadence", action="store_true",
                    help="also solve the constraint the PROPOSAL asks for: one whole frame")
    ap.add_argument("--f32-check", action="store_true")
    ap.add_argument("--interior-noise", action="store_true",
                    help="also solve the noise sweep on interior rows only")
    ap.add_argument("--px-per-cell", type=float, default=8.0,
                    help="recording pixels per grid cell (1024 px tif / 128 grid = 8)")
    ap.add_argument("--tag", default="")
    args = ap.parse_args()

    lines = []

    def log(s):
        print(s, flush=True)
        lines.append(str(s))

    R = {"argv": vars(args)}
    t_start = time.time()

    with torch.no_grad():
        sy = build_planted(args, args.warmup, log)
        C, dx = sy.C, sy.g.dx
        th = sy.theta_true.double()
        R["C"] = C
        R["Np"] = sy.Np
        R["dx"] = dx
        R["dt_sub"] = sy.dt_sub
        R["E_planted"] = [float(sy.E_true[1:].min()), float(sy.E_true[1:].max())]
        R["wall_diag"] = sy.wall_diag()

        # ---------------- the trajectory: x_{k-1}, x_k, x_{k+1} ------------------------------- #
        a_solver = sy.step(sy.E_true, sy.gain_true, n_sub=1)
        x_next = sy.p.get("pos").clone()
        x_k, x_prev = sy.x0.clone(), sy.x_prev.clone()
        a_fd = fd_accel(x_prev, x_k, x_next, sy.dt_sub)
        R["fd_vs_solver_rel"] = rel(a_fd - a_solver, a_solver)
        log(f"[injection] a from POSITIONS vs a from the solver's velocities: "
            f"rel diff {R['fd_vs_solver_rel']:.3e}   (||a||={float(a_solver.norm()):.4g})")
        if args.f32_check:
            f = lambda x: x.float().double()
            a32 = fd_accel(f(x_prev), f(x_k), f(x_next), sy.dt_sub)
            R["fd_float32_positions_rel"] = rel(a32 - a_solver, a_solver)
            log(f"            same second difference from float32 POSITIONS: "
                f"{R['fd_float32_positions_rel']:.3e}  <-- storage precision alone")

        # ---------------- assemble ------------------------------------------------------------ #
        A, a0, t_asm = sy.assemble(n_sub=1)
        b_or = a_solver - a0
        b_fd = a_fd - a0
        R["assembly_s"] = t_asm
        R["A_shape"] = list(A.shape)
        R["residual_A_theta_true_vs_b"] = rel(A @ sy.theta_true - b_or, b_or)
        R["norm_b"] = float(b_or.norm())
        R["b_rms"] = float(b_or.norm() / np.sqrt(b_or.numel()))
        log(f"[assemble]  A {tuple(A.shape)} in {t_asm:.2f}s;  ||A.theta_true - b||/||b|| = "
            f"{R['residual_A_theta_true_vs_b']:.3e};  ||b||={R['norm_b']:.5g} "
            f"(rms {R['b_rms']:.4g})")

        # ---------------- ZERO NOISE recovery -------------------------------------------------- #
        # NULLS for every recovery number below: what "knowing nothing" scores
        nom = torch.cat([torch.full((C,), 130.0, dtype=torch.float64, device=th.device),
                         torch.full((C,), 1.0, dtype=torch.float64, device=th.device)])
        perm = torch.randperm(C, device=th.device)
        shuf = torch.cat([th[:C][perm], th[C:][perm]])
        R["nulls"] = {"nominal_constant_theta": score(nom, th, C),
                      "shuffled_true_theta": score(shuf, th, C)}
        log(f"[null] nominal constant theta (E=130,g=1): med E "
            f"{R['nulls']['nominal_constant_theta']['med_E']:.3f} gain "
            f"{R['nulls']['nominal_constant_theta']['med_gain']:.3f};  shuffled truth: med E "
            f"{R['nulls']['shuffled_true_theta']['med_E']:.3f} gain "
            f"{R['nulls']['shuffled_true_theta']['med_gain']:.3f}")

        pm = sy.interior_particle_mask(4.0)
        fm = sy.flat_mask(pm)
        R["zero_noise"] = {}
        S = Solver(A, C)
        R["cond_scaled"] = S.cond
        R["pinv_ranks"] = S.ranks()
        log(f"            cond(G) in nominal-scaled coordinates: {S.cond:.4e};  "
            f"ranks {S.ranks()} of {2*C}")
        for tag, bb in (("oracle_b", b_or), ("fd_b", b_fd)):
            sols = S(bb)
            R["zero_noise"][tag] = {k: score(v, th, C) for k, v in sols.items()}
            s0 = R["zero_noise"][tag]["ridge0"]
            log(f"[zero noise/{tag:20s}] ridge0: median rel err  E {s0['med_E']:.3e}  "
                f"gain {s0['med_gain']:.3e}   p90 E {s0['p90_E']:.3e} gain {s0['p90_gain']:.3e}"
                f"   ||dtheta||/||theta|| {s0['rel_l2']:.3e}")
            if tag == "fd_b":
                for k in sorted(R["zero_noise"][tag]):
                    if k == "ridge0":
                        continue
                    s = R["zero_noise"][tag][k]
                    log(f"                       {k:12s}: med E {s['med_E']:.3e} "
                        f"gain {s['med_gain']:.3e}  p90 E {s['p90_E']:.3e}  l2 {s['rel_l2']:.3e}")
                theta0 = sols["ridge0"]
        S.free()
        Si = Solver(A[fm].contiguous(), C)
        sols = Si(b_fd[fm])
        R["zero_noise"]["fd_b_interior_rows"] = {k: score(v, th, C) for k, v in sols.items()}
        R["zero_noise"]["fd_b_interior_rows"]["_cond"] = Si.cond
        s0 = R["zero_noise"]["fd_b_interior_rows"]["ridge0"]
        log(f"[zero noise/interior rows ({100*float(pm.float().mean()):.1f}% of particles)] "
            f"ridge0: med E {s0['med_E']:.3e} gain {s0['med_gain']:.3e} l2 {s0['rel_l2']:.3e} "
            f"cond {Si.cond:.3e}")
        Si.free()
        del Si
        torch.cuda.empty_cache()
        S = Solver(A, C)

        # ---------------- N1: noise on the injected positions only ----------------------------- #
        gen = torch.Generator(device=sy.device).manual_seed(4242)
        sig_list = [float(x) for x in args.sigmas.split(",")]
        R["N1"] = {}
        R["N1_interior"] = {}
        Si = Solver(A[fm].contiguous(), C) if args.interior_noise else None
        thetas_for_plot = {}
        log("\n[N1] Gaussian noise on the three injected position frames; A, a(0) still CLEAN")
        log("      sigma/dx      sigma(world)   ||dn_b||/||b||    med|dE/E|   p90     "
            "med|dg/g|   p90      l2      | best-ridge l2")
        for sg in sig_list:
            sigma = sg * dx
            accum = []
            for r in range(args.reps):
                xp, xk, xn = noisy_positions(x_prev, x_k, x_next, sigma, gen)
                bn = fd_accel(xp, xk, xn, sy.dt_sub) - a0
                sols = S(bn)
                sc = {k: score(v, th, C) for k, v in sols.items()}
                sc["_noise_over_b"] = float((bn - b_fd).norm() / b_fd.norm())
                accum.append(sc)
                if r == 0:
                    thetas_for_plot[sg] = sols["ridge0"].clone()
                    if Si is not None:
                        si = Si(bn[fm])
                        R["N1_interior"][f"{sg:g}"] = {k: score(v, th, C) for k, v in si.items()}
            keys = [k for k in accum[0] if not k.startswith("_")]
            avg = {k: {m: float(np.mean([a[k][m] for a in accum])) for m in accum[0][k]}
                   for k in keys}
            avg["_noise_over_b"] = float(np.mean([a["_noise_over_b"] for a in accum]))
            R["N1"][f"{sg:g}"] = avg
            best = min(keys, key=lambda k: avg[k]["rel_l2"])
            s0 = avg["ridge0"]
            log(f"      {sg:<12.0e}  {sigma:<13.3e}  {avg['_noise_over_b']:<15.3e}  "
                f"{s0['med_E']:<10.3e}  {s0['p90_E']:<8.2e}  {s0['med_gain']:<10.3e}  "
                f"{s0['p90_gain']:<8.2e}  {s0['rel_l2']:<8.2e}| {best} {avg[best]['rel_l2']:.2e}"
                + (f" | interior ridge0 medE "
                   f"{R['N1_interior'][f'{sg:g}']['ridge0']['med_E']:.2e}" if Si else ""))
        if Si is not None:
            Si.free()
            del Si
            torch.cuda.empty_cache()

        # ---------------- N2: noise also inside the state A is built from ---------------------- #
        if args.n2:
            log("\n[N2] the same noise ALSO in the state A and a(0) are built from "
                "(pos -> weights/wall/activation, vel -> drag); F, C still oracle")
            S.free()
            del S
            torch.cuda.empty_cache()
            R["N2"] = {}
            F0, C0, Jp0, st0 = sy.F0.clone(), sy.C0.clone(), sy.Jp0.clone(), sy.state0.clone()
            for sg in [float(x) for x in args.n2_sigmas.split(",")]:
                sigma = sg * dx
                xp, xk, xn = noisy_positions(x_prev, x_k, x_next, sigma, gen)
                a_obs = fd_accel(xp, xk, xn, sy.dt_sub)
                v_obs = (xk - xp) / sy.dt_sub
                sy.state0 = st0.clone()
                set_state(sy, xk, v_obs, args.warmup)
                An, a0n, _ = sy.assemble(n_sub=1)
                bn = a_obs - a0n
                res = rel(An @ sy.theta_true - bn, bn)
                Sn = Solver(An, C)
                sols = Sn(bn)
                sc = {k: score(v, th, C) for k, v in sols.items()}
                sc["_model_residual"] = res
                sc["_cond"] = Sn.cond
                Sn.free()
                del Sn
                R["N2"][f"{sg:g}"] = sc
                best = min([k for k in sc if not k.startswith("_")],
                           key=lambda k: sc[k]["rel_l2"])
                log(f"      sigma={sg:.0e} dx : ||A.theta_true-b||/||b|| = {res:.3e}   "
                    f"ridge0 med E {sc['ridge0']['med_E']:.3e} gain "
                    f"{sc['ridge0']['med_gain']:.3e} l2 {sc['ridge0']['rel_l2']:.3e}  | "
                    f"best {best} l2 {sc[best]['rel_l2']:.3e}")
                del An
                torch.cuda.empty_cache()
            sy.state0 = st0.clone()
            sy.F0, sy.C0, sy.Jp0 = F0, C0, Jp0
            sy.x0 = x_k
            sy.v0 = (x_k - x_prev) / sy.dt_sub
            sy.act0, sy.pass0 = sy._outer(args.warmup, gain_cell=None)

        # ---------------- the PROPOSAL as written: one whole FRAME ----------------------------- #
        if args.frame_cadence:
            log("\n[frame cadence] the constraint the proposal actually asks for: "
                f"{sy.n_sub_per_frame} substeps = 1 frame, positions at frame cadence")
            del A
            if "S" in locals():
                S.free()
                del S
            torch.cuda.empty_cache()
            x_fprev = frame_prev(args, args.warmup, log)
            sy.restore()
            af = sy.step(sy.E_true, sy.gain_true, n_sub=sy.n_sub_per_frame)
            x_fnext = sy.p.get("pos").clone()
            a_fdf = fd_accel(x_fprev, x_k, x_fnext, sy.dt)
            Af, a0f, tf = sy.assemble(n_sub=sy.n_sub_per_frame)
            bf_or = af - a0f
            bf = a_fdf - a0f
            out = {"assembly_s": tf,
                   "fd_vs_solver_rel": rel(a_fdf - af, af),
                   "residual_A_theta_true_vs_b": rel(Af @ sy.theta_true - bf_or, bf_or)}
            log(f"      a(frame) from positions vs from the solver: {out['fd_vs_solver_rel']:.3e}"
                f"   model residual ||A.theta-b||/||b|| = "
                f"{out['residual_A_theta_true_vs_b']:.3e}")
            Sf = Solver(Af, C)
            out["cond_scaled"] = Sf.cond
            for tag, bb in (("oracle_b", bf_or), ("fd_b", bf)):
                sols = Sf(bb)
                out[tag] = {k: score(v, th, C) for k, v in sols.items()}
                if tag == "fd_b":
                    theta_frame = sols["ridge0"].clone()
                    theta_frame_ridge = sols["ridge0.01"].clone()
                s0 = out[tag]["ridge0"]
                best = min([k for k in out[tag]], key=lambda k: out[tag][k]["rel_l2"])
                log(f"      zero-noise recovery [{tag}] ridge0: med E {s0['med_E']:.3e} "
                    f"gain {s0['med_gain']:.3e} l2 {s0['rel_l2']:.3e}  | best {best} "
                    f"l2 {out[tag][best]['rel_l2']:.3e}")
            # noise at frame cadence: divisor dt^2, 100x gentler than dt_sub^2
            out["noise"] = {}
            for sg in [float(x) for x in args.sigmas.split(",")]:
                xp, xk2, xn = noisy_positions(x_fprev, x_k, x_fnext, sg * dx, gen)
                bn = fd_accel(xp, xk2, xn, sy.dt) - a0f
                sols = Sf(bn)
                sc = {k: score(v, th, C) for k, v in sols.items()}
                sc["_noise_over_b"] = float((bn - bf).norm() / bf.norm())
                out["noise"][f"{sg:g}"] = sc
                log(f"      sigma={sg:.0e} dx: noise/||b|| {sc['_noise_over_b']:.2e}  "
                    f"ridge0 med E {sc['ridge0']['med_E']:.2e} gain "
                    f"{sc['ridge0']['med_gain']:.2e} l2 {sc['ridge0']['rel_l2']:.2e}")
            R["frame_cadence"] = out
            Sf.free()
            del Af, Sf
            torch.cuda.empty_cache()
        else:
            del A
            if "S" in locals():
                S.free()
                del S
            torch.cuda.empty_cache()

        # ---------------- figure ---------------------------------------------------------------- #
        tag = args.tag or ("real" if args.real else f"C{args.cells}")
        png = os.path.join(HERE, f"recover_{tag}.png")
        make_figure(png, th, theta0, thetas_for_plot, R, C, tag, args.px_per_cell,
                    locals().get("theta_frame"), locals().get("theta_frame_ridge"))
        R["figure"] = png

    R["wall_seconds"] = time.time() - t_start
    out = os.path.join(HERE, f"recover_{args.tag or ('real' if args.real else 'C'+str(args.cells))}.json")
    json.dump(R, open(out, "w"), indent=1, default=str)
    log(f"\nwrote {out}\nwrote {R['figure']}\n[{R['wall_seconds']:.1f} s]")


def make_figure(path, th, theta0, thetas, R, C, tag, px_per_cell=8.0,
                theta_frame=None, theta_frame_ridge=None):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    thn = th.cpu().numpy()
    npan = 5 if theta_frame is not None else 4
    fig, ax = plt.subplots(1, npan, figsize=(4.75 * npan, 4.6), facecolor="black")
    for a in ax:
        a.set_facecolor("black")
        for sp in a.spines.values():
            sp.set_color("white")
        a.tick_params(colors="white", labelsize=9)
        a.xaxis.label.set_color("white")
        a.yaxis.label.set_color("white")

    def lab(a, s):
        a.text(0.02, 0.97, s, transform=a.transAxes, color="white", fontsize=11,
               va="top", ha="left", fontweight="bold")

    t0 = theta0.cpu().numpy()
    ax[0].plot(thn[:C], t0[:C], ".", color="#4da6ff", ms=5)
    lo, hi = thn[:C].min(), thn[:C].max()
    ax[0].plot([lo, hi], [lo, hi], "-", color="0.6", lw=1)
    ax[0].set_xlabel("planted E"); ax[0].set_ylabel("recovered E")
    lab(ax[0], f"a  E, zero noise  (med rel err {R['zero_noise']['fd_b']['ridge0']['med_E']:.1e})")

    ax[1].plot(thn[C:], t0[C:], ".", color="#ff6666", ms=5)
    lo, hi = thn[C:].min(), thn[C:].max()
    ax[1].plot([lo, hi], [lo, hi], "-", color="0.6", lw=1)
    ax[1].set_xlabel("planted gain"); ax[1].set_ylabel("recovered gain")
    lab(ax[1], f"b  gain, zero noise  (med {R['zero_noise']['fd_b']['ridge0']['med_gain']:.1e})")

    sgs = sorted(thetas.keys())
    if sgs:
        sg = sgs[max(0, len(sgs) // 2)]
        tn = thetas[sg].cpu().numpy()
        ax[2].plot(thn[:C], tn[:C], ".", color="#4da6ff", ms=5, label="E")
        ax[2].plot(thn[C:] * 100, tn[C:] * 100, ".", color="#ff6666", ms=5, label="gain x100")
        ax[2].plot([0, 250], [0, 250], "-", color="0.6", lw=1)
        ax[2].set_xlabel("planted (gain x100)"); ax[2].set_ylabel("recovered")
        ax[2].set_ylim(-100, 400)
        lab(ax[2], f"c  sigma = {sg:g} dx")

    S = R["N1"]
    xs = sorted(float(k) for k in S)
    ax[3].loglog(xs, [S[f"{x:g}"]["ridge0"]["med_E"] for x in xs], "o-", color="#4da6ff",
                 label="E, ridge 0")
    ax[3].loglog(xs, [S[f"{x:g}"]["ridge0"]["med_gain"] for x in xs], "s-", color="#ff6666",
                 label="gain, ridge 0")
    best = "ridge1e-06"
    if best in S[f"{xs[0]:g}"]:
        ax[3].loglog(xs, [S[f"{x:g}"][best]["med_E"] for x in xs], "o--", color="#9ecbff",
                     label="E, ridge 1e-6")
    ax[3].axhline(0.1, color="0.6", lw=1, ls=":")
    piv = 0.1 / px_per_cell
    ax[3].axvline(piv, color="orange", lw=1, ls="--")
    ax[3].text(piv * 1.15, ax[3].get_ylim()[0] * 3, "0.1 px PIV", color="orange",
               fontsize=8, rotation=90)
    ax[3].set_xlabel("position noise sigma / grid cell"); ax[3].set_ylabel("median |rel err|")
    ax[3].legend(fontsize=8, facecolor="black", edgecolor="white", labelcolor="white")
    lab(ax[3], "d  degradation with noise\n   (substep constraint)")

    if theta_frame is not None:
        tf = theta_frame.cpu().numpy()
        tr = theta_frame_ridge.cpu().numpy()
        ax[4].plot(thn[:C], tf[:C], ".", color="#4da6ff", ms=5, label="ridge 0")
        ax[4].plot(thn[:C], tr[:C], ".", color="#ffd24d", ms=4, label="ridge 1e-2")
        lo, hi = thn[:C].min(), thn[:C].max()
        ax[4].plot([lo, hi], [lo, hi], "-", color="0.6", lw=1)
        ax[4].axhline(130.0, color="0.4", lw=1, ls=":")
        ax[4].set_xlabel("planted E"); ax[4].set_ylabel("recovered E")
        ax[4].set_ylim(min(-50, float(np.percentile(tf[:C], 2))),
                       max(300, float(np.percentile(tf[:C], 98))))
        ax[4].legend(fontsize=8, facecolor="black", edgecolor="white", labelcolor="white")
        fm_ = R["frame_cadence"]["fd_b"]["ridge0"]
        lab(ax[4], f"e  ONE FRAME = the proposal, NOISE-FREE\n"
                   f"   med rel err {fm_['med_E']:.2f}  (null {R['nulls']['nominal_constant_theta']['med_E']:.2f})")
    fig.suptitle("")
    fig.tight_layout()
    fig.savefig(path, dpi=130, facecolor="black")
    plt.close(fig)


if __name__ == "__main__":
    main()
