general:
  name: material_viscoelastic_vs_elastic
  seed: 0
  n_frames: 6000
  dt: 0.0015
  boundary: wall
sets:
  cell:
    n: 2
    start:
    - - 0.3
      - 0.76
    - - 0.7
      - 0.76
    types:
      elastic:
        fraction: 0.5
        youngs: 400
      visco:
        fraction: 0.5
        youngs: 400
        layers:
        - frac: 1.0
          youngs: 400
          material: viscoelastic
          tau: 0.05
  mpm_particle:
    parent: cell
    per_parent: 7500
    radius: 0.09
    density: 1.0
fields:
  mpm_grid:
    frame: mpm_grid
    n_grid: 192
operators:
- op: gravity
  at: cell
  g: 9.0
- op: mpm_strain
  at: mpm_particle
- op: mpm_scatter
  at: mpm_particle
  to: mpm_grid
  drag: 0.0
  a_max: 200
- op: mpm_grid_update
  at: mpm_grid
  surface_tension: 0.0
  wall_damp: 1.0
  implementation: nosync
- op: mpm_gather
  at: mpm_particle
  from: mpm_grid
  wall_damp: 1.0
  wall_contact: 0.04
  vmax: 1000000000.0
schedule:
- gravity
- substep_dt: 9.375000e-05
  steps:
  - mpm_strain
  - mpm_scatter
  - mpm_grid_update
  - mpm_gather
plotting:
  renderer: mpl2d
  background: black
  colors:
    elastic:
    - 0.95
    - 0.55
    - 0.2
    visco:
    - 0.38
    - 0.1
    - 0.52
  fps: 30
  movie_max_frames: 600
  dot_size: 1.2
