"""Set ONE type size for every generated column, and check that nothing overflows a slide.

    python presentation/fit_deck.py                 # two-pass compile of plexus_oct_26.tex
    python presentation/fit_deck.py --deck other.tex --check-only

A column that is measured and shrunk slide by slide ends up at a different type size on every
slide -- large where a spec declares three operators, small where it declares fifteen -- and a
deck read as a sequence shows that as type that jumps about. So the size is set ONCE, for all
slides, at the size the densest slide needs:

    pass 1   compile; every slide reports the scale it would need as `FITSCALE=` in the log
    pass 2   write slides/fit.tex with the SMALLEST of those, and compile again with it

The same run is the check on the graphics: `Overfull \\vbox` / `\\hbox` warnings are collected
per page and reported, so "the poster is too big for the slide" is something the build says out
loud rather than something noticed later in a projector room.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
THEME = HERE                    # where beamerthemeJanelia.sty, the logo and icons/ live


def compile_once(deck: str) -> str:
    """Run pdflatex and return the log text (the run is never allowed to stop for input).

    A deck in another folder (`--dir`, e.g. an experiment's own presentation/) compiles there, with
    THIS folder on TEXINPUTS so it finds the same Janelia theme, logo and icons without a copy."""
    env = dict(os.environ, TEXINPUTS=f".:{THEME}//:" + os.environ.get("TEXINPUTS", ""))
    subprocess.run(["pdflatex", "-interaction=nonstopmode", deck],
                   cwd=HERE, capture_output=True, text=True, errors="replace", env=env)
    with open(os.path.join(HERE, os.path.splitext(deck)[0] + ".log"), errors="ignore") as f:
        return f.read()


def scales(log: str) -> list[float]:
    return [float(x) for x in re.findall(r"FITSCALE=([0-9.]+)", log)]


def overfull(log: str) -> list[tuple[int, str]]:
    """(page, message) for every box that did not fit, by counting `[n` page marks in the log."""
    out, page = [], 0
    for line in log.split("\n"):
        page += len(re.findall(r"\[\d+", line))
        if line.startswith("Overfull"):
            out.append((page + 1, line.strip()))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--deck", default="plexus_oct_26.tex")
    ap.add_argument("--dir", default=None,
                    help="the deck's folder, if not this one (it keeps its own slides/fit.tex)")
    ap.add_argument("--check-only", action="store_true", help="do not write slides/fit.tex")
    ap.add_argument("--slides-dir", default="slides",
                    help="the folder of the deck's slides and its fit.tex (two decks in one folder: exp17, 2026-10-06)")
    ap.add_argument("--floor", type=float, default=0.45,
                    help="refuse a size below this: past it the column is unreadable")
    ap.add_argument("--outlier", type=float, default=0.75,
                    help="a slide needing less than this share of the median sets its own size")
    a = ap.parse_args()
    if a.dir:
        global HERE
        HERE = os.path.abspath(a.dir)

    log = compile_once(a.deck)
    found = scales(log)
    if not found:
        print("no FITSCALE reported -- is the deck using \\fitcol?")
        return
    med = sorted(found)[len(found) // 2]
    # A SLIDE FAR DENSER THAN THE REST IS ITS OWN CASE. Taking the deck's size from it would set
    # every other slide at a size only it needs; it keeps its own smaller scale instead (\fitcol
    # takes the minimum of the two), and is named here so the choice is visible.
    ordinary = [x for x in found if x >= a.outlier * med]
    outliers = [(i + 1, x) for i, x in enumerate(found) if x < a.outlier * med]
    worst = min(ordinary) if ordinary else min(found)
    print(f"{len(found)} generated columns; scales {min(found):.3f} to {max(found):.3f}")
    for i, x in outliers:
        print(f"  slide {i} needs {x:.3f}, under {a.outlier:g} of the median {med:.3f}: "
              f"it keeps its own size")
    if not a.check_only:
        if worst < a.floor:
            print(f"  the densest ordinary slide needs {worst:.3f}, below the {a.floor} floor")
            worst = a.floor
        with open(os.path.join(HERE, a.slides_dir, "fit.tex"), "w") as f:
            f.write("% generated by presentation/fit_deck.py -- one type size for every column\n")
            f.write(f"\\renewcommand{{\\fitfixed}}{{{worst:.4f}}}\n")
        log = compile_once(a.deck)
        print(f"  every column now drawn at {worst:.4f}, the densest slide's own size")

    # LaTeX ERRORS, not only overfull boxes: the nonstop run compiles past them to a pdf, which hid a `^2` in text
    # mode that stopped Kile's pdflatex (exp17, 2026-09-30)
    errs = [l for l in log.splitlines() if l.startswith("! ")]
    print(f"  latex errors: {len(errs)}" + "".join(f"\n    {e}" for e in errs[:5]))
    bad = overfull(log)
    print(f"  overfull boxes: {len(bad)}")
    for page, msg in bad[:10]:
        print(f"    p{page}: {msg}")
    m = re.search(r"Output written on (\S+) \((\d+) pages", log)
    if m:
        print(f"  {m.group(1)}, {m.group(2)} pages")


if __name__ == "__main__":
    main()
