"""Set ONE type size for every generated column, and check that nothing overflows a slide.

    python presentation/fit_deck.py                 # two-pass compile of plexus_oct_26.tex
    python presentation/fit_deck.py --deck other.tex --check-only

A column that is measured and shrunk slide by slide ends up at a different type size on every
slide -- large where a spec declares three operators, small where it declares fifteen -- and a
deck read as a sequence shows that as type that jumps about. So the size is set ONCE, for all
slides, at the size the densest slide needs:

    pass 1   compile; every slide reports the scale it would need as `FITSCALE=` in the log
    pass 2   write slides/fit.tex with the SMALLEST of those, and compile again with it

The same run is the check on the graphics: `Overfull \\vbox` / `\\hbox` warnings are collected
per page and reported, so "the poster is too big for the slide" is something the build says out
loud rather than something noticed later in a projector room.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))


def compile_once(deck: str) -> str:
    """Run pdflatex and return the log text (the run is never allowed to stop for input)."""
    subprocess.run(["pdflatex", "-interaction=nonstopmode", deck],
                   cwd=HERE, capture_output=True, text=True)
    with open(os.path.join(HERE, os.path.splitext(deck)[0] + ".log"), errors="ignore") as f:
        return f.read()


def scales(log: str) -> list[float]:
    return [float(x) for x in re.findall(r"FITSCALE=([0-9.]+)", log)]


def overfull(log: str) -> list[tuple[int, str]]:
    """(page, message) for every box that did not fit, by counting `[n` page marks in the log."""
    out, page = [], 0
    for line in log.split("\n"):
        page += len(re.findall(r"\[\d+", line))
        if line.startswith("Overfull"):
            out.append((page + 1, line.strip()))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--deck", default="plexus_oct_26.tex")
    ap.add_argument("--check-only", action="store_true", help="do not write slides/fit.tex")
    ap.add_argument("--floor", type=float, default=0.45,
                    help="refuse a size below this: past it the column is unreadable")
    a = ap.parse_args()

    log = compile_once(a.deck)
    found = scales(log)
    if not found:
        print("no FITSCALE reported -- is the deck using \\fitcol?")
        return
    worst = min(found)
    print(f"{len(found)} generated columns; scales {min(found):.3f} to {max(found):.3f}")
    if not a.check_only:
        if worst < a.floor:
            print(f"  the densest slide needs {worst:.3f}, below the {a.floor} floor: "
                  f"it is set at the floor and that slide will still overflow")
            worst = a.floor
        with open(os.path.join(HERE, "slides", "fit.tex"), "w") as f:
            f.write("% generated by presentation/fit_deck.py -- one type size for every column\n")
            f.write(f"\\renewcommand{{\\fitfixed}}{{{worst:.4f}}}\n")
        log = compile_once(a.deck)
        print(f"  every column now drawn at {worst:.4f}, the densest slide's own size")

    bad = overfull(log)
    print(f"  overfull boxes: {len(bad)}")
    for page, msg in bad[:10]:
        print(f"    p{page}: {msg}")
    m = re.search(r"Output written on (\S+) \((\d+) pages", log)
    if m:
        print(f"  {m.group(1)}, {m.group(2)} pages")


if __name__ == "__main__":
    main()
