"""The toy: a Plexus forward run that knows its own ground truth.

WHY A TOY AT ALL. ZAPBench has no connectome and no cell-type labels; redox has no segmentation.
Neither can tell us whether the model works, only whether it fits. The toy exists to falsify
cheaply: it is generated by the SAME registered operators the fit will try to recover, so every
learnable object has a known answer --

    W_e         the edge weight            -> G9   (the spatial interaction kernel)
    tau_t       per-type time constant     -> G10
    node_type   the 8 (or 65) type labels  -> G11/G12
    b_i         per-neuron stimulus gain   -> G13

NOTHING IS REIMPLEMENTED. The dynamics are `neuron_update` (leaky_tanh) + `neuron_signal` +
`neuron_field_input` + `activation_pulse`, all already registered in `plexus.operators.neural`,
run by `plexus.engine.run`. This module only builds the spatial graph they need and records the
ground truth alongside the trajectory.

THE GENERATION IS TWO-PASS, and the reason is worth stating because it looks like a detour. The
interaction graph is spatial -- k nearest neighbours on the neuron positions -- but positions are
assigned by the engine when it builds the hierarchy, so the graph cannot be written before the
build. Pass 1 builds and seeds a hierarchy with the synapse set removed, which needs no graph, and
reads the positions off it. Pass 2 writes those positions' kNN graph to an `edges_file:` -- a key
`plexus.engine` already resolves (engine.py:441) -- and runs the real spec. The alternative,
generating positions here and hoping they match the engine's, is the kind of second source of
truth this prototype exists to avoid.

DIM 2, DELIBERATELY. The external drive is a grid field sampled at each neuron's position, and the
field operators the toy reuses (`activation_pulse`) are two-dimensional. Nothing in the model under
test is 2D -- ZAPBench is a 3-D point cloud and the option that cares, the encoder/decoder, is
tested there. Paying for a 3-D field here would buy a harder toy, not a better one.
"""

from __future__ import annotations

import copy
import os

import numpy as np
import torch
import yaml

import ops_toy  # noqa: F401  registers the toy generator's rules
from plexus import engine as plexus_engine
from plexus import schema as plexus_schema


def _spec_without(raw: dict, set_name: str) -> dict:
    r = copy.deepcopy(raw)
    r["sets"].pop(set_name, None)
    r["operators"] = [o for o in r["operators"]
                      if o.get("edge_set") != set_name and o.get("at") != set_name]
    keep = {o["op"] for o in r["operators"]}
    r["schedule"] = [s for s in r["schedule"] if s in keep]
    return r


def _write_tmp_spec(raw: dict, path: str) -> str:
    with open(path, "w") as f:
        yaml.safe_dump(raw, f, sort_keys=False)
    return path


def knn_edges(pos: np.ndarray, k: int) -> tuple[np.ndarray, np.ndarray]:
    """Directed edges j -> i for the k nearest neighbours of each i, excluding self.

    Returns (edge_index [2, E] as (pre, post), distance [E]). `pre` is the sender, matching the
    `pre`/`post` incidence roles the neural operators traverse.
    """
    d = np.linalg.norm(pos[:, None, :] - pos[None, :, :], axis=-1)
    np.fill_diagonal(d, np.inf)
    nn = np.argsort(d, axis=1)[:, :k]                       # [N, k] senders for each receiver
    post = np.repeat(np.arange(pos.shape[0]), k)
    pre = nn.reshape(-1)
    return np.stack([pre, post]).astype(np.int64), d[post, pre].astype(np.float32)


def kernel_weights(dist: np.ndarray, pre_type: np.ndarray, n_types: int,
                   amplitude: float, length_scale: float,
                   inhibitory_fraction: float, rng) -> np.ndarray:
    """W_e = sign(type of the sender) * A * exp(-d_e / lambda).

    A DETERMINISTIC function of distance and presynaptic type, which is what makes G9 a gate on a
    kernel rather than on a memorised list: the model has to recover a rule, not E numbers. The
    sign is Dale-like -- a neuron is excitatory or inhibitory as a whole -- so the sign structure
    is a property of the type, not of the edge.
    """
    n_inh = int(round(inhibitory_fraction * n_types))
    inhibitory = set(rng.permutation(n_types)[:n_inh].tolist())
    sign = np.where(np.isin(pre_type, list(inhibitory)), -1.0, 1.0).astype(np.float32)
    return (sign * amplitude * np.exp(-dist / length_scale)).astype(np.float32)


def generate(fit, out_dir: str, device: str = "cpu") -> dict:
    """Run the toy forward and write trajectory + ground truth. Returns a summary dict."""
    if (fit.data.toy or {}).get("kind") == "wave_gradient":
        return generate_wave(fit, out_dir, device)
    if (fit.data.toy or {}).get("kind") == "two_scale_field":
        return generate_field(fit, out_dir, device)
    with open(fit.path) as f:
        raw = yaml.safe_load(f)
    toy = fit.data.toy
    rng = np.random.default_rng(fit.plexus.seed)
    os.makedirs(out_dir, exist_ok=True)

    # --- pass 1: positions and types, with no graph to build ------------------------------- #
    p1 = _write_tmp_spec(_spec_without(raw, toy["edge_set"]), os.path.join(out_dir, "_pass1.yaml"))
    spec1 = plexus_schema.load(p1)
    H1 = plexus_engine.build(spec1, device)
    plexus_engine.seed(H1, spec1, device)
    lvl = H1.level(toy["set"])
    pos = lvl.get("pos").detach().cpu().numpy().astype(np.float32)
    node_type = lvl.node_type.detach().cpu().numpy().astype(np.int64)
    n_types = int(node_type.max()) + 1

    # --- the spatial graph, and the kernel that will have to be recovered ------------------ #
    edge_index, dist = knn_edges(pos, fit.data.graph.k)
    weights = kernel_weights(dist, node_type[edge_index[0]], n_types,
                             float(toy["amplitude"]), float(toy["length_scale"]),
                             float(toy["inhibitory_fraction"]), rng)
    # ABSOLUTE, because `edges_file:` is resolved through `graphs_data_path` unless the path is
    # absolute (engine.py:444). A relative path here would be silently looked for under the data
    # root, which is not where the prototype writes.
    edges_path = os.path.abspath(os.path.join(out_dir, "edges.npz"))
    np.savez(edges_path, edge_index=edge_index, weights=weights)

    # --- pass 2: the real run ------------------------------------------------------------- #
    # The base spec carries a one-edge placeholder so it loads for `-o gates` before any graph
    # exists. It must be REMOVED here, not left beside the file: the schema refuses an edge-set
    # that names both, on the grounds that an inline list beside a connectome file is a second
    # answer to the same question. It is right to refuse.
    r2 = copy.deepcopy(raw)
    es = r2["sets"][toy["edge_set"]]
    es.pop("edges", None)
    es.pop("weights", None)
    es["edges_file"] = edges_path
    p2 = _write_tmp_spec(r2, os.path.join(out_dir, "_pass2.yaml"))
    spec2 = plexus_schema.load(p2)
    traj_path = os.path.join(out_dir, "toy.zarr")
    H2, rec = plexus_engine.run(spec2, traj_path, device=device, progress=False)

    # --- ground truth, next to the trajectory --------------------------------------------- #
    # Read the trajectory back out of the zarr the engine wrote rather than off `rec`: the zarr is
    # the artifact a consumer sees, so reading it here is also a check that it contains what the
    # fit will later need. Layout is <set>/state/<block>, per plexus.engine's writer.
    import zarr
    z = zarr.open(traj_path, "r")
    lvl2 = H2.level(toy["set"])
    voltage = np.asarray(z[toy["set"]]["state"][fit.data.state][:, :, 0], dtype=np.float32)
    type_p = np.array([t["p"] for t in raw["sets"][toy["set"]]["types"].values()], dtype=np.float32)
    tau_per_type = 1.0 / type_p[:, 0]
    # THE STIMULUS, FACTORISED the way the model represents it: a global clock s(t) times a
    # per-neuron gain b_i. Saving only the final omega would make b_i a constant bias rather than
    # a gain, and G13 would then be scoring the wrong object.
    pulse = next(o for o in raw["operators"] if o["op"] == "activation_pulse")
    pace = next(o for o in raw["operators"] if o["op"] == "pacemaker")
    period, duration = float(pace["period"]), float(pace["duration"])
    frames = np.arange(voltage.shape[0], dtype=np.float32)
    ph = np.mod(frames, period)
    stim_t = np.where(ph < duration, np.sin(np.pi * ph / max(duration, 1e-9)), 0.0).astype(np.float32)
    ctr = np.array(pulse.get("center", [0.5, 0.5]), dtype=np.float32)[: pos.shape[1]]
    sigma = float(pulse.get("radius", 0.12))
    bump = np.exp(-((pos - ctr) ** 2).sum(1) / (2 * sigma * sigma)).astype(np.float32)
    gain_per_type = type_p[:, 2]
    b_i = (gain_per_type[node_type] * bump).astype(np.float32)

    gt_path = os.path.join(out_dir, "ground_truth.npz")
    np.savez(gt_path,
             positions=pos, node_type=node_type, edge_index=edge_index, weights=weights,
             distance=dist, tau_per_type=tau_per_type, tau=tau_per_type[node_type],
             gain_per_type=gain_per_type, b_i=b_i, type_p=type_p, voltage=voltage,
             stim_t=stim_t, bump=bump)

    return {"n_neurons": int(pos.shape[0]), "n_types": n_types,
            "n_edges": int(edge_index.shape[1]), "n_frames": int(voltage.shape[0]),
            "trajectory": traj_path, "ground_truth": gt_path, "edges": edges_path}


def _mean_cell_purity(key: np.ndarray, node_type: np.ndarray, n_types: int) -> float:
    purities = []
    for cell in np.unique(key):
        t = node_type[key == cell]
        purities.append(np.bincount(t, minlength=n_types).max() / t.size)
    return float(np.mean(purities))


def spatial_type_purity(pos: np.ndarray, node_type: np.ndarray, cells_per_axis: int,
                        n_permutations: int = 32, seed: int = 0) -> float:
    """G16: spatial-cell type purity, as a multiple of a LABEL-PERMUTATION null. 1.0 == chance.

    The gate exists because G11/G12 must not be passable by position alone. On flyvis that holds by
    anatomy -- retinotopy is the axis along which neurons are equivalent, and spatial-cell type
    purity is 0.016 = 1/65 = chance at every resolution from 2 to 128 cells per axis. The toy has to
    reproduce that property deliberately rather than inherit it, so types are assigned by a
    permutation independent of position and this measures that they were.

    THE NULL IS EMPIRICAL, NOT 1/n_types, and the first version of this gate failed because of it.
    An analytic chance level of 1/n_types is only right when a cell holds many neurons. At 32 cells
    per axis there are 1024 cells for 1024 neurons, so almost every occupied cell holds ONE neuron
    and its purity is 1.0 by construction -- the measurement read 6.1x chance and meant nothing but
    "the grid is finer than the sampling". Permuting the labels over the same cells reproduces that
    finite-sampling effect exactly, so the ratio is 1.0 when there is no spatial structure at ANY
    resolution. The threshold did not move; the estimator of chance did.
    """
    n_types = int(node_type.max()) + 1
    lo, hi = pos.min(0), pos.max(0)
    idx = np.clip(((pos - lo) / np.maximum(hi - lo, 1e-12) * cells_per_axis).astype(int),
                  0, cells_per_axis - 1)
    key = idx[:, 0] * cells_per_axis + idx[:, 1] if pos.shape[1] > 1 else idx[:, 0]
    observed = _mean_cell_purity(key, node_type, n_types)
    rng = np.random.default_rng(seed)
    null = np.mean([_mean_cell_purity(key, rng.permutation(node_type), n_types)
                    for _ in range(n_permutations)])
    return float(observed / max(null, 1e-12))


def generate_wave(fit, out_dir: str, device: str = "cpu") -> dict:
    """The two-scale toy: a coarse field rule read by per-node signed gains.

    There is NO edge set in the spec, because the generator's fine rule reads the field directly.
    The graph is the MODEL's problem: it sees only the drive sampled at each node and has to
    reconstruct a spatial derivative from its neighbours. Building the generator on the same graph
    the model is given would hand it the answer.

    GROUND TRUTH IS EVALUATED THROUGH THE OPERATOR, not from a formula written again here. An
    earlier version re-derived du/dx analytically while the operator computed it by a finite
    difference on a sampled grid; the two disagreed enough to drop the per-node recovery R^2 from
    ~1.0 to 0.645, which read as a defect in the toy and was a defect in the bookkeeping. The
    operator instance is the single source of truth for what the coarse rule IS.
    """
    import zarr
    from plexus.models.registry import get_operator

    with open(fit.path) as f:
        raw = yaml.safe_load(f)
    toy = fit.data.toy
    os.makedirs(out_dir, exist_ok=True)

    spec = plexus_schema.load(fit.path)
    traj = os.path.join(out_dir, "toy.zarr")
    H, _ = plexus_engine.run(spec, traj, device=device, progress=False)

    z = zarr.open(traj, "r")
    voltage = np.asarray(z[toy["set"]]["state"][fit.data.state][:, :, 0], dtype=np.float32)
    pos = np.asarray(z[toy["set"]]["pos"][0], dtype=np.float32)
    lvl = H.level(toy["set"])
    node_type = lvl.node_type.detach().cpu().numpy().astype(np.int64)
    type_p = np.array([t["p"] for t in raw["sets"][toy["set"]]["types"].values()], dtype=np.float32)
    tau = (1.0 / type_p[:, 0])[node_type].astype(np.float32)
    gain = type_p[:, 2][node_type].astype(np.float32)

    # --- the coarse rule, evaluated through the operator the run actually used -------------- #
    wf_line = next(o for o in raw["operators"] if o["op"] == "wave_field")
    gg_line = next(o for o in raw["operators"] if o["op"] == "gradient_gain")
    model_name = wf_line.get("model", "travelling")
    cls = get_operator("wave_field", variant=model_name)
    op = cls({**wf_line, "_at": wf_line.get("at")}, device="cpu")
    ax, delta = int(wf_line.get("axis", 0)), float(gg_line.get("delta", 0.005))

    T = voltage.shape[0]
    P = torch.tensor(pos, dtype=torch.float32)
    off = torch.zeros_like(P)
    off[:, ax] = delta
    stim = np.zeros((T, pos.shape[0]), dtype=np.float32)
    grad = np.zeros((T, pos.shape[0]), dtype=np.float32)
    for t in range(T):
        cols = [P[:, d] for d in range(P.shape[1])]
        up = op._u([c + (delta if d == ax else 0.0) for d, c in enumerate(cols)], float(t))
        um = op._u([c - (delta if d == ax else 0.0) for d, c in enumerate(cols)], float(t))
        stim[t] = op._u(cols, float(t)).numpy()
        grad[t] = ((up - um) / (2.0 * delta)).numpy()

    edge_index, dist = knn_edges(pos, fit.data.graph.k)
    gt_path = os.path.join(out_dir, "ground_truth.npz")
    np.savez(gt_path, positions=pos, node_type=node_type, tau=tau, gain=gain,
             edge_index=edge_index, distance=dist, voltage=voltage,
             stim=stim, grad=grad, type_p=type_p,
             tau_per_type=1.0 / type_p[:, 0], gain_per_type=type_p[:, 2],
             coarse_model=np.array(model_name))
    return {"n_nodes": int(pos.shape[0]), "n_types": int(node_type.max()) + 1,
            "coarse_rule": model_name, "n_edges": int(edge_index.shape[1]),
            "n_frames": int(T), "trajectory": traj, "ground_truth": gt_path}


def generate_field(fit, out_dir: str, device: str = "cpu") -> dict:
    """The two-scale FIELD toy: a coarse rule and a fine rule that do not couple.

    THREE SPECS, NOT ONE SPEC WITH A SWITCH. `<toy>_coarse.yaml` holds only the coarse field and
    the coarse operator, `<toy>_fine.yaml` only the fine pair, `<toy>.yaml` both. Each is a
    complete, runnable Plexus spec that stands on its own, and each writes its own zarr into its
    own run directory. The alternative -- one spec and a `--only coarse` flag -- would put the
    composition in the command line instead of in the file, and then the archived zarr would not
    say what produced it.

    THAT THE TWO PARTS ARE UNCOUPLED IS WHAT MAKES THIS LEGAL. `u` never reads `v` and `v` never
    reads `u`, so running either alone gives bit-identical trajectories to running both and looking
    at one channel. If they were coupled, the split runs would be different physics wearing the
    same name, and the separate zarrs would be a lie about what the sum decomposes into.

    Measurements written to `summary.json` are the two that decide whether the toy poses the
    intended problem, and both are reported in the unit of the phenomenon rather than of the mesh:

        rate separation   coarse period / fine period, in FRAMES
        sampling          recorded samples per fine period -- below ~4 the fine rule is aliased and
                          any 'it changes fast' measurement is measuring the sampling instead
    """
    import json

    import zarr

    import vtk_toy

    spec = plexus_schema.load(fit.path)
    traj = os.path.join(out_dir, "field.zarr")
    plexus_engine.run(spec, traj, device=device, progress=False)
    z = zarr.open(traj, "r")

    part = (fit.data.toy or {}).get("part", "both")
    names = {"u": "coarse transport", "v": "fine Kuramoto"}
    grids, summary = {}, {"part": part, "fields": {}}
    for key in z.array_keys() if hasattr(z, "array_keys") else []:
        pass
    for key in ("u", "v"):
        if key in z:
            grids[key] = np.asarray(z[key]["grid"])[:, 0]

    for key, g in grids.items():
        res = "x".join(str(s) for s in g.shape[1:])
        summary["fields"][key] = {"res": res, "frames": int(g.shape[0]),
                                  "std": float(g.std()), "lag1_autocorr": _lag1(g),
                                  "still_pair_fraction": _still_pairs(g)}
        vtk_toy.movie(g, os.path.join(out_dir, f"{key}.mp4"), f"{names[key]}  {res}")

    if len(grids) == 2:
        # THE SUM IS THE OBSERVATION. It is formed at the FINE resolution, because that is the one
        # that can hold both: putting the fine field on the coarse grid would decimate exactly the
        # structure the model has to find.
        #
        # NOT WRITTEN TO DISK, and that is deliberate. The sum is u-interpolated plus v exactly, and
        # both terms are already archived as their own zarrs, so a `sum.zarr` would be a third copy
        # of the same numbers -- 4.3 GB of them at 256^3 x 64 -- that could drift out of step with
        # the two it is derived from. The movie is the artifact; these three lines are the recipe.
        # Accumulated IN PLACE for the same reason: at 3-D sizes a spare temporary is gigabytes.
        # NEAREST, NOT LINEAR. The coarse field is discrete at its own resolution -- 256^2 in 2-D,
        # 64^3 in 3-D -- and smoothing it on the way up invents structure the PDE never produced,
        # so the observation would carry gradients that belong to the interpolant rather than to
        # the physics. Held at nearest, one coarse cell is one block of 4x4 (or 4^3) fine cells and
        # the sum contains exactly the two fields that were solved for.
        u, v = grids["u"], grids["v"]
        s = torch.nn.functional.interpolate(torch.as_tensor(u)[:, None], size=v.shape[1:],
                                            mode="nearest")[:, 0].numpy()
        s += v
        summary["fields"]["sum"] = {"res": "x".join(str(x) for x in v.shape[1:]),
                                    "frames": int(s.shape[0]), "std": float(s.std()),
                                    "lag1_autocorr": _lag1(s)}
        vtk_toy.movie(s, os.path.join(out_dir, "sum.mp4"), "sum, the observation")

    with open(os.path.join(out_dir, "summary.json"), "w") as f:
        json.dump(summary, f, indent=2)
    return summary


def _lag1(g):
    """Lag-1 autocorrelation of the recorded series, averaged over a sample of cells.

    NEAR 1 MEANS RESOLVED IN TIME; NEAR 0 MEANS ALIASED, and the two are not distinguishable by
    looking at a movie -- an aliased oscillation looks like fast noise, which is exactly how it was
    misread once here. This number is the check, and it belongs in the generator's summary rather
    than in a gate, because a badly sampled toy should be caught before anything is measured on it.
    """
    x = np.asarray(g, np.float64).reshape(g.shape[0], -1)
    live = np.abs(x).max(0) > 1e-6
    x = x[:, live] if live.any() else x
    idx = np.arange(0, x.shape[1], max(1, x.shape[1] // 300))
    c = [np.corrcoef(x[:-1, j], x[1:, j])[0, 1] for j in idx]
    c = [w for w in c if np.isfinite(w)]
    return float(np.mean(c)) if c else float("nan")


def _still_pairs(g, tol=1e-12):
    """Fraction of CONSECUTIVE RECORDED PAIRS between which the field does not change at all.

    THE STATISTIC THAT DEFINES THE TWO-RESOLUTION PARTITION, and it is the prototype's target
    phenomenon rather than a defect to be tuned away.

    The coarse rule advances by whole cells (see `AdvectField`), so its motion per recorded frame
    is the velocity times the resolution times the stride. Coarsen the mesh and that number falls;
    below one cell per recorded frame, MOST CONSECUTIVE RECORDS ARE BIT-IDENTICAL and du/dt is
    exactly zero on them. Measured at the same velocity and stride: 256^2 moves 1.28 cells per
    record and this reads ~0; 64^2 moves 0.29 and it reads ~0.7.

    A single-resolution fit sees the 64^2 case as a field that is mostly static and occasionally
    jumps, and there is no timestep at which that is a smooth transport -- which is exactly the
    situation a multi-resolution model exists for: the coarse level must be integrated on its OWN
    clock, not on the observation's. So this number is reported next to the data, and the two
    coarse specs per dimension exist to put a fit on both sides of it.
    """
    x = np.asarray(g, np.float64).reshape(g.shape[0], -1)
    d = np.abs(x[1:] - x[:-1]).max(axis=1)
    return float((d <= tol).mean())
