"""Generate the paired differential-test artefacts for `regulate:connectionist`.

ONE source of the numbers, written into BOTH sides, so the oracle and the Plexus spec integrate
the *identical* ODE from the *identical* initial condition with the *identical* parameters. Run
this once (any interpreter with numpy + yaml); it writes:

    _oracle/scripts/gene_network_connectionist.py     the oracle (reference GeneNetworkConnectionist)
    config/atlas/gene_network_connectionist.yaml       the matched Plexus spec (regulate:connectionist)

Arrays are embedded as full-precision literals in both files (json/yaml both serialize floats via
repr, so float64 round-trips exactly and casts to the same float32 on each side). The scenario is a
homogeneous batch of N identical cells: this still exercises the recurrent gene->gene coupling, the
input coupling inside the sigmoid, the algebraic sigmoid, per-gene decay and the multi-step
accumulation, and it catches the realistic bug classes (a spurious cross-cell coupling would scale
the drive by N and blow the threshold by orders of magnitude).
"""
from __future__ import annotations

import json
import os

import numpy as np
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
PLEXUS = os.path.abspath(os.path.join(HERE, "..", "..", ".."))

# ---- the one place the scenario is defined ------------------------------------------------- #
SEED = 20250731
N = 6                 # cells (homogeneous batch)
HIDDEN = 2            # latent genes
OUT = 3               # observed output genes
IN = 2               # sensed driver width
NG = HIDDEN + OUT     # = 5, the full gene vector width
N_STEPS = 20          # macro-steps -> 21 recorded frames g(0), g(dt), ..., g(20 dt)
DT = 1.0
SUBSTEPS = 64         # Plexus fixed-step RK4 substeps (>> enough that RK4 error << reference rtol)

rng = np.random.default_rng(SEED)
gene0 = rng.uniform(0.2, 2.0, NG)         # initial gene vector [hidden(2), outputs(3)]
u = rng.uniform(-1.0, 2.0, IN)            # frozen sensed drive
W_gene = rng.normal(0.0, 0.4, (NG, NG))   # dense within-cell gene->gene coupling
W_in = rng.normal(0.0, 0.6, (NG, IN))     # input coupling (INSIDE the sigmoid; code, not paper)
b = rng.normal(0.0, 0.5, NG)              # basal bias
gamma = rng.uniform(0.08, 0.15, NG)       # per-gene decay (non-default; exercises the broadcast path)


def jlist(a):
    return json.dumps(np.asarray(a).tolist())


# =========================================================================================== #
#  the oracle script  (reference GeneNetworkConnectionist, run in _oracle/venv)
# =========================================================================================== #
ORACLE = f'''"""diff oracle for regulate:connectionist -- the reference GeneNetworkConnectionist ODE.

GENERATED by _gen_gene_network_connectionist.py; do not hand-edit. Runs the shipped
jax_morph.control.GeneNetworkConnectionist (diffrax Dopri5, PIDController rtol=1e-4 atol=1e-6)
for {N_STEPS} macro-steps of dt={DT} on a homogeneous batch of {N} cells and writes the gene
trajectory g(0), g(dt), ..., g({N_STEPS}*dt). The Plexus spec config/atlas/gene_network_connectionist.yaml
integrates the IDENTICAL ODE from the IDENTICAL initial condition with regulate:connectionist.
"""
import json, os
import numpy as np
import jax, jax.numpy as jnp
import jax_morph as jxm
from jax_morph.control import GeneNetworkConnectionist
from jax_morph.core.state import StateFieldSpec, build_state_from_model

OUT_DIR = os.environ["OUT"]
SEED, N, HIDDEN, OUT, IN, NG = {SEED}, {N}, {HIDDEN}, {OUT}, {IN}, {NG}
N_STEPS, DT = {N_STEPS}, {DT}

gene0  = np.array(json.loads(r\'\'\'{jlist(gene0)}\'\'\'), dtype=np.float64)
u_vec  = np.array(json.loads(r\'\'\'{jlist(u)}\'\'\'), dtype=np.float64)
W_gene = np.array(json.loads(r\'\'\'{jlist(W_gene)}\'\'\'), dtype=np.float64)
W_in   = np.array(json.loads(r\'\'\'{jlist(W_in)}\'\'\'), dtype=np.float64)
b      = np.array(json.loads(r\'\'\'{jlist(b)}\'\'\'), dtype=np.float64)
gamma  = np.array(json.loads(r\'\'\'{jlist(gamma)}\'\'\'), dtype=np.float64)

u_spec = StateFieldSpec("u_drive", shape=(IN,))
o_spec = StateFieldSpec("gout", shape=(OUT,))
ctrl = GeneNetworkConnectionist(
    (u_spec,), (o_spec,), hidden_size=HIDDEN,
    W_gene=jnp.asarray(W_gene), W_in=jnp.asarray(W_in), b=jnp.asarray(b), gamma=jnp.asarray(gamma),
)
model = jxm.Model([ctrl])
State = build_state_from_model(model)


def seed_state():
    s = State.init_empty(capacity=N, n_space_dim=2, n_types=1)
    return s.update(
        alive=s.alive.at[:N].set(True),
        celltype=s.celltype.at[:N, 0].set(1.0),
        gene_hidden=s.gene_hidden.at[:N].set(jnp.asarray(gene0[:HIDDEN])),
        gout=s.gout.at[:N].set(jnp.asarray(gene0[HIDDEN:])),
        u_drive=s.u_drive.at[:N].set(jnp.asarray(u_vec)),
    )


def rollout():
    return jxm.simulate(model, seed_state(), n_steps=N_STEPS, dt=DT, history=True)


h1 = rollout()
h2 = rollout()

hid1, out1 = np.asarray(h1.gene_hidden), np.asarray(h1.gout)
hid2, out2 = np.asarray(h2.gene_hidden), np.asarray(h2.gout)
same = bool(np.array_equal(hid1, hid2) and np.array_equal(out1, out2))
if not same:
    raise SystemExit("ORACLE IS NOT DETERMINISTIC at a fixed input -- a differential test would "
                     "measure the reference's own noise. Stop here.")

gene = np.concatenate([hid1, out1], axis=-1)          # [T, N, NG] = concat([hidden, outputs])
udrive = np.asarray(h1.u_drive)
t = np.asarray(h1.t)

np.savez_compressed(
    os.path.join(OUT_DIR, "reference.npz"),
    t=t, gene=gene, gene_hidden=hid1, gout=out1, u_drive=udrive,
    gene0=gene0, u=u_vec, W_gene=W_gene, W_in=W_in, b=b, gamma=gamma,
)

# the input must stay a frozen snapshot across the whole rollout (the contract);
# a violation here would silently change what the Plexus side has to match.
u_frozen = bool(np.allclose(udrive, udrive[0]))
cell_spread = float(gene.std(axis=1).max())           # ~float32 noise for a homogeneous batch

summary = {{
    "seed": SEED, "n_cells": N, "hidden_size": HIDDEN, "out_size": OUT, "in_size": IN,
    "n_gene": NG, "n_steps": N_STEPS, "dt": DT, "n_frames": int(gene.shape[0]),
    "deterministic_at_fixed_input": same,
    "u_frozen_across_rollout": u_frozen,
    "max_cell_spread": cell_spread,
    "gene0_cell0": gene[0, 0].tolist(),
    "gene_final_cell0": gene[-1, 0].tolist(),
    "gene_min": float(gene.min()), "gene_max": float(gene.max()),
}}
with open(os.path.join(OUT_DIR, "summary.json"), "w") as f:
    json.dump(summary, f, indent=2)
print(json.dumps(summary, indent=2))

if not u_frozen:
    raise SystemExit("input drift detected -- u is not a frozen snapshot; the scenario is invalid.")

# --- one figure: cell-0 gene trajectories on a common scale -------------------------------- #
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(6.0, 3.6))
for i in range(NG):
    label = ("hidden " + str(i)) if i < HIDDEN else ("output " + str(i - HIDDEN))
    ax.plot(t, gene[:, 0, i], marker="o", ms=3, label=label)
ax.set_xlabel("t"); ax.set_ylabel("gene concentration")
ax.set_title("oracle: GeneNetworkConnectionist  dg/dt = sigma(W_gene g + W_in u + b) - gamma g")
ax.legend(fontsize=8, ncol=2)
fig.tight_layout()
fig.savefig(os.path.join(OUT_DIR, "reference.png"), dpi=130)
print("wrote reference.npz, summary.json, reference.png")
'''

with open(os.path.join(HERE, "gene_network_connectionist.py"), "w") as f:
    f.write(ORACLE)


# =========================================================================================== #
#  the Plexus spec  (regulate:connectionist through the engine)
# =========================================================================================== #
spec = {
    "general": {
        "name": "gene_network_connectionist",
        "seed": 0,
        "n_frames": N_STEPS,          # 21 recorded frames g(0)..g(20 dt), matching the oracle
        "dt": DT,
        "boundary": "free",
        "dim": 2,
        "world": [10.0, 10.0],
    },
    "sets": {
        "cell": {
            "n": N,
            # positions never move (no motion operator) -- they exist only so run_spec can draw a
            # strip and compute its generic spatial series; the differential test is on `gene`.
            "start": [[float(i) * 1.2 + 2.0, 5.0] for i in range(N)],
            "state": {
                "pos": {"width": 2},
                "vel": {"width": 2},
                # the evolving gene vector g = concat([hidden(2), outputs(3)]); recorded to the zarr
                "gene": {"width": NG, "integration": "first_order", "boundary": "free"},
                # the frozen sensed drive u; seeded once, never written again
                "drive": {"width": IN, "integration": "first_order", "boundary": "free"},
            },
        }
    },
    "fields": {},
    "operators": [
        # frame 0 only: set g(0) and u (broadcast identically to every cell => homogeneous batch).
        {"op": "seed_state", "at": "cell", "before_frame": 1,
         "values": {"gene": gene0.tolist(), "drive": u.tolist()}},
        # frames >=1: integrate the gene ODE one macro-step per frame, so recorded frame k = g(k dt)
        # and frame 0 = g(0), aligning with the oracle's s_0..s_20.
        {"op": "regulate", "implementation": "connectionist", "at": "cell", "after_frame": 1,
         "gene": "gene", "inputs": "drive", "hidden_size": HIDDEN, "substeps": SUBSTEPS,
         "W_gene": W_gene.tolist(), "W_in": W_in.tolist(), "b": b.tolist(), "gamma": gamma.tolist()},
    ],
    "schedule": ["seed_state", "regulate"],
    "plotting": {"background": "black", "point_size": 8.0},
}

header = (
    "# GENERATED by _oracle/scripts/_gen_gene_network_connectionist.py -- do not hand-edit.\n"
    "# Differential-test spec for regulate:connectionist. It integrates the IDENTICAL gene ODE from\n"
    "# the IDENTICAL initial condition and parameters as the oracle\n"
    "# (_oracle/scripts/gene_network_connectionist.py -> _oracle/runs/diff_gene_network_connectionist/).\n"
    "# regulate self-solves the macro-step with fixed-step RK4 (substeps=64) and returns (g(dt)-g0)/dt;\n"
    "# the engine's g += dt*delta recovers g(dt). seed_state@frame0 + regulate@frame>=1 make recorded\n"
    "# frame k = g(k*dt). The `gene` block is recorded to graphs_data/atlas/<name>/simulation.zarr.\n"
)
with open(os.path.join(PLEXUS, "config", "atlas", "gene_network_connectionist.yaml"), "w") as f:
    f.write(header)
    yaml.safe_dump(spec, f, default_flow_style=False, sort_keys=False)

print("wrote _oracle/scripts/gene_network_connectionist.py")
print("wrote config/atlas/gene_network_connectionist.yaml")
