#!/usr/bin/env python
"""minisite_section -- add the "Vertex + MPM" section to index.qmd, and copy its two clips.

    python minisite_section.py                    # insert (idempotent: replaces its own block)

WHY A SCRIPT AND NOT A HAND EDIT. The section carries the two runs' ACTUAL `spec_run.yaml`, which is
the site's convention -- every clip on the page opens the spec that produced it -- and a spec pasted by
hand is a spec that silently stops matching the run the next time either changes. This reads the specs
off disk, escapes them, and rewrites the block between two markers, so re-running it after a re-run
updates the page instead of duplicating it.
"""
from __future__ import annotations

import html
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
LOG = os.path.join(ROOT, "log", "okuda_ECM")
QMD = os.path.join(ROOT, "index.qmd")
GAL = os.path.join(ROOT, "gallery")
# THE RENDERED SITE IS COMMITTED, and quarto is not installed in this container. `index.qmd` is the
# source of truth and stays so; `docs/index.html` is patched with the EQUIVALENT block so the page goes
# live without a render, and the next `quarto render` reproduces it rather than changing it. The two
# differences quarto makes to this markup are mechanical and applied here: `class="anchored"` on the
# heading, and `&#x27;` normalised back to a literal apostrophe inside the spec blocks.
DOCS = os.path.join(ROOT, "docs", "index.html")
DOCS_GAL = os.path.join(ROOT, "docs", "gallery")

BEGIN = "<!-- BEGIN vertex-mpm (generated by prototype/ecm/minisite_section.py) -->"
END = "<!-- END vertex-mpm -->"

# The heading this section goes after, and its new name. The old one said "Turing x vertex"; the page
# now has two vertex-model couplings on it, so both are named the same way round.
ANCHOR_OLD = "<h3>Turing × vertex — patterning &amp; shaping a growing tissue</h3>"
ANCHOR_NEW = "<h3>Vertex + Turing — patterning &amp; shaping a growing tissue</h3>"


def split_concat(src, dst):
    """Cut the two-panel movie in half and play the halves in SEQUENCE: 3D first, then the section.

    ONE CLIP PER RUN, NOT TWO. A gallery card is a square block, and the movie is 2:1 -- shown whole it
    letterboxes to a third of the card's height and neither panel is legible. Two cards per run would fit
    but would spend six of the row's slots on three runs, and the confinement SERIES is the thing the row
    exists to show. Concatenating in time gives one square card per run that shows both views.

    CUT, NOT RE-RENDERED. The halves are the same pixels the movie has, so the page cannot end up
    disagreeing with the artefact it was made from.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    half = (w // 2) - (w // 2) % 2
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-filter_complex",
           f"[0:v]crop={half}:{h}:0:0[a];[0:v]crop={half}:{h}:{w - half}:0[b];[a][b]concat=n=2:v=1[o]",
           "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "21", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg split+concat failed for {dst}")


def _exe(name):
    """Next to the interpreter, not on PATH -- the conda env ships ffmpeg but the shell does not see it."""
    p = os.path.join(os.path.dirname(sys.executable), name)
    if os.path.exists(p):
        return p
    import shutil as _sh
    return _sh.which(name) or name


def _size(path):
    out = subprocess.check_output([_exe("ffprobe"), "-v", "error", "-select_streams", "v",
                                   "-show_entries", "stream=width,height",
                                   "-of", "csv=p=0", path]).decode().strip()
    w, h = (int(v) for v in out.split(",")[:2])
    return w, h


def card(video, name, spec_path, cap):
    spec = html.escape(open(spec_path).read().rstrip(), quote=False).replace("'", "&#x27;")
    return f"""  <figure class="sim-card">
    <video src="gallery/{video}" autoplay loop muted playsinline preload="metadata"></video>
    <figcaption>
      <span class="sim-name" tabindex="0">{name}<span class="sim-spec"><pre>{spec}</pre></span></span>
      <span class="sim-cap">{cap}</span>
    </figcaption>
  </figure>"""


def build(runs):
    """Three cards in the page's 3-column grid -- one per confinement, each playing 3D then section."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    return f"""{BEGIN}
<h3>Vertex + MPM — an epithelium loading an extracellular matrix</h3>
<p class="opk">Two Levels, two solvers, one experiment: the <b>vertex</b> shell of the section above grows
and divides inside a <b>material-point matrix</b> (the MLS-MPM cycle below) seeded as fibres. The
epithelium is the real <code>cellfix_B_new</code> run — 200 cells to ~6,000, its own mechanics untouched
— and its apical surface is a moving boundary the fibres feel: they are dragged, splayed and put under
stress, coloured by the local volume change |J−1| so the <b>stress front</b> travelling outward from the
tissue is the thing you watch. Adding two <b>solid blocks</b> above and below breaks the symmetry:
blocked in one axis, the epithelium grows into the other two and a sphere becomes an <b>ovoid</b>. Each
clip plays the 3D view first, then a cross-section through the same plane — the monolayer is one cell
deep, the lumen is hollow, the fibres are cut where they cross, and the blocks are the grey bands.</p>
<p class="opk-ref">Reference — the epithelium is the 3D active vertex model of
<a href="https://www.nature.com/articles/s41598-018-20678-6">Okuda et&nbsp;al. (2018)</a> on the
<a href="https://github.com/DamCB/tyssue">Tyssue</a> mesh; the matrix is MLS-MPM
(<a href="https://github.com/yuanming-hu/taichi_mpm">Hu et&nbsp;al. 2018</a>). The coupling and the
<code>ecm_seed</code> / <code>cell_to_ecm</code> / <code>cell_exclude_3d</code> /
<code>ecm_stress</code> / <code>plate_confine_3d</code> operators are ours
(<code>prototype/ecm</code>).</p>
<div class="sim-gallery g3">
{cards}
</div>
{END}"""


def main():
    R3 = [
        ("30_epi2_soft_E5", "vertex_mpm_free", "unconfined",
         "the control: a growing, dividing epithelium presses into a soft fibrous matrix and stays a "
         "SPHERE (oblateness 1.01) at ~6,000 cells. First contact at frame 32; by the end 89% of the "
         "matrix is strained and the front has reached the wall of the box"),
        ("52_aniso_growth_oblate", "vertex_mpm_grown", "grown into an ovoid",
         "the matrix is 3x denser within 55 deg of the vertical and resists 2.6x harder there, so "
         "<code>ecm_growth_gate_3d</code> slows the cell cycle at the poles. The sphere GROWS into an "
         "ovoid instead of being pressed into one: oblateness 1.22"),
        ("58_oblcav_oblate", "vertex_mpm_grown_oblate", "ovoid from first contact",
         "an OBLATE cavity, so the tissue meets the fibres at its poles first and the stress is "
         "directional from first contact -- pole/equator 14.7, against 1.5 for a round cavity. "
         "Oblateness 1.43, grown in all three axes. Nothing presses on it"),
    ]
    runs = [(d, f"{v}.mp4", lbl, os.path.join(LOG, d, "spec_run.yaml"), cap)
            for d, v, lbl, cap in R3]
    missing = [r for r, *_ in runs if not os.path.exists(os.path.join(LOG, r, "movie.mp4"))]
    if missing:
        sys.exit(f"no movie.mp4 for {missing} -- run them before writing the page")

    os.makedirs(GAL, exist_ok=True)
    for d, v, *_ in runs:
        src = os.path.join(LOG, d, "movie.mp4")
        split_concat(src, os.path.join(GAL, v))
        print(f"[minisite] gallery/{v} <- {d}/movie.mp4  "
              f"({os.path.getsize(os.path.join(GAL, v)) / 1e6:.1f} MB, 3D then section)")

    import shutil
    for tgt, rendered in ((QMD, False), (DOCS, True)):
        if rendered and not os.path.exists(DOCS):
            print("[minisite] no docs/index.html -- source updated only; run `quarto render`")
            continue
        _patch(tgt, build(runs), rendered=rendered)
    if os.path.isdir(DOCS_GAL):
        for d, v, *_ in runs:
            shutil.copy2(os.path.join(GAL, v), os.path.join(DOCS_GAL, v))
        print("[minisite] videos copied into docs/gallery/")
    return


def _patch(path, block, rendered=False):
    if rendered:
        block = block.replace("<h3>", '<h3 class="anchored">').replace("&#x27;", "'")
    s = open(path).read()
    anchor_old = ANCHOR_OLD if not rendered else ANCHOR_OLD.replace("<h3>", '<h3 class="anchored">')
    anchor_new = ANCHOR_NEW if not rendered else ANCHOR_NEW.replace("<h3>", '<h3 class="anchored">')
    if BEGIN in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        anchor = anchor_old if anchor_old in s else anchor_new
        if anchor not in s:
            sys.exit(f"anchor heading not found in {path}")
        # AFTER the anchor section, which ends at the `</div>` closing its gallery -- i.e. just before
        # the next h3. Inserting straight after the heading would put this section INSIDE the previous
        # one's prose.
        k = s.index(anchor)
        tag = "<h3" if rendered else "<h3>"
        nxt = s.index(tag, k + len(anchor))
        s = s[:nxt] + block + "\n\n" + s[nxt:]
        what = "inserted"
    s = s.replace(anchor_old, anchor_new)
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: {what}; heading renamed to 'Vertex + Turing'")


if __name__ == "__main__":
    main()
