#!/usr/bin/env python
"""minisite_section -- add the "Vertex + MPM" section to index.qmd, and copy its two clips.

    python minisite_section.py                    # insert (idempotent: replaces its own block)

WHY A SCRIPT AND NOT A HAND EDIT. The section carries the two runs' ACTUAL `spec_run.yaml`, which is
the site's convention -- every clip on the page opens the spec that produced it -- and a spec pasted by
hand is a spec that silently stops matching the run the next time either changes. This reads the specs
off disk, escapes them, and rewrites the block between two markers, so re-running it after a re-run
updates the page instead of duplicating it.
"""
from __future__ import annotations

import html
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
LOG = os.path.join(ROOT, "log", "okuda_ECM")
QMD = os.path.join(ROOT, "index.qmd")
GAL = os.path.join(ROOT, "gallery")
# THE RENDERED SITE IS COMMITTED, and quarto is not installed in this container. `index.qmd` is the
# source of truth and stays so; `docs/index.html` is patched with the EQUIVALENT block so the page goes
# live without a render, and the next `quarto render` reproduces it rather than changing it. The two
# differences quarto makes to this markup are mechanical and applied here: `class="anchored"` on the
# heading, and `&#x27;` normalised back to a literal apostrophe inside the spec blocks.
DOCS = os.path.join(ROOT, "docs", "index.html")
DOCS_GAL = os.path.join(ROOT, "docs", "gallery")

BEGIN = "<!-- BEGIN vertex-mpm (generated by prototype/ecm/minisite_section.py) -->"
END = "<!-- END vertex-mpm -->"

# The heading this section goes after, and its new name. The old one said "Turing x vertex"; the page
# now has two vertex-model couplings on it, so both are named the same way round.
ANCHOR_OLD = "<h3>Turing × vertex — patterning &amp; shaping a growing tissue</h3>"
ANCHOR_NEW = "<h3>Vertex + Turing — patterning &amp; shaping a growing tissue</h3>"


def split_concat(src, dst):
    """Cut the two-panel movie in half and play the halves in SEQUENCE: 3D first, then the section.

    ONE CLIP PER RUN, NOT TWO. A gallery card is a square block, and the movie is 2:1 -- shown whole it
    letterboxes to a third of the card's height and neither panel is legible. Two cards per run would fit
    but would spend six of the row's slots on three runs, and the confinement SERIES is the thing the row
    exists to show. Concatenating in time gives one square card per run that shows both views.

    CUT, NOT RE-RENDERED. The halves are the same pixels the movie has, so the page cannot end up
    disagreeing with the artefact it was made from.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    half = (w // 2) - (w // 2) % 2
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-filter_complex",
           f"[0:v]crop={half}:{h}:0:0[a];[0:v]crop={half}:{h}:{w - half}:0[b];[a][b]concat=n=2:v=1[o]",
           "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "21", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg split+concat failed for {dst}")



def quad_concat(src, dst, keep=0.78):
    """Cut a 2x2 movie into its four panels and play them in SEQUENCE, each cropped to its subject.

    THE 2x2 LAYOUT DOES NOT SURVIVE A GALLERY CARD. Four panels in a square card is each panel at a
    quarter linear scale, and the crosslink network -- the thing these runs exist to show -- is a mesh
    whose spacing is already near a pixel. Played one after another, each panel gets the whole card.

    `keep` crops each quadrant about ITS OWN CENTRE, which does two things at once: the spheroid stays
    centred (it is drawn centred in every panel), and the run label in the top-left panel is cropped away
    with the margin, so no frame carries a caption the page has not written itself.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    qw, qh = w // 2, h // 2
    cw = int(qw * keep) - int(qw * keep) % 2
    ch = int(qh * keep) - int(qh * keep) % 2
    ox, oy = (qw - cw) // 2, (qh - ch) // 2
    parts, labels = [], []
    for n, (qx, qy) in enumerate(((0, 0), (qw, 0), (0, qh), (qw, qh))):
        parts.append(f"[0:v]crop={cw}:{ch}:{qx + ox}:{qy + oy}[p{n}]")
        labels.append(f"[p{n}]")
    fc = ";".join(parts) + ";" + "".join(labels) + "concat=n=4:v=1[o]"
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-filter_complex", fc,
           "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "21", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg quad+concat failed for {dst}")


def _exe(name):
    """Next to the interpreter, not on PATH -- the conda env ships ffmpeg but the shell does not see it."""
    p = os.path.join(os.path.dirname(sys.executable), name)
    if os.path.exists(p):
        return p
    import shutil as _sh
    return _sh.which(name) or name


def _size(path):
    out = subprocess.check_output([_exe("ffprobe"), "-v", "error", "-select_streams", "v",
                                   "-show_entries", "stream=width,height",
                                   "-of", "csv=p=0", path]).decode().strip()
    w, h = (int(v) for v in out.split(",")[:2])
    return w, h


def card(video, name, spec_path, cap):
    spec = html.escape(open(spec_path).read().rstrip(), quote=False).replace("'", "&#x27;")
    return f"""  <figure class="sim-card">
    <video src="gallery/{video}" autoplay loop muted playsinline preload="metadata"></video>
    <figcaption>
      <span class="sim-name" tabindex="0">{name}<span class="sim-spec"><pre>{spec}</pre></span></span>
      <span class="sim-cap">{cap}</span>
    </figcaption>
  </figure>"""


def build(runs, runs2=()):
    """Two rows: the confinement series, then the two new levels drawn on their own."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    cards2 = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs2)
    return f"""{BEGIN}
<h3>Vertex + MPM — an epithelium loading an extracellular matrix</h3>
<p class="opk">Two Levels, two solvers, one experiment: the <b>vertex</b> shell of the section above grows
and divides inside a <b>material-point matrix</b> (the MLS-MPM cycle below) seeded as fibres. The
epithelium is the real <code>cellfix_B_new</code> run — 200 cells to ~6,000, its own mechanics untouched
— and its apical surface is a moving boundary the fibres feel: they are dragged, splayed and put under
stress, coloured by the local volume change |J−1| so the <b>stress front</b> travelling outward from the
tissue is the thing you watch. Adding two <b>solid blocks</b> above and below breaks the symmetry:
blocked in one axis, the epithelium grows into the other two and a sphere becomes an <b>ovoid</b>. Each
clip plays the 3D view first, then a cross-section through the same plane — the monolayer is one cell
deep, the lumen is hollow, the fibres are cut where they cross, and the blocks are the grey bands.</p>
<p class="opk-ref">Reference — the epithelium is the 3D active vertex model of
<a href="https://www.nature.com/articles/s41598-018-20678-6">Okuda et&nbsp;al. (2018)</a> on the
<a href="https://github.com/DamCB/tyssue">Tyssue</a> mesh; the matrix is MLS-MPM
(<a href="https://github.com/yuanming-hu/taichi_mpm">Hu et&nbsp;al. 2018</a>). The coupling and the
<code>seed_ecm</code> / <code>cell_to_ecm</code> / <code>cell_exclude_3d</code> /
<code>ecm_stress</code> / <code>plate_confine_3d</code> operators are ours
(<code>prototype/ecm</code>).</p>
<div class="sim-gallery g3">
{cards}
</div>
<h3>Basement membrane + junctions</h3>
<p class="opk">The same tissue, with two things that were not there before. The <b>basement membrane</b>
is a sheet of nodes joined by explicit <b>crosslinks</b>, laid down outside the epithelium and tied to
it by one <b>integrin</b> spring per node — anchored to a fixed direction, so the sheet stretches as the
tissue grows instead of sliding over it. It is <b>secreted</b>: it starts with a ninth of its material
and lays down more as the surface expands, because a sphere that triples in radius needs nine times the
area covered. The <b>junctions</b> are the cell–cell contacts, each carrying its own <b>myosin</b>, which
is recruited where a junction is longer than average. Each clip plays the four panels in turn — the
whole tissue, a cross-section, the membrane alone with its crosslinks coloured by how far they are
stretched (blue slack, red at the breaking point), and the junction network alone coloured by myosin.</p>
<p class="opk-ref">Reference — the crosslinked-sheet and secretion picture follows
<a href="https://doi.org/10.1016/j.devcel.2023.01.004">Ku &amp; Bilder (2023)</a> and
<a href="https://doi.org/10.1242/dev.200456">T&ouml;pfer et&nbsp;al. (2022)</a>; junctional myosin
recruitment by tension is the standard vertex-model feedback. The
<code>seed_basement_membrane</code> / <code>basement_membrane_bond</code> /
<code>basement_membrane_secrete</code> / <code>integrin_adhesion</code> / <code>junction_myosin</code>
operators are ours (<code>prototype/ecm</code>).</p>
<div class="sim-gallery g3">
{cards2}
</div>
{END}"""


def main():
    R3 = [
        ("30_epi2_soft_E5", "vertex_mpm_free", "unconfined",
         "the control: a growing, dividing epithelium presses into a soft fibrous matrix and stays a "
         "SPHERE (oblateness 1.01) at ~6,000 cells. First contact at frame 32; by the end 89% of the "
         "matrix is strained and the front has reached the wall of the box"),
        ("27_epi_ecm_fibres_long", "vertex_mpm_fibres", "the fibres, at length",
         "the same coupling run out: an epithelium pressing into a fibre matrix for the full growth, "
         "so the stress front has time to cross the box. Nothing confines it -- this is what the "
         "matrix does when only the tissue's own growth loads it"),
        ("58_oblcav_oblate", "vertex_mpm_grown_oblate", "grown into an ovoid",
         "an oblate cavity, so the tissue meets the fibres at its poles first and the matrix resists "
         "there 14.7x harder. <code>ecm_growth_gate_3d</code> slows the cell cycle where it resists, so "
         "the sphere GROWS to oblateness 1.43. Nothing presses on it"),
        ("48_block_elastic_g40", "vertex_mpm_pressed", "pressed by an elastic solid",
         "the same shape the other way. Two solid blocks -- a second MPM body, 130x stiffer than the "
         "matrix, so they deform too -- press the tissue to oblateness 1.41, indistinguishable from "
         "the grown 1.43 beside it. Two mechanisms, one shape"),
    ]
    R4 = [
        ("69_graph_reference", "bm_reference", "reference",
         "the sheet at work. 37,427 nodes joined by 180,304 crosslinks, covering the whole surface, "
         "stretched to 10% on average — teal-green on a scale whose top is the breaking point"),
        ("71_fast_remodelling", "bm_fast_remodel", "fast remodelling",
         "the same network — 187,781 crosslinks, same coverage — but the crosslinks forget being "
         "stretched four times faster, so the sheet never builds tension and sits at 3%. Uniformly "
         "dark blue. Turnover, not strength, sets how hard a membrane pulls"),
        ("73_no_adhesion", "bm_no_adhesion", "no adhesion",
         "the control: with the integrin springs removed the sheet SLIDES over the epithelium instead "
         "of being stretched by it, and is the only run that loses coverage (0.89) — it goes where the "
         "matrix pushes it. The strain in the other two is real because this one has none"),
    ]
    runs = [(d, f"{v}.mp4", lbl, os.path.join(LOG, d, "spec_run.yaml"), cap)
            for d, v, lbl, cap in R3]
    runs2 = [(d, f"{v}.mp4", lbl, os.path.join(LOG, d, "spec_run.yaml"), cap)
             for d, v, lbl, cap in R4]
    missing = [r for r, *_ in runs + runs2 if not os.path.exists(os.path.join(LOG, r, "movie.mp4"))]
    if missing:
        sys.exit(f"no movie.mp4 for {missing} -- run them before writing the page")

    os.makedirs(GAL, exist_ok=True)
    for d, v, *_ in runs:
        src = os.path.join(LOG, d, "movie.mp4")
        split_concat(src, os.path.join(GAL, v))
        print(f"[minisite] gallery/{v} <- {d}/movie.mp4  "
              f"({os.path.getsize(os.path.join(GAL, v)) / 1e6:.1f} MB, 3D then section)")
    for d, v, *_ in runs2:
        src = os.path.join(LOG, d, "movie.mp4")
        quad_concat(src, os.path.join(GAL, v))
        print(f"[minisite] gallery/{v} <- {d}/movie.mp4  "
              f"({os.path.getsize(os.path.join(GAL, v)) / 1e6:.1f} MB, four panels in turn)")

    import shutil
    for tgt, rendered in ((QMD, False), (DOCS, True)):
        if rendered and not os.path.exists(DOCS):
            print("[minisite] no docs/index.html -- source updated only; run `quarto render`")
            continue
        _patch(tgt, build(runs, runs2), rendered=rendered)
    if os.path.isdir(DOCS_GAL):
        # `runs + runs2`. Copying only the first row left the new clips out of docs/gallery while the
        # page that referenced them was patched -- three cards pointing at files the site did not have.
        for d, v, *_ in runs + runs2:
            shutil.copy2(os.path.join(GAL, v), os.path.join(DOCS_GAL, v))
        print("[minisite] videos copied into docs/gallery/")
    return


def _patch(path, block, rendered=False):
    if rendered:
        block = block.replace("<h3>", '<h3 class="anchored">').replace("&#x27;", "'")
    s = open(path).read()
    anchor_old = ANCHOR_OLD if not rendered else ANCHOR_OLD.replace("<h3>", '<h3 class="anchored">')
    anchor_new = ANCHOR_NEW if not rendered else ANCHOR_NEW.replace("<h3>", '<h3 class="anchored">')
    if BEGIN in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        anchor = anchor_old if anchor_old in s else anchor_new
        if anchor not in s:
            sys.exit(f"anchor heading not found in {path}")
        # AFTER the anchor section, which ends at the `</div>` closing its gallery -- i.e. just before
        # the next h3. Inserting straight after the heading would put this section INSIDE the previous
        # one's prose.
        k = s.index(anchor)
        tag = "<h3" if rendered else "<h3>"
        nxt = s.index(tag, k + len(anchor))
        s = s[:nxt] + block + "\n\n" + s[nxt:]
        what = "inserted"
    s = s.replace(anchor_old, anchor_new)
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: {what}; heading renamed to 'Vertex + Turing'")


if __name__ == "__main__":
    main()
