#!/usr/bin/env python
"""minisite_section -- add the "Vertex + MPM" section to index.qmd, and copy its two clips.

    python minisite_section.py                    # insert (idempotent: replaces its own block)

WHY A SCRIPT AND NOT A HAND EDIT. The section carries the two runs' ACTUAL `spec_run.yaml`, which is
the site's convention -- every clip on the page opens the spec that produced it -- and a spec pasted by
hand is a spec that silently stops matching the run the next time either changes. This reads the specs
off disk, escapes them, and rewrites the block between two markers, so re-running it after a re-run
updates the page instead of duplicating it.
"""
from __future__ import annotations

import html
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
LOG = os.path.join(ROOT, "log", "okuda_ECM")
QMD = os.path.join(ROOT, "index.qmd")
GAL = os.path.join(ROOT, "gallery")
# THE RENDERED SITE IS COMMITTED, and quarto is not installed in this container. `index.qmd` is the
# source of truth and stays so; `docs/index.html` is patched with the EQUIVALENT block so the page goes
# live without a render, and the next `quarto render` reproduces it rather than changing it. The two
# differences quarto makes to this markup are mechanical and applied here: `class="anchored"` on the
# heading, and `&#x27;` normalised back to a literal apostrophe inside the spec blocks.
DOCS = os.path.join(ROOT, "docs", "index.html")
DOCS_GAL = os.path.join(ROOT, "docs", "gallery")

BEGIN = "<!-- BEGIN vertex-mpm (generated by prototype/ecm/minisite_section.py) -->"
END = "<!-- END vertex-mpm -->"
# The SECOND row of the Vertex + Turing section, which is a different experiment in the same
# section rather than a section of its own: same shell, same RD machinery, one more field.
BEGIN2 = "<!-- BEGIN vertex-turing-death (generated by prototype/ecm/minisite_section.py) -->"
END2 = "<!-- END vertex-turing-death -->"
LOG_OKUDA = os.path.join(ROOT, "log", "okuda")

# The heading this section goes after, and its new name. The old one said "Turing x vertex"; the page
# now has two vertex-model couplings on it, so both are named the same way round.
ANCHOR_OLD = "<h3>Turing × vertex — patterning &amp; shaping a growing tissue</h3>"
ANCHOR_NEW = "<h3>Vertex + Turing — patterning &amp; shaping a growing tissue</h3>"


def _content_box(src, x0, wid, hei, n=9, thresh=14, skip_top=0.0, skip_bot=0.0):
    """The bounding box of everything that is not background, in a REGION of the frame.

    Both panels of these movies are drawn on black with matplotlib's own margins around them, and
    the margins are not symmetric -- the 3D axes sit left of centre and the 2D section right of it,
    which is exactly what a viewer sees as "the first half is a bit to the left and the second a bit
    to the right". Centring is therefore a property of the CONTENT, not of the frame, and it has to
    be measured rather than nudged.

    Sampled over `n` frames and unioned, because the content MOVES: a box measured on one frame
    crops away the part of the run that happens later. Threshold on the max channel, so a dim strand
    counts as content and JPEG-ish ringing around the border does not.
    """
    import glob
    import tempfile
    import numpy as _np
    import matplotlib.image as _mpimg
    d = tempfile.mkdtemp(prefix="mscrop_")
    subprocess.check_call([_exe("ffmpeg"), "-y", "-loglevel", "error", "-i", src,
                           "-vf", "select='not(mod(n\\," + str(max(1, _nframes(src) // n))
                           + "))'",
                           "-vsync", "vfr", os.path.join(d, "f%03d.png")])
    xs0, xs1, ys0, ys1 = wid, 0, hei, 0
    for f in sorted(glob.glob(os.path.join(d, "*.png"))):
        a = _mpimg.imread(f)
        a = (a[:, :, :3].max(axis=2) * (255 if a.dtype.kind == "f" else 1))[:hei, x0:x0 + wid]
        # THE PRINTED LABEL IS NOT CONTENT. Every one of these movies stamps the run name, the frame
        # and the cell count in the top-left corner, in white on black -- so a bounding box that
        # measures brightness puts the box around the TEXT as well as around the tissue, and the
        # crop that follows keeps the text and shrinks the subject. `skip_top` is the fraction of
        # the panel the label occupies; measured below it, the box is the tissue's.
        if skip_top:
            a = a[int(skip_top * hei):]
        # AND THE SCALE BAR IS NOT CONTENT EITHER. The okuda movies draw a white rule and its length
        # in the bottom margin of every panel; a box that includes it is a box around the bar, and
        # the square crop that follows then keeps the bar and shrinks the tissue.
        if skip_bot:
            a = a[:max(1, a.shape[0] - int(skip_bot * hei))]
        m = a > thresh
        if not m.any():
            continue
        cols, rows = _np.nonzero(m.any(0))[0], _np.nonzero(m.any(1))[0]
        xs0, xs1 = min(xs0, int(cols[0])), max(xs1, int(cols[-1]))
        ys0, ys1 = min(ys0, int(rows[0])), max(ys1, int(rows[-1]))
    import shutil as _sh
    _sh.rmtree(d, ignore_errors=True)
    if xs1 <= xs0 or ys1 <= ys0:
        return wid // 2, hei // 2, min(wid, hei)
    return (xs0 + xs1) // 2, (ys0 + ys1) // 2, max(xs1 - xs0, ys1 - ys0)


def _nframes(src):
    out = subprocess.check_output([_exe("ffprobe"), "-v", "error", "-select_streams", "v",
                                   "-count_frames", "-show_entries", "stream=nb_read_frames",
                                   "-of", "csv=p=0", src]).decode().strip()
    return max(1, int(out.split(",")[0]))


def split_concat(src, dst, recentre=True, skip_top=0.0):
    """Cut the two-panel movie in half and play the halves in SEQUENCE: 3D first, then the section.

    ONE CLIP PER RUN, NOT TWO. A gallery card is a square block, and the movie is 2:1 -- shown whole it
    letterboxes to a third of the card's height and neither panel is legible. Two cards per run would fit
    but would spend six of the row's slots on three runs, and the confinement SERIES is the thing the row
    exists to show. Concatenating in time gives one square card per run that shows both views.

    CUT, NOT RE-RENDERED. The halves are the same pixels the movie has, so the page cannot end up
    disagreeing with the artefact it was made from.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    half = (w // 2) - (w // 2) % 2
    ax, ay, aw = 0, 0, half
    bx, by, bw = w - half, 0, half
    side = h
    if recentre:
        # EACH HALF CENTRED ON ITS OWN CONTENT, and both cropped to ONE size, because `concat`
        # requires it. The window is the larger of the two contents plus a fifth, so neither panel
        # is cut and the smaller one is not blown up past the other.
        cxa, cya, sa = _content_box(src, 0, half, h, skip_top=skip_top)
        cxb, cyb, sb = _content_box(src, w - half, half, h, skip_top=skip_top)
        cya += int(skip_top * h); cyb += int(skip_top * h)      # back into full-frame rows
        side = min(h, half, int(1.2 * max(sa, sb)))
        side -= side % 2
        ax = min(max(cxa - side // 2, 0), half - side)
        ay = min(max(cya - side // 2, 0), h - side)
        bx = (w - half) + min(max(cxb - side // 2, 0), half - side)
        by = min(max(cyb - side // 2, 0), h - side)
        aw = bw = side
        print(f"[minisite]   recentred: {side}x{side} windows at ({ax},{ay}) and ({bx},{by}) "
              f"of {w}x{h}", flush=True)
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-filter_complex",
           f"[0:v]crop={aw}:{side}:{ax}:{ay}[a];[0:v]crop={bw}:{side}:{bx}:{by}[b];"
           f"[a][b]concat=n=2:v=1[o]",
           "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "21", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg split+concat failed for {dst}")



def crop_panel(src, dst, panel="left", skip_top=0.09, skip_bot=0.14, pad=1.20):
    """Keep the LEFT panel only, as a square window centred on what is drawn in it.

    THE MOVIE IS A CONTACT SHEET, NOT A CLIP. `log/okuda/*/movie.mp4` is drawn for reading a run:
    two views side by side, each labelled with its elevation, each with a scale bar, and a section
    inset in the corner. A gallery card is one square block, so the page takes one panel -- the side
    view -- and the crop has to be measured rather than guessed, because the tissue GROWS: a window
    fitted to the first frame cuts the last one off.

    `skip_top` / `skip_bot` are the fractions of the panel its printed text occupies -- the "side
    elev 18" label above and the scale bar below. Measured between them, the box is the tissue's;
    the window is then clamped to stay inside those margins, so no frame of the result carries a
    caption the page has not written itself.

    `panel="right"` takes the top view instead, for a run whose interesting face is on top. THE BOX
    IS STILL MEASURED ON THE LEFT PANEL, and deliberately: the right one carries the section-ring
    inset in its bottom corner, which is bright, is not the tissue, and drags any box measured
    around it out to the frame edge. Both panels draw the same tissue at the same axes scale and
    the same centre, so the left panel's window is the right one's window plus the offset.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    half = (w // 2) - (w // 2) % 2
    top, bot = int(skip_top * h), int(skip_bot * h)
    cx, cy, sz = _content_box(src, 0, half, h, skip_top=skip_top, skip_bot=skip_bot)
    cy += top
    side = min(half, h - top - bot, int(pad * sz))
    side -= side % 2
    x = min(max(cx - side // 2, 0), half - side)
    y = min(max(cy - side // 2, top), h - bot - side)
    if panel == "right":
        x += w - half
    print(f"[minisite]   panel crop: {side}x{side} at ({x},{y}) of {w}x{h}", flush=True)
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-vf", f"crop={side}:{side}:{x}:{y}",
           "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg panel crop failed for {dst}")


def _exe(name):
    """Next to the interpreter, not on PATH -- the conda env ships ffmpeg but the shell does not see it."""
    p = os.path.join(os.path.dirname(sys.executable), name)
    if os.path.exists(p):
        return p
    import shutil as _sh
    return _sh.which(name) or name


def _size(path):
    out = subprocess.check_output([_exe("ffprobe"), "-v", "error", "-select_streams", "v",
                                   "-show_entries", "stream=width,height",
                                   "-of", "csv=p=0", path]).decode().strip()
    w, h = (int(v) for v in out.split(",")[:2])
    return w, h


def card(video, name, spec_path, cap):
    spec = html.escape(open(spec_path).read().rstrip(), quote=False).replace("'", "&#x27;")
    return f"""  <figure class="sim-card">
    <video src="gallery/{video}" autoplay loop muted playsinline preload="metadata"></video>
    <figcaption>
      <span class="sim-name" tabindex="0">{name}<span class="sim-spec"><pre>{spec}</pre></span></span>
      <span class="sim-cap">{cap}</span>
    </figcaption>
  </figure>"""



def replace_card(video, name, spec_path, cap, files=(), new_video=None):
    """Rewrite ONE hand-written gallery card in place, matched on the clip it plays.

    The generated block below owns the Vertex + MPM section; the cards in the older sections are
    part of the page's own prose and are not in it. Rewriting one by hand would break the same rule
    this file exists to enforce -- that a card's spec is READ from the run that produced it rather
    than pasted -- so it is done here, keyed on the video filename, which is the one thing about a
    card that does not change when its content does.
    """
    # THE CLIP A CARD PLAYS AND THE CLIP IT IS FOUND BY ARE NOT THE SAME QUESTION. Two cards on
    # this page play `tyssue_grow_divide.mp4` -- the vertex model's own, and the growth phase of the
    # Turing section -- so overwriting that FILE changes both, and the second one's spec then
    # describes a run its clip no longer shows. A new card gets a new filename and only the card
    # named here is repointed.
    blk = card(new_video or video, name, spec_path, cap)
    for path, rendered in files:
        if not os.path.exists(path):
            continue
        s = open(path).read()
        i = s.find(f'<video src="gallery/{video}"')
        if i < 0:
            print(f"[minisite] {os.path.basename(path)}: no card plays {video} -- not replaced")
            continue
        # `<figure` AND NOT `<figure class="sim-card">`. Quarto renders the class list as
        # `sim-card figure`, so matching the bare class found nothing in the rendered page, `rfind`
        # returned -1, and the "replacement" was appended at the END OF THE FILE -- a second card
        # four thousand lines below the gallery it belongs to, with the original still in place.
        a = s.rfind("<figure", 0, i)
        b = s.index("</figure>", i) + len("</figure>")
        out = blk if not rendered else blk.replace("&#x27;", "'")
        open(path, "w").write(s[:a] + out.lstrip() + s[b:])
        print(f"[minisite] {os.path.basename(path)}: card for {video} replaced ({name})")


def build(runs):
    """One row: the interface under the three loadings it has to survive -- press, drag, breach."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    return f"""{BEGIN}
<h3>Vertex + MPM</h3>
<p class="opk">Two Levels, two solvers, one interface: a <b>triangulated surface</b> with mass and
springs — the vertex model's own geometry — pressed into a <b>block of MPM material</b> (the MLS-MPM
cycle below), coupled particle-to-face so the reaction really returns to the mesh rather than being
applied to the material alone. No tissue and no matrix here: this is the interface itself, on the
smallest rig that can falsify it, under the three loadings that can break it. <b>Press</b>: the
surface indents the block against a rigid floor and lifts off again, and the material has to push
back and recover. <b>Drag</b>: a sticky pad presses to a fixed depth and then travels sideways over a
block pinned at its base, so the load is tangential — it ploughs, heaps material ahead of itself and
<b>shears</b> what it drags over, coloured by von Mises because a drag changes shape at constant
volume and a volumetric colour is blank exactly where the physics is. <b>Breach</b>: the surface
carries a hole and the box is closed on all four sides, so the material has nowhere to go but
<b>through</b>, and it extrudes as a plug. Each clip plays the 3D view first, then a cross-section
through the same instant; the grey lines are the rigid floor and, in the last one, the walls.</p>
<p class="opk-ref">Reference — the contact is the ICFEMP particle-to-surface scheme of
<a href="https://doi.org/10.1016/j.cma.2015.04.005">Chen, Qiu, Zhang &amp; Lian (2015),
<i>Comput. Methods Appl. Mech. Engrg.</i> 293:1–19</a>, chosen over grid-node coupling
(<a href="https://doi.org/10.1016/j.cma.2011.07.014">Lian, Zhang &amp; Liu 2011,
<i>CMAME</i> 200:3482</a>) because that one needs the mesh and the grid to be comparable in size and
ours are not; the solid is MLS-MPM
(<a href="https://github.com/yuanming-hu/taichi_mpm">Hu et&nbsp;al. 2018</a>), the surface is the mesh
of the 3D active vertex model of
<a href="https://www.nature.com/articles/s41598-018-20678-6">Okuda et&nbsp;al. (2018)</a>. The
implementation is ours (<code>prototype/ecm</code>): these three clips are the interface rig
<code>test_03_mesh_contact</code>, and the operator that carries the same scheme onto a curved,
dividing surface is <code>mesh_contact</code>, with <code>seed_ecm</code> /
<code>cell_to_ecm</code> / <code>cell_exclude_3d</code> / <code>ecm_stress</code> beside it.</p>
<div class="sim-gallery g3">
{cards}
</div>
{END}"""


def _measured(run):
    """The run's own `metrics.json`, so a number in a caption is a number the run reported.

    The same rule as the specs: the page quotes runs, and a quantity typed by hand is one that stops
    being true the next time the run changes without anybody noticing.
    """
    return json.load(open(os.path.join(LOG, run, "metrics.json")))


def build2(runs):
    """The second row of Vertex + Turing: two Turing fields, one growing the tissue and one killing
    cells in it. No heading of its own -- it is the same section with one more field in it."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    return f"""{BEGIN2}
<p class="opk"><b>Division and death, patterned by a second field.</b> The same shell, with a
<b>second Gray–Scott system</b> living on the same cells and reading none of the first one's
numbers: species&nbsp;A (red) is the one <code>grow_3d</code> and <code>divide_3d</code> listen to,
species&nbsp;B has twice the diffusivities — so a coarser wavelength — and where B falls LOW,
<code>apoptosis_3d</code> marks the cell to die. That is the point of the second field: one field
cannot put growth and death in different places, because every operator reading it reads the same
number in the same cell. <b>Blue is a cell already marked</b> — the mark is the only visible part,
because a marked cell then shrinks at a fixed rate, is removed, and its neighbours close the gap by
a T1 exchange, so what you see is the pattern of who is <i>about</i> to go. The first two clips
differ in one number — the ceiling on how much of the population may be under sentence at once, 2%
against 25% — and the third is the control that says why any of this needs a second field: with only
one, death fires below a threshold on the very chemical that drives growth, so it lands in the
<b>antiphase</b> of the growth pattern and nowhere else.</p>
<div class="sim-gallery g3">
{cards}
</div>
{END2}"""


def main():
    sh, br = _measured("03f_mesh_shear"), _measured("03g_mesh_breach")
    R3 = [
        ("03c_mesh_contact_hole", "vertex_mpm_free", "press",
         "a triangulated surface pressed into an MPM block against a rigid floor, then lifted off "
         "again. The reaction really returns to the mesh (momentum residual 1.4e-7, float32 "
         "precision) and friction changes the slip fourfold -- not MPM's automatic weld"),
        ("03f_mesh_shear", "vertex_mpm_shear", "drag",
         f"the tangential half of the same law, as a loading rather than as a number. A sticky pad "
         f"presses {sh['indent_cells']:.1f} grid cells in and then travels "
         f"{sh['drag_box_units']:.2f} box units at that depth across a matrix pinned at its base: "
         f"it ploughs, heaps the material ahead of itself and shears what it drags over -- coloured "
         f"by von Mises, because a drag changes shape at constant volume. Momentum still balances "
         f"to {sh['momentum_residual_max']:.0e} of the applied force across "
         f"{sh['contacts_max']:,} contacts"),
        ("03g_mesh_breach", "vertex_mpm_breach", "breach",
         f"what a hole in the surface is FOR. The box is closed on all four sides and the matrix is "
         f"nearly incompressible, so a press {br['indent_cells']:.1f} grid cells deep has no rim to "
         f"escape through: it extrudes through the breach as a plug standing "
         f"{br['plug_above_surface_cells']:.1f} cells proud of the plate. A penalty contact is not a "
         f"wall -- {br['penetration_max_cells']:.1f} cells of matrix stand above the mesh elsewhere "
         f"at the deepest press -- but that is where the plug's height has to be read against"),
    ]
    def _spec(d):
        """`spec_run.yaml` where the engine wrote one, `spec.yaml` where the rig did.

        The rigs (`test_03`, `test_04`) write their own `spec.yaml`; only runs that went through
        `run_ecm.run` leave a `spec_run.yaml`. Hard-coding the latter is why the live page opened
        `30_epi2_soft_E5`'s spec under the interface clip -- a spec belonging to a different run
        entirely, which is the one thing the site's convention exists to prevent.
        """
        for nm in ("spec_run.yaml", "spec.yaml"):
            q = os.path.join(LOG, d, nm)
            if os.path.exists(q):
                return q
        sys.exit(f"no spec beside {d} -- a clip on the page must open the spec that made it")

    runs = [(d, f"{v}.mp4", lbl, _spec(d), cap) for d, v, lbl, cap in R3]
    missing = [r for r, *_ in runs if not os.path.exists(os.path.join(LOG, r, "movie.mp4"))]
    if missing:
        sys.exit(f"no movie.mp4 for {missing} -- run them before writing the page")

    os.makedirs(GAL, exist_ok=True)
    for d, v, *_ in runs:
        src = os.path.join(LOG, d, "movie.mp4")
        split_concat(src, os.path.join(GAL, v))
        print(f"[minisite] gallery/{v} <- {d}/movie.mp4  "
              f"({os.path.getsize(os.path.join(GAL, v)) / 1e6:.1f} MB, 3D then section)")

    # ---- the Vertex + Turing second row: division AND death, from two independent RD fields ----
    # WHICH THREE, AND WHY NOT THE OTHER TWO. The sweep has five runs; `tsd_cap10` and `tsd_cap25`
    # lost the pattern -- both species end up high in every cell, the shell renders as a flat
    # magenta ball and neither growth spots nor death patches can be told apart on it (cap10's own
    # summary reports n_spots_final 0 and red_frac_final 0.0). A clip that shows nothing is not a
    # third point of a sweep, so the row is the three runs whose pattern survived.
    # (run, clip, label, which panel of the two-view movie). `sc_antiphase` is the ONE-field
    # control and its death network is drawn on the pole, so the top view is the one that shows it;
    # the two-field runs are read from the side like every other clip on the page.
    R2 = [
        ("tsd_cap02", "turing_death_cap02", "two fields, 2% under sentence", "left"),
        ("tsd_max", "turing_death_max", "two fields, 25% and earlier", "left"),
        ("sc_antiphase", "turing_death_antiphase", "one field, in antiphase", "right"),
    ]
    def _cap2(run):
        s = json.load(open(os.path.join(LOG_OKUDA, run, "diag.json")))["summary"]
        extra = {
            "tsd_cap02": "Death this rare is a speckle: single blue cells, gone by the next frame, "
                         "and the tissue grows as though nothing were removing it",
            "tsd_max": "Death opens at frame 180 instead of 600 and marked cells shrink three "
                       "times faster, and the tissue this leaves is a QUARTER the size of the "
                       "gentler run beside it. Growth and death are patterned INDEPENDENTLY here, "
                       "so this is not growth being slowed down, it is a second field deciding how "
                       "much of what the first one builds survives",
            "sc_antiphase": "The control, and the reason for the second field: with ONE field, "
                            "death has nowhere to be but where growth is not. It reads the same "
                            "chemical the growth does and fires below a threshold on it, so the "
                            "blue network is the exact complement of the red spots — a pattern "
                            "nobody chose, drawn on the flanks between them. Top view, because "
                            "that is the face the network is on",
        }[run]
        return (f"{s['cells_final']:,} cells at frame 1,800, from 2,000 seeded, "
                f"{100 * s['red_frac_final']:.0f}% of them in the red (high-activator) phase of the "
                f"field that drives growth. {extra}. The shell stays a sphere throughout (reduced "
                f"volume {s['reduced_volume_final']:.2f} at the end, where 1.0 is a perfect "
                f"sphere)")
    runs2 = [(d, f"{v}.mp4", lbl,
              os.path.join(LOG_OKUDA, d, "spec_run.yaml"), _cap2(d)) for d, v, lbl, _p in R2]
    for d, v, _lbl, panel in R2:
        src = os.path.join(LOG_OKUDA, d, "movie.mp4")
        if not os.path.exists(src):
            sys.exit(f"no movie.mp4 for {d} -- run it before writing the page")
        crop_panel(src, os.path.join(GAL, v + ".mp4"), panel=panel,
                   skip_bot=0.25 if panel == "right" else 0.14, pad=1.26)
        print(f"[minisite] gallery/{v}.mp4 <- okuda/{d}/movie.mp4  "
              f"({os.path.getsize(os.path.join(GAL, v + '.mp4')) / 1e6:.1f} MB, {panel} panel, "
              f"square, no label)")

    import shutil
    for tgt, rendered in ((QMD, False), (DOCS, True)):
        if rendered and not os.path.exists(DOCS):
            print("[minisite] no docs/index.html -- source updated only; run `quarto render`")
            continue
        _patch(tgt, build(runs), rendered=rendered)
        _patch2(tgt, build2(runs2), rendered=rendered)
    # AND THE ONE HAND-WRITTEN CARD THIS SESSION REPLACED: "grow & divide" now plays the vertex
    # model on its own (`00_spheroid`), cropped to the tissue so the printed label is out of frame,
    # 3D first and the true cross-section second.
    gd = os.path.join(LOG, "00_spheroid")
    if os.path.exists(os.path.join(gd, "movie.mp4")):
        split_concat(os.path.join(gd, "movie.mp4"), os.path.join(GAL, "tyssue_spheroid_00.mp4"),
                     skip_top=0.16)
        print(f"[minisite] gallery/tyssue_spheroid_00.mp4 <- 00_spheroid/movie.mp4 "
              f"({os.path.getsize(os.path.join(GAL, 'tyssue_spheroid_00.mp4')) / 1e6:.1f} MB)")
        replace_card("tyssue_grow_divide.mp4", "grow &amp; divide", os.path.join(gd, "spec.yaml"),
                     "the vertex model on its own: 200 cells and 396 vertices to 6,076 and ~12,000 "
                     "over 402 frames, the apical radius x3.56 and the shell still round "
                     "(aspect 1.02), through 1,384 T1 neighbour exchanges. 3D first, then the true "
                     "cross-section -- one cell deep, hollow",
                     files=((QMD, False), (DOCS, True)),
                     new_video="tyssue_spheroid_00.mp4")
        import shutil as _sh
        if os.path.isdir(DOCS_GAL):
            _sh.copy2(os.path.join(GAL, "tyssue_spheroid_00.mp4"),
                      os.path.join(DOCS_GAL, "tyssue_spheroid_00.mp4"))

    if os.path.isdir(DOCS_GAL):
        # EVERY CARD'S CLIP, not just the ones that are new this time. Copying a subset once left
        # clips out of docs/gallery while the page that referenced them was patched -- cards
        # pointing at files the site did not have.
        for d, v, *_ in runs + runs2:
            shutil.copy2(os.path.join(GAL, v), os.path.join(DOCS_GAL, v))
        print("[minisite] videos copied into docs/gallery/")
    return


def _patch(path, block, rendered=False):
    if rendered:
        block = block.replace("<h3>", '<h3 class="anchored">').replace("&#x27;", "'")
    s = open(path).read()
    anchor_old = ANCHOR_OLD if not rendered else ANCHOR_OLD.replace("<h3>", '<h3 class="anchored">')
    anchor_new = ANCHOR_NEW if not rendered else ANCHOR_NEW.replace("<h3>", '<h3 class="anchored">')
    if BEGIN in s:
        i, j = s.index(BEGIN), s.index(END) + len(END)
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        anchor = anchor_old if anchor_old in s else anchor_new
        if anchor not in s:
            sys.exit(f"anchor heading not found in {path}")
        # AFTER the anchor section, which ends at the `</div>` closing its gallery -- i.e. just before
        # the next h3. Inserting straight after the heading would put this section INSIDE the previous
        # one's prose.
        k = s.index(anchor)
        tag = "<h3" if rendered else "<h3>"
        nxt = s.index(tag, k + len(anchor))
        s = s[:nxt] + block + "\n\n" + s[nxt:]
        what = "inserted"
    s = s.replace(anchor_old, anchor_new)
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: {what}; heading renamed to 'Vertex + Turing'")


def _patch2(path, block, rendered=False):
    """The Vertex + Turing second row, inserted BETWEEN that section and the Vertex + MPM one.

    Anchored on the `BEGIN` marker of the Vertex + MPM block rather than on a heading, because it
    belongs to the section ABOVE that marker and has no heading of its own -- and because the two
    blocks then cannot be inserted in the wrong order however many times this runs.
    """
    if rendered:
        block = block.replace("&#x27;", "'")
    s = open(path).read()
    if BEGIN2 in s:
        i, j = s.index(BEGIN2), s.index(END2) + len(END2)
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        if BEGIN not in s:
            sys.exit(f"vertex-mpm marker not found in {path} -- run the first patch before this one")
        k = s.index(BEGIN)
        s = s[:k] + block + "\n\n" + s[k:]
        what = "inserted"
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: Vertex + Turing death row {what}")


if __name__ == "__main__":
    main()
