#!/usr/bin/env python
"""make_multimaterial27 -- emit 5 variants of material_3d_multimaterial27_<k> into
config/material/, a Plexus take on MPM_pytorch's `multimaterial_1_3D`: 27 cubes on a
3x3x3 grid, each given a COHERENT random launch velocity, dropped in a box.

Geometry matches the reference (utils.init_MPM_3D_shapes, n_shapes==27): cube side
`size=0.08`, grid `spacing=0.25`, `start=0.15` -> centres at {0.15,0.40,0.65} per axis.

For real per-cube variability the 27 cubes cycle THREE MATERIALS (elastic jelly /
liquid / snow) -- the colour now MEANS the material -- and each cube gets a per-cube
coherent launch velocity (`vel_init`); the 5 variants differ by `seed`, so the
launch directions (and the resulting collisions/pile) differ run to run.
Differences from the reference: actual material variety (not just density), axis-aligned
cubes (no per-cube rotation), gravity on -y (render up-axis), coarser grid.
"""
import os

SIZE = 0.08
SPACING = 0.25
START = 0.15
HALF = SIZE / 2.0
N_VARIANTS = 5
# the three cycled groups: (material, youngs, colour). The colour now denotes the material.
GROUPS = [
    ("elastic", 220, [0.86, 0.76, 0.58]),   # jelly  (tan)   -- holds shape, bounces
    ("liquid",  200, [0.30, 0.62, 1.00]),   # water  (blue)  -- splashes, spreads flat
    ("snow",     90, [0.95, 0.95, 1.00]),   # snow   (white) -- crumbles, packs
]


def _type_line(nm, frac, mat, youngs, block):
    base = f"fraction: {frac}, youngs: {youngs}, block: {block}"
    if mat == "elastic":
        return f"      {nm}: {{{base}}}"
    return (f"      {nm}: {{{base}, "
            f"layers: [{{frac: 1.0, youngs: {youngs}, material: {mat}}}]}}")


def emit(seed: int) -> str:
    name = f"material_3d_multimaterial27_{seed}"
    types, colors = [], {}
    frac = round(1.0 / 27.0, 6)
    for idx in range(27):
        depth, row, col = idx // 9, (idx % 9) // 3, idx % 3
        cx, cy, cz = (START + col * SPACING, START + row * SPACING, START + depth * SPACING)
        mat, youngs, color = GROUPS[idx % 3]
        nm = f"c{idx:02d}"
        f = frac if idx < 26 else round(1.0 - 26 * frac, 6)
        block = [round(cx - HALF, 4), round(cy - HALF, 4), round(cz - HALF, 4),
                 round(cx + HALF, 4), round(cy + HALF, 4), round(cz + HALF, 4)]
        types.append(_type_line(nm, f, mat, youngs, block))
        colors[nm] = color
    types_block = "\n".join(types)
    col_lines = "\n".join(f"    {k}: {v}" for k, v in colors.items())
    return name, f"""# {name} -- Plexus take on MPM_pytorch multimaterial_1_3D (variant seed={seed}).
# 27 cubes on a 3x3x3 grid, cycling THREE MATERIALS (elastic / liquid / snow -- the
# colour denotes the material), each launched with a per-cube random velocity, dropped
# in a box. Generated by prototype/mpm_3d/make_multimaterial27.py.
general: {{name: {name}, seed: {seed}, n_frames: 280, dt: 0.0036, boundary: wall, dim: 3, world: [1.0, 1.0, 1.0]}}
sets:
  cell:
    n: 27
    types:
{types_block}
  mpm_particle: {{parent: cell, per_parent: 1100, radius: 0.05, density: 1.0, vel_init: 3.0}}
fields:
  mpm_grid: {{frame: mpm_grid, n_grid: 96}}
operators:
- {{op: aggregate, at: cell}}
- {{op: gravity, at: cell, g: 18.0}}
- {{op: mpm_strain, at: mpm_particle}}
- {{op: p2g, at: mpm_particle, to: mpm_grid, drag: 0.0, a_max: 200}}
- {{op: mpm_grid_update, at: mpm_grid, wall_damp: 0.7}}
- {{op: g2p, at: mpm_particle, from: mpm_grid, wall_damp: 0.7, wall_contact: 0.04, vmax: 1000000000.0}}
schedule:
- aggregate
- gravity
- {{substep_dt: 0.0002, steps: [mpm_strain, p2g, mpm_grid_update, g2p]}}
plotting:
  background: black
  up_axis: 1
  camera_elev: 1.18
  camera_turns: 0.0
  camera_zoom: 0.0
  render_3d: dots
  dot_size: 1.2
  splat_res: 620
  box_frame: true
  fps: 60
  hide_sets: [cell]
  colors:
{col_lines}
"""


def main():
    outdir = os.path.join(os.path.dirname(__file__), "..", "..", "config", "material")
    outdir = os.path.normpath(outdir)
    for seed in range(1, N_VARIANTS + 1):
        name, yaml = emit(seed)
        with open(os.path.join(outdir, f"{name}.yaml"), "w") as f:
            f.write(yaml)
        print(f"wrote config/material/{name}.yaml")


if __name__ == "__main__":
    main()
