general:
  name: si_restitution
  seed: 0
  n_frames: 1800
  dt: 0.0008333333333333334
  boundary: wall
  dim: 3
  world:
  - 0.4
  - 0.4
  - 0.4
  save_data: false
  units:
    length_um: 1000000.0
    time_s: 1.0
    force_nN: 1000000000.0
sets:
  cell:
    n: 1
    types:
      e0:
        material: elastic
        youngs: 100000.0
        block:
        - 0.05
        - 0.26
        - 0.17
        - 0.11
        - 0.32
        - 0.23
        fraction: 0.25
      e1:
        material: elastic
        youngs: 1000000.0
        block:
        - 0.14
        - 0.26
        - 0.17
        - 0.2
        - 0.32
        - 0.23
        fraction: 0.25
      e2:
        material: elastic
        youngs: 10000000.0
        block:
        - 0.22999999999999998
        - 0.26
        - 0.17
        - 0.29
        - 0.32
        - 0.23
        fraction: 0.25
      e3:
        material: elastic
        youngs: 100000000.0
        block:
        - 0.32
        - 0.26
        - 0.17
        - 0.38
        - 0.32
        - 0.23
        fraction: 0.25
  mpm_particle:
    parent: cell
    per_parent: 95551
    radius: 0.5
    density: 1000.0
    particle_mass: 9.04229e-06
fields:
  mpm_grid:
    frame: mpm_grid
    n_grid: 96
operators:
- op: gravity
  at: cell
  g: 9.81
- op: mpm_strain
  at: mpm_particle
  implementation: warp
- op: mpm_scatter
  at: mpm_particle
  to: mpm_grid
  drag: 0.0
  a_max: 200.0
  implementation: warp
  polar: higham
- op: mpm_grid_update
  at: mpm_grid
  wall_damp: 1.0
- op: mpm_gather
  at: mpm_particle
  from: mpm_grid
  wall_damp: 1.0
  vmax: 1000000000.0
  implementation: warp
schedule:
- gravity
- substep_dt: 4.990020e-06
  steps:
  - mpm_strain
  - mpm_scatter
  - mpm_grid_update
  - mpm_gather
plotting:
  renderer: vtk_points
  background: black
  up_axis: 1
  camera_elev: 1.18
  camera_zoom: 0.0
  camera_turns: 0.0
  box_frame: true
  hide_sets:
  - cell
  render_3d: dots
  dot_size: 1.3
  slow_motion: 4
  colors:
    e0:
    - 0.3
    - 0.62
    - 1.0
    e1:
    - 0.35
    - 0.85
    - 0.45
    e2:
    - 1.0
    - 0.55
    - 0.2
    e3:
    - 0.95
    - 0.3
    - 0.35
