#!/usr/bin/env python
"""turing_vertex_study -- the discovery loop pointed at the Turing x vertex settings.

WHAT THIS IS FOR
------------------------------------------------------------------------------------------------
The minisite's "Turing x vertex" section shows two movies, both generated by
`prototype/Tyssue/archive_rounded.py`: a plain grow+divide vesicle and a Gray-Scott "coral" one.
Reproducing them (2026-07-30) turned up something that changes what is worth asking:

    THE TWO MOVIES ARE THE SAME SIMULATION.

Their archived diagnostics are identical -- cells_end 1778, vol_cv 0.226, hollow_frac 0.004 -- and
the reproduction confirms it. The growth law in `morphogen_growth_3d` is

        hillv = a^h / (a_sw^h + a^h)                    # in [0, 1]
        s    <- s * (1 + rate * (rho + hillv))          # per-cell cumulative volume scale
        if rho > 0:  s <- min(s, (vth_frac * v_ref / V0f_init)^(1/3))     # <-- THE CAP
        else:        s <- min(s, cap)

and the archived settings are `a_sw = 50.0, rho = 1.0`. TWO separate things then make the
chemistry decorative, and only one of them is the obvious one:

  1. `a_sw = 50` with a Gray-Scott activator around 0.4 gives `hillv ~ 4e-9`. The switch never
     fires. This is the obvious one, and it is the one you would try to fix first.
  2. `rho > 0` selects the **capped** branch, which pins EVERY cell to the same target volume
     `vth_frac * v_ref`. Under that cap a high-activator cell does not grow BIGGER, it merely
     reaches the division threshold SOONER. Shape is activator-independent BY CONSTRUCTION.

So (2) predicts that fixing (1) alone changes nothing about the shape. That is the first
hypothesis this study records and tests, and it is one I can be wrong about.

That is a fine thing for a gallery and a bad thing to reason from, because it means the site does
not yet show Turing chemistry SHAPING anything. So the question this study asks is not "does it
run" but:

    ACROSS THE (a_sw, rho, chi, rate) SETTINGS, WHEN DOES THE PATTERN STOP COLOURING AND START
    DRIVING THE SHAPE -- AND WHAT DOES IT MAKE WHEN IT DOES?

THE MEASUREMENT THAT DECIDES IT
------------------------------------------------------------------------------------------------
`corr_act_rad` -- the Pearson correlation between a cell's activator and its radius. It is the
only metric here that can tell colouring from driving:

    ~0.0   the bulges are wherever they were going to be; the chemistry is decorative
    >0.3   cells bulge WHERE the activator is; the pattern is shaping the sheet

The prior campaign (Turing_vertex, spherical SPV backend) reached corr 0.42 at best and recorded
that "localized growth does NOT produce localized extrusion" on shell mechanics with corr ~ 0.03.
Those numbers are the yardstick; this study measures the same quantity on the vertex-mesh backend,
which is the one the talk is about.

DISCIPLINE (the same as the main loop, deliberately)
------------------------------------------------------------------------------------------------
Every point carries a PREDICTION recorded before it runs, scored by `predict.score` -- so an
unparseable or unmet prediction cannot quietly become a confirmation, and the surprise rate means
something. Runs are CPU subprocesses (the box has 64 cores); a wave of 6 x 400 frames takes a few
minutes, which is what makes a real hypothesis-first loop affordable here at all.

    python turing_vertex_study.py --sweep a_sw --values 50,0.6,0.45,0.30,0.15 --frames 400
    python turing_vertex_study.py --one '{"name":"x","a_sw":0.3}' --frames 400      # worker
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
TYSSUE = os.path.join(ROOT, "prototype", "Tyssue")
OUT = os.path.join(HERE, "_turing_vertex")
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, TYSSUE)

PY = sys.executable

# The archived minisite recipe, as the DEFAULTS. Every knob below is exactly what
# archive_rounded.py hard-codes, so `--values` with the default first reproduces the movie.
BASE = dict(
    n_cells=150, radius=5.0, jitter=0.18, seed=0,
    p0=3.5, Lambda=3.0, Gamma=0.4, K_V=2.0, K_A=1.0, K_P=1.0, K_R=0.4,
    relax_iters=30, eta=0.08, cap_frac=0.12,
    # --- Gray-Scott chemistry (the "Turing" half) ---
    d_a=0.08, d_h=0.16, chi=1.3, F=0.055, kk=0.062, rate=1.0, seed_frac=0.06,
    # --- the coupling (the lever this study is about) ---
    conserve_amount=1,  # 1 = divide cell.chem by the volume growth ratio EVERY tick (op default)
    a_sw=50.0,          # activator switch threshold. 50 == the switch never fires == colouring
    hill=4.0, rho=1.0,  # rho = the uniform growth floor. 1.0 == growth is fully uniform
    grow_rate=0.03, vth_frac=1.4,
    # --- division / topology ---
    div_every=4, t1_every=4, max_div=12, max_div_frac=0.03, min_cycle=4, max_cycle=12,
)


# =============================================================================== one run
def build(k, frames, dt=1.0):
    """The coral recipe with every knob exposed. Mirrors archive_rounded.make(coral=True)."""
    import tempfile
    import yaml
    import plexus.operators                                            # noqa: F401
    import tyssue_ops3d, tyssue_rd_ops, tyssue_t1_ops3d                # noqa: F401
    import plexus.schema as S
    from tyssue_ops3d import build_sphere_mesh

    verts, es, et, ef, nF = build_sphere_mesh(k["n_cells"], k["radius"], k["jitter"], k["seed"])
    Nv = verts.shape[0]
    ops = [
        {"op": "seed_mesh_3d", "at": "vertex", "n_cells": k["n_cells"], "radius": k["radius"],
         "jitter": k["jitter"], "p0": k["p0"], "seed": k["seed"], "before_frame": 1,
         "vseed_cv": 0.15},
        {"op": "cell_geometry_3d", "at": "cell"},
        {"op": "cell_adjacency", "at": "cell"},
        {"op": "cell_rd_seed", "at": "cell", "seed": k["seed"], "before_frame": 3,
         "mode": "scatter", "seed_frac": k["seed_frac"]},
        {"op": "cell_diffuse", "at": "cell", "d_a": k["d_a"], "d_h": k["d_h"], "chi": k["chi"]},
        {"op": "cell_react", "at": "cell", "implementation": "gray_scott", "F": k["F"],
         "kk": k["kk"], "rate": k["rate"]},
        {"op": "morphogen_growth_3d", "at": "vertex", "cell_set": "cell", "rate": k["grow_rate"],
         "a_sw": k["a_sw"], "hill": k["hill"], "rho": k["rho"], "vth_frac": k["vth_frac"],
         "conserve_amount": bool(k["conserve_amount"])},
        {"op": "shape_energy_3d", "at": "vertex", "p0": k["p0"], "K_A": k["K_A"], "K_P": k["K_P"],
         "Gamma": k["Gamma"], "Lambda": k["Lambda"], "K_V": k["K_V"], "K_R": k["K_R"], "mu": 1.0,
         "dt": dt, "relax_iters": k["relax_iters"], "eta": k["eta"], "cap_frac": k["cap_frac"]},
        # D1: the engine owns the clock; these periods are engine-owned (see archive_rounded.py)
        {"op": "reconnect_t1_3d", "at": "vertex", "l_th_frac": 0.35, "every": k["t1_every"],
         "engine_clock": True, "max_flips": 30},
        {"op": "divide_3d", "at": "vertex", "factor": 2.0, "reset_noise": 0.12, "cycle_cv": 0.15,
         "p0": k["p0"], "every": k["div_every"], "engine_clock": True, "max_div": k["max_div"],
         "max_div_frac": k["max_div_frac"], "cell_set": "cell", "min_cycle": k["min_cycle"],
         "max_cycle": k["max_cycle"]},
        {"op": "topo_snapshot_3d", "at": "vertex", "every": 1},
    ]
    sched = ["seed_mesh_3d", "cell_geometry_3d", "cell_adjacency", "cell_rd_seed", "cell_diffuse",
             "cell_react", "morphogen_growth_3d", "shape_energy_3d", "reconnect_t1_3d",
             "divide_3d", "topo_snapshot_3d"]
    cfg = {"general": {"name": f"tv_{k['name']}", "seed": k["seed"], "n_frames": frames, "dt": dt,
                       "record_cap": frames + 2, "boundary": "free", "dim": 3,
                       "world": [10 * k["radius"]] * 3},
           "sets": {"vertex": {"n": int(Nv * 12)},
                    "cell": {"n": int(nF * 12),
                             "state": {"chem": {"width": 2, "integration": "first_order"},
                                       "cen": {"width": 3}, "area": {"width": 1}}}},
           "fields": {}, "operators": ops, "schedule": sched}
    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as fh:
        yaml.safe_dump(cfg, fh)
        path = fh.name
    sim = S.load(path)
    os.unlink(path)
    return sim, cfg, dict(E_srce=es, E_trgt=et, E_face=ef, nF=nF, Nv=Nv)


def metrics(mt, pos, act):
    """Geometry + pattern + THE COUPLING. Returns a flat dict of floats."""
    import numpy as np
    import torch
    from tyssue_ops3d import face_geometry_3d
    from tyssue_diag import hollow_flags

    nF = int(mt["nF"])
    area, perim, cen, vf = face_geometry_3d(
        torch.as_tensor(pos), torch.as_tensor(np.asarray(mt["E_srce"])),
        torch.as_tensor(np.asarray(mt["E_trgt"])), torch.as_tensor(np.asarray(mt["E_face"])), nF)
    cen = cen.numpy()[:nF]
    vfn = vf.numpy()
    live = np.abs(vfn) > 1e-9
    r = np.linalg.norm(cen, axis=1)
    a = np.asarray(act[:nF], dtype=float)
    ok = live & np.isfinite(r) & np.isfinite(a)
    r, a = r[ok], a[ok]
    m = {"cells_end": int(nF), "n_live": int(ok.sum())}
    if r.size < 8:
        return {**m, "degenerate": True}
    rmed = float(np.median(r))
    m.update(
        vol_cv=float(np.std(vfn[live]) / (abs(np.mean(vfn[live])) + 1e-9)),
        hollow_frac=float(hollow_flags(pos, mt)[2]["frac"]),
        r_med=rmed, r_cv=float(r.std() / (rmed + 1e-9)),
        # protrusion: how far the furthest cell sticks out beyond the body
        protr=float(r.max() / (rmed + 1e-9)),
        protr_p99=float(np.percentile(r, 99) / (rmed + 1e-9)),
        act_mean=float(a.mean()), act_max=float(a.max()),
        act_frac_high=float((a > 0.5 * a.max()).mean()) if a.max() > 1e-9 else 0.0,
        act_nan=bool(not np.isfinite(np.asarray(act[:nF], dtype=float)).all()),
    )
    # ---- THE metric: does the shape follow the pattern, or merely wear it? ----
    if a.std() > 1e-9 and r.std() > 1e-9:
        m["corr_act_rad"] = float(np.corrcoef(a, r)[0, 1])
    else:
        # a flat activator field cannot correlate with anything. Report it as absent, NOT as 0.0:
        # 0.0 would read as "measured, no coupling" when the truth is "no pattern to couple".
        m["corr_act_rad"] = None
        m["corr_undefined_why"] = ("activator is uniform" if a.std() <= 1e-9
                                   else "radius is uniform")
    return m


def run_one(k, frames, movie=False):
    """Run one setting to completion and return its metrics. Called in a subprocess."""
    import numpy as np
    from plexus.engine import run as engine_run

    t0 = time.time()
    sim, cfg, mesh0 = build(k, frames)
    d = os.path.join(OUT, k["name"])
    os.makedirs(d, exist_ok=True)
    rec = {"name": k["name"], "knobs": {x: k[x] for x in k if x != "name"}, "frames": frames}
    try:
        Hf, out = engine_run(sim, device="cpu")
        emesh = Hf.level("vertex")._mesh
        hist = emesh.get("hist")
        posf = out["sets"]["vertex"]["pos"]
        chemf = out["sets"]["cell"]["state"]["chem"]
        T = posf.shape[0]
        # THE PHANTOM GUARD. `hist[min(t, len(hist)-1)]` is the line that produced the phantom
        # "97% hollow / global buckling" result: it pairs frame t's coordinates with ANOTHER
        # frame's connectivity and fabricates inverted cells. run_one.py:check_alignment was
        # written to forbid exactly this, and this module -- which produced every hollow_frac
        # behind OR001 -- never called it. Assert, never clamp.
        from run_one import check_alignment
        check_alignment(posf, hist, name=k["name"])
        mtT = hist[T - 1]
        pT = posf[T - 1][:mtT["Nv"]].astype(np.float64)
        aT = chemf[T - 1][:mtT["nF"], 0]
        rec.update(metrics(mtT, pT, aT))
        # a mid-run reading too: a setting that blows up late still says something
        tm = T // 2
        mtm = hist[tm]
        rec["mid"] = metrics(mtm, posf[tm][:mtm["Nv"]].astype(np.float64),
                             chemf[tm][:mtm["nF"], 0])
        if movie:
            _render(d, k, hist, posf, chemf, T, mesh0)
        rec["ok"] = True
    except Exception as e:
        import traceback
        rec.update(ok=False, error=repr(e))
        traceback.print_exc()
    rec["secs"] = round(time.time() - t0, 1)
    json.dump(rec, open(os.path.join(d, "diag.json"), "w"), indent=1)
    return rec


def _render(d, k, hist, posf, chemf, T, mesh0):
    """A 4-panel strip + a movie, coloured BY ACTIVATOR (this study is about the chemistry)."""
    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.animation import FFMpegWriter
    try:
        import imageio_ffmpeg
        matplotlib.rcParams["animation.ffmpeg_path"] = imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        pass
    from run_tyssue_vesicle import _draw, _draw_cross, make_movie_axes, draw_movie_frame

    from run_one import check_alignment
    check_alignment(posf, hist, name=k["name"] + " (render)")   # the phantom guard, render path

    def frame(t):
        mt = hist[t]
        return mt, posf[t][:mt["Nv"]].astype(np.float64), chemf[t][:mt["nF"], 0]

    aT = frame(T - 1)[2]
    lo, hi = float(np.percentile(aT, 5)), float(np.percentile(aT, 99) + 1e-6)
    col = lambda mt, pt, a: np.clip((a - lo) / (hi - lo + 1e-9), 0, 1)     # noqa: E731
    Rmax = max(float(np.linalg.norm(frame(t)[1], axis=1).max())
               for t in np.linspace(0, T - 1, 20).astype(int))
    L3, L2 = Rmax * 1.06, Rmax * 2.23
    fig = plt.figure(figsize=(17.6, 9.0))
    fig.patch.set_facecolor("black")
    for i, t in enumerate([int(round(f * (T - 1))) for f in (0.0, 0.33, 0.66, 1.0)]):
        mt, pt, a = frame(t)
        c = col(mt, pt, a)
        _draw(fig.add_subplot(2, 4, i + 1, projection="3d"), pt, mt, k["p0"], azim=30, act=c, Lbox=L3)
        _draw_cross(fig.add_subplot(2, 4, 4 + i + 1), pt, mt, k["p0"], act=c, Lbox=L2)
    fig.subplots_adjust(0.006, 0.005, 0.996, 0.996, wspace=0.02, hspace=0.02)
    fig.savefig(os.path.join(d, "strip.png"), dpi=110, facecolor="black")
    plt.close(fig)
    figm = plt.figure(figsize=(5.0, 5.2))
    figm.patch.set_facecolor("black")
    axm, axin = make_movie_axes(figm)
    keep = np.arange(0, T, max(1, T // 150))
    wri = FFMpegWriter(fps=12, metadata={"title": k["name"]})
    with wri.saving(figm, os.path.join(d, "movie.mp4"), dpi=110):
        for j, t in enumerate(keep):
            mt, pt, a = frame(int(t))
            draw_movie_frame(axm, axin, pt, mt, k["p0"], (2 * j) % 360, col(mt, pt, a), L3, L2)
            wri.grab_frame()
    plt.close(figm)


# =============================================================================== the wave
def wave(points, frames, movie_for=(), jobs=8):
    """Run `points` as parallel subprocesses. Returns {name: rec}."""
    os.makedirs(OUT, exist_ok=True)
    procs, recs = {}, {}
    pending = list(points)
    env = {**os.environ, "PYTHONPATH": os.path.join(ROOT, "src"),
           "OMP_NUM_THREADS": "4", "MKL_NUM_THREADS": "4"}
    while pending or procs:
        while pending and len(procs) < jobs:
            k = pending.pop(0)
            cmd = [PY, "-u", os.path.abspath(__file__), "--one", json.dumps(k),
                   "--frames", str(frames)]
            if k["name"] in movie_for:
                cmd.append("--movie")
            log = open(os.path.join(OUT, f"{k['name']}.log"), "w")
            procs[k["name"]] = (subprocess.Popen(cmd, stdout=log, stderr=subprocess.STDOUT,
                                                 cwd=HERE, env=env), log, time.time())
            print(f"  [wave] started {k['name']}", flush=True)
        time.sleep(4)
        for nm, (p, log, t0) in list(procs.items()):
            if p.poll() is None:
                continue
            log.close()
            del procs[nm]
            dp = os.path.join(OUT, nm, "diag.json")
            if os.path.exists(dp):
                recs[nm] = json.load(open(dp))
                r = recs[nm]
                c = r.get("corr_act_rad")
                print(f"  [wave] {nm:22} {'ok' if r.get('ok') else 'FAIL'} "
                      f"cells={r.get('cells_end','?'):<6} protr={r.get('protr', float('nan')):.3f} "
                      f"corr={'n/a' if c is None else f'{c:+.3f}'}  {r.get('secs')}s", flush=True)
            else:
                # A worker that produced no diag at all is NOT a null result -- it is a missing
                # measurement, and recording it as one keeps it out of the science.
                recs[nm] = {"name": nm, "ok": False,
                            "error": f"worker exited {p.returncode} with no diag.json; "
                                     f"see _turing_vertex/{nm}.log"}
                print(f"  [wave] {nm:22} NO DIAG (exit {p.returncode})", flush=True)
    return recs


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--one", default=None, help="JSON knobs for a single worker run")
    ap.add_argument("--sweep", default=None, help="knob name to sweep")
    ap.add_argument("--values", default=None, help="comma-separated values")
    ap.add_argument("--frames", type=int, default=400)
    ap.add_argument("--jobs", type=int, default=8)
    ap.add_argument("--movie", action="store_true")
    ap.add_argument("--tag", default="")
    # Holding the OTHER knobs is not a convenience, it is the experiment.
    # Sweeping `rho` while `a_sw` sits at its default 50 gives hillv ~ 0 at every point, so the
    # sweep measures "growth rate -> 0" and not "activator-driven bulging" -- two levers changing
    # at once, with only one of them named. Caught before it ran; --fix is the fix.
    ap.add_argument("--fix", default="", help="k=v,k=v held constant across the sweep")
    a = ap.parse_args()

    if a.one:
        k = {**BASE, **json.loads(a.one)}
        r = run_one(k, a.frames, movie=a.movie)
        print(json.dumps({x: r[x] for x in r if x != "mid"}, indent=1))
        sys.exit(0 if r.get("ok") else 1)

    if not (a.sweep and a.values):
        ap.error("give --sweep and --values, or --one")
    vals = [float(v) for v in a.values.split(",")]
    tag = a.tag or a.sweep
    fixed = {}
    for kv in filter(None, a.fix.split(",")):
        key, _, val = kv.partition("=")
        key = key.strip()
        if key not in BASE:
            ap.error(f"--fix {key!r} is not a knob; known: {', '.join(sorted(BASE))}")
        fixed[key] = float(val)
    if a.sweep in fixed:
        ap.error(f"--fix {a.sweep} contradicts --sweep {a.sweep}")
    pts = [{**BASE, **fixed, "name": f"{tag}_{i}_{v:g}".replace(".", "p"), a.sweep: v}
           for i, v in enumerate(vals)]
    print(f"[study] sweeping {a.sweep} over {vals}"
          + (f", holding {fixed}" if fixed else "")
          + f", {a.frames} frames, {a.jobs} parallel")
    recs = wave(pts, a.frames, movie_for={p["name"] for p in pts}, jobs=a.jobs)
    json.dump(recs, open(os.path.join(OUT, f"wave_{tag}.json"), "w"), indent=1)
    print(f"\n[study] wrote {OUT}/wave_{tag}.json")
