#!/usr/bin/env python
"""tv_report -- score the Turing x vertex waves against the predictions and render the finding.

Scoring goes through `predict.score`, the same path the main loop uses, so an unparseable or
unmet prediction cannot quietly become a confirmation here either.
"""
from __future__ import annotations

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import predict as PR                                                       # noqa: E402

OUT = os.path.join(HERE, "_turing_vertex")

# The predictions as recorded in PREDICTIONS.md, BEFORE the runs. Keyed by run name.
POSED = {
    # wave A -- a_sw at the archived conserve_amount=1 (a dead field, as it turned out)
    "waveA_0_50":  ("control",      "protr 1.0-1.15"),
    "waveA_1_0p6": ("confirmatory", "protr 1.0-1.15"),
    "waveA_2_0p45": ("confirmatory", "protr 1.0-1.15"),
    "waveA_3_0p3": ("confirmatory", "protr 1.0-1.15"),
    "waveA_4_0p15": ("confirmatory", "protr 1.0-1.15"),
    # wave B -- rho, also against the dead field
    "waveB_0_1":   ("control",      "protr 1.0-1.15"),
    "waveB_1_0p5": ("confirmatory", "protr 1.0-1.15"),
    "waveB_2_0p2": ("confirmatory", "protr 1.0-1.15"),
    "waveB_3_0p05": ("adversarial", "protr 1.0-1.15"),
    "waveB_4_0":   ("confirmatory", "protr >= 1.3"),
    # wave C -- the decisive one edit
    "waveC_0_1":   ("control",      "protr 1.0-1.15"),
    "waveC_1_0":   ("adversarial",  "protr 1.0-1.15"),
    # wave D -- a_sw against a LIVE field
    "waveD_0_50":  ("control",      "protr 1.0-1.10"),
    "waveD_1_0p6": ("confirmatory", "protr 1.0-1.15"),
    "waveD_2_0p4": ("confirmatory", "protr 1.0-1.20"),
    "waveD_3_0p25": ("confirmatory", "protr 1.0-1.25"),
    "waveD_4_0p1": ("adversarial",  "protr >= 1.15"),
    # wave E -- rho against a LIVE field: the cap hypothesis, unconfounded
    "waveE_0_1":   ("control",      "protr 1.0-1.15"),
    "waveE_1_0p5": ("confirmatory", "protr 1.0-1.20"),
    "waveE_2_0p2": ("confirmatory", "protr 1.0-1.30"),
    "waveE_3_0p05": ("confirmatory", "protr >= 1.2"),
    "waveE_4_0":   ("confirmatory", "protr >= 1.3"),
    # wave F -- chi (domain size), at the only setting with coupling
    "waveF_0_0p3": ("confirmatory", "protr >= 1.10"),
    "waveF_1_0p65": ("confirmatory", "protr >= 1.10"),
    "waveF_2_1p3": ("control",      "protr 1.10-1.30"),
    "waveF_3_3":   ("confirmatory", "protr 1.0-1.30"),
    "waveF_4_8":   ("adversarial",  "protr 1.0-1.15"),
    # wave G -- rate (gamma)
    "waveG_0_0p1": ("confirmatory", "protr >= 1.10"),
    "waveG_1_0p3": ("confirmatory", "protr >= 1.10"),
    "waveG_2_1":   ("control",      "protr 1.10-1.30"),
    "waveG_3_3":   ("confirmatory", "protr 1.0-1.25"),
    "waveG_4_10":  ("adversarial",  "protr 1.0-1.15"),
}


def load():
    rows = []
    for f in sorted(glob.glob(os.path.join(OUT, "wave*_*", "diag.json"))):
        d = json.load(open(f))
        if not d.get("ok"):
            continue
        nm = d["name"]
        intent, pred = POSED.get(nm, (None, None))
        # `protr` is what the predictions are written against; expose it under that name.
        obs = {"protr": d.get("protr"), "corr_act_rad": d.get("corr_act_rad"),
               "hollow_frac": d.get("hollow_frac")}
        outcome, why = (PR.score(pred, obs, primary_metric="protr") if pred
                        else ("inconclusive", "no posed prediction"))
        surprise = (intent == "confirmatory" and outcome == "refuted") or \
                   (intent == "adversarial" and outcome == "confirmed")
        rows.append(dict(name=nm, wave=nm.split("_")[0], knobs=d["knobs"], intent=intent,
                         predicted=pred, outcome=outcome, why=why, surprise=surprise,
                         protr=d["protr"], corr=d.get("corr_act_rad"),
                         hollow=d["hollow_frac"], vol_cv=d["vol_cv"],
                         act_max=d["act_max"], cells=d["cells_end"]))
    return rows


def integrity(h):
    return "DESTROYED" if h > 0.5 else "straining" if h > 0.05 else "intact"


def main():
    rows = load()
    mech = [r for r in rows if r["intent"] in ("confirmatory", "adversarial")
            and r["outcome"] in ("confirmed", "refuted")]
    srate = (sum(1 for r in mech if r["surprise"]) / len(mech)) if mech else None

    L = ["# Turing x vertex — what the loop found in the settings", "",
         "_Generated by `tv_report.py` from `_turing_vertex/*/diag.json`. Every prediction was",
         "recorded in `PREDICTIONS.md` before its run and is scored here by `predict.score`._", "",
         f"**{len(rows)} runs · surprise rate "
         + (f"{srate:.2f}" if srate is not None else "n/a") + "**", "",
         "## The headline", "",
         "In the archived minisite recipe the Gray-Scott activator **decays to nothing**, and two",
         "further settings would keep the chemistry decorative even if it did not. Three layers,",
         "and they have to be peeled in order:", "",
         "| # | setting | what it does | measured |",
         "|---|---|---|---|",
         "| 1 | `conserve_amount = True` | divides `cell.chem` by the volume growth ratio every "
         "tick | activator 3.3e-2 → 4.6e-11 → **2.0e-22** at frames 60/200/400 |",
         "| 2 | `rho > 0` | selects the capped branch: every cell pinned to the same target "
         "volume | shape stays spherical (`protr` 1.03–1.06) however strong the pattern |",
         "| 3 | `a_sw = 50` | Hill switch far above the activator's ~0.43 peak | `hillv ~ 4e-9`; "
         "no coupling |", "",
         "Layer 1 dominates: while the field is extinct, layers 2 and 3 are unobservable. Waves A",
         "and B swept `a_sw` and `rho` against a dead field — **ten runs, every one "
         "`cells_end = 1778`** — and taught nothing about either lever.", "",
         "## The lever map (live field, `conserve_amount = 0`)", "",
         "| run | rho | a_sw | protr | corr(act,radius) | hollow_frac | mesh |",
         "|---|---|---|---|---|---|---|"]
    for r in [x for x in rows if x["wave"] in ("waveD", "waveE")]:
        c = r["corr"]
        L.append(f"| `{r['name']}` | {r['knobs']['rho']} | {r['knobs']['a_sw']} | "
                 f"{r['protr']:.3f} | {'n/a' if c is None else f'{c:+.3f}'} | "
                 f"{r['hollow']:.3f} | {integrity(r['hollow'])} |")
    L += ["",
          "**`rho` is the shaping lever; `a_sw` is not.** At `rho = 1.0` the pattern is vivid and",
          "the sphere is perfect at every `a_sw` from 50 down to 0.1 (`protr` 1.036–1.051,",
          "`hollow` 0.000). Lowering `rho` toward the uncapped branch is what lets the shell",
          "follow the bands.", "",
          "**But the coupling and the mesh fail together — there is no clean window:**", "",
          "```",
          "rho    1.0     0.5     0.2     0.05      0.0",
          "corr  +0.29   +0.26   +0.28   +0.63    +0.53",
          "protr  1.03    1.05    1.06    1.17     32.7",
          "hollow 0.000   0.006   0.008   0.197    0.839",
          "       <--------- intact --------><strain><-- destroyed",
          "```", "",
          "`rho = 0.05` is the best coupling seen anywhere in this project (**corr +0.63**, against",
          "0.42 for the previous campaign's best on the SPV backend) and the strip shows real",
          "clefting along the activator bands — but 20% of faces are already folded, and the",
          "cross-section tears by frame 400. At `rho = 0` the monolayer is destroyed outright",
          "(84% folded, `vol_cv` 4.9): `protr = 32.7` is a needle, not a tube.", "",
          "**This is a structural-limitation result, and it is first-class.** On this backend, "
          "activator-driven shaping is only reachable in a regime where the mesh is already "
          "failing. That is consistent with the prior campaign's independent conclusion that the "
          "gap is representational — quasi-static force-balance iteration and 3D reconnection are "
          "missing, not parameters.", "",
          "## Scoring", "",
          "| run | intent | predicted | observed protr | outcome | |",
          "|---|---|---|---|---|---|"]
    for r in rows:
        L.append(f"| `{r['name']}` | {r['intent']} | `{r['predicted']}` | {r['protr']:.3f} | "
                 f"{r['outcome']} | {'🔥 **surprise**' if r['surprise'] else ''} |")
    # ---- the claim that survives every wave ----
    intact = [r for r in rows if r["hollow"] < 0.05]
    coupled = [r for r in rows if (r["corr"] or 0) > 0.4]
    both = [r for r in rows if r["hollow"] < 0.05 and (r["corr"] or 0) > 0.4]
    L += ["", "## The structural limitation (the result)", "",
          f"Across **{len(rows)} runs spanning 5 knobs** (`conserve_amount`, `a_sw`, `rho`, "
          f"`chi`, `rate`):", "",
          f"- **{len(intact)} runs keep an intact mesh** (`hollow_frac < 0.05`). The best any of "
          f"them achieves is `protr` **{max(r['protr'] for r in intact):.3f}** and `corr` "
          f"**{max((r['corr'] or 0) for r in intact):+.3f}** — no shaping.",
          f"- **{len(coupled)} runs reach real coupling** (`corr > 0.4`). The *least* damaged of "
          f"them has `hollow_frac` **{min(r['hollow'] for r in coupled):.3f}** — a fifth of all "
          f"faces folded.",
          f"- **{len(both)} runs achieve both.**", "",
          "> On this backend, **activator-driven shaping and monolayer integrity are mutually",
          "> exclusive.** Every setting that lets the Turing pattern shape the shell also breaks",
          "> the shell. This is a structural limitation, not a tuning failure — and it is a",
          "> first-class result.", "",
          "It is also not a new opinion: the previous Turing_vertex campaign concluded "
          "independently, on a *different* backend (spherical SPV), that *the gap is "
          "REPRESENTATIONAL not parametric*. This is the same conclusion reached by measurement "
          "on the vertex-mesh backend, with the boundary located at `hollow_frac ~ 0.197`.", "",
          "Filed as **OR001** in `campaign/operator_backlog.md`: quasi-static force-balance "
          "relaxation (a residual, not a step count) plus 3D IH/HI reconnection. With an "
          "acceptance test that today's best setting fails by ~4x on both integrity metrics.", "",
          "### Caveat carried, not buried", "",
          "Waves F and G (the Okuda `chi`/`gamma` axes) were run at `rho = 0.05`, the only regime "
          "with coupling — where `hollow_frac` is already 0.197. **Every point in those two waves "
          "has `hollow_frac >= 0.197` and most exceed 0.46.** So their morphology numbers are "
          "measured on a failing mesh and must not be read as a phase diagram. The apparent best "
          "point (`chi = 3.0`: `protr` 1.430, `corr` +0.776) has **40% of faces folded**; it is "
          "not an operating point. Reproducing Okuda's (chi, gamma) diagram needs OR001 first.", "",
          "### What I got wrong", "",
          "- I predicted the **cap** was what held the shape flat, and that `rho = 0` would bulge.",
          "  Wave B refuted it (`protr` 1.034, the lowest of its sweep) — but wave B ran against",
          "  the dead field, so its refutation was uninformative. Wave E, with a live field,",
          "  **confirmed** the cap reading. A refutation obtained under a broken instrument is not",
          "  evidence, and I nearly recorded it as one.",
          "- I predicted `protr >= 1.2` at `rho = 0.05` and got 1.173 — refuted by 0.027.",
          "  Recorded as refuted rather than rounded into a pass.",
          "- **Wave G refuted my timescale story.** I claimed `corr` would FALL as `rate` rose,",
          "  because a pattern reorganising faster than the shell relaxes should decouple from it.",
          "  Observed `corr`: 0.167 / 0.062 / 0.627 / 0.675 / 0.476 at `rate` 0.1 / 0.3 / 1 / 3 /",
          "  10 — it RISES then falls, peaking near `rate ~ 3`. The low end is not decoupling at",
          "  all: `act_max` there is 0.002 and 0.000, i.e. **the pattern had not formed yet in 400",
          "  frames**. A run-length artefact I read as a mechanism until I checked `act_max`.", ""]
    p = os.path.join(OUT, "FINDINGS.md")
    open(p, "w").write("\n".join(L))
    print(f"wrote {p}")
    print(f"{len(rows)} runs, surprise rate {srate}")
    return rows


if __name__ == "__main__":
    main()
