#!/usr/bin/env python
"""exp19's deck: every content slide GENERATED from the data and result files, as tools/exp17_slides.py does exp17's.

    PYTHONPATH=src python tools/exp19_slides.py
    python presentation/fit_deck.py --dir experiments/exp19_wholistic_graphcast/presentation --deck exp19.tex

Reads experiments/exp19_wholistic_graphcast/data/{f338_inspect.json, f338_b<B>.json}, the frozen recordings'
provenance (graphs_data/redox/wholistic_f338_<channel>_recording.provenance.json), gates.yaml, and the data movie
(graphs_data/zebrafish/wholistic_f338_data/, tools/exp19_data_movie.py); writes presentation/slides/*.tex and
slides/all.tex, and copies the movie and its poster into presentation/Movies/. No number on a slide is typed here.
"""
import glob
import json
import re
import os
import shutil
import sys

import yaml

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EXP = os.path.join(ROOT, "experiments", "exp19_wholistic_graphcast")
PRES = os.path.join(EXP, "presentation")
GD = os.environ.get("GNN_OUTPUT_ROOT", "/groups/saalfeld/home/allierc/GraphData")
TITLE = "multi-level GNN on a whole fish"


def tex(s):
    """LaTeX-safe text; the unit `um` (a whole word only) becomes the micro sign."""
    return re.sub(r"\bum\b", r"\\textmu m", str(s).replace("\\", "/").replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")
            .replace("#", "\\#"))


def rows(pairs):
    return ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{7pt}}l@{}}\n"
            + "".join(f"{tex(a)} & {tex(b)} \\\\\n" for a, b in pairs) + "\\end{tabular}\\par}")


def frame(name, source, left, right):
    body = (f"% generated by tools/exp19_slides.py from {source}\n"
            f"\\begin{{frame}}[t]{{{TITLE}}}\n\\vspace*{{\\bandgap}}\n"
            "\\begin{columns}[T,onlytextwidth]\n\\begin{column}{0.58\\textwidth}\n"
            # the picture centred in the slide's height: a box as tall as the right column may be, its content
            # vertically centred ([c]), its top on the columns' top ([t]) so nothing climbs into the title band
            f"\\begin{{minipage}}[t][\\colheight][c]{{\\linewidth}}\n{left}\n\\end{{minipage}}\n\\end{{column}}\n\\begin{{column}}{{0.4\\textwidth}}\n\\vspace*{{2\\baselineskip}}\n"
            f"\\fitcol{{%\n{right}\n}}\n\\end{{column}}\n\\end{{columns}}\n\\end{{frame}}\n")
    open(os.path.join(PRES, "slides", f"{name}.tex"), "w").write(body)
    return name


def head(s):
    return f"{{\\normalsize\\textbf{{{tex(s)}}}}}\\\\[4pt]"


def slide_data():
    ins = json.load(open(os.path.join(EXP, "data", "f338_inspect.json")))
    st = json.load(open([p for p in glob.glob(os.path.join(EXP, "data", "f338_b*.json"))][0]))
    pv = {c: json.load(open(os.path.join(GD, "graphs_data", "redox", f"wholistic_f338_{c}_recording.provenance.json")))
          for c in ("gcamp", "mcherry")}
    s, v = ins["sizes"], ins["voxel_um"]
    T, Z, C, Y, X = s["T"], s["Z"], s["C"], s["Y"], s["X"]
    dur = ins["volume_times_s_first_last"][1] - ins["volume_times_s_first_last"][0]
    b = st["bin_factor_xy"]
    g = pv["gcamp"]
    _, Zl, Yl, Xl = g["shape_TZYX"]
    src = os.path.join(GD, "graphs_data", "zebrafish", "wholistic_f338_data")
    for ext in ("mp4", "png"):
        shutil.copy(os.path.join(src, "movie.mp4" if ext == "mp4" else "3d.png"),
                    os.path.join(PRES, "Movies", f"01_wholistic_data.{ext}"))
    right = "\n".join([
        head("the recording (WHOLISTIC f338)"),
        rows([("animal", "7 dpf larva, every cell GCaMP7f + mCherry-CAAX"),
              ("imaged", f"{T:,} volumes x {Z} planes x {C} channels"),
              ("", f"one volume every {ins['volume_interval_s_median']:.2f} s, {dur / 3600:.2f} h"),
              ("field", f"{Y * v['y']:.0f} x {X * v['x']:.0f} um, {Z * v['z']:.0f} um deep"),
              ("raw", f"{ins['file_GB']:.0f} GB, never stored: streamed once")]),
        "\\vspace{8pt}" + head("what is kept"),
        rows([("stored", f"{b} x {b} pixel means, {b * v['x']:.1f} um, {st['binned_shape_TZCYX'][3]} x "
                         f"{st['binned_shape_TZCYX'][4]} x {Z}, {ins['binned_uint16_GB']:.1f} GB"),
              ("law grid", f"{g['law_bin']} x {g['law_bin']} of those, {g['dx_um']:.1f} um, {Yl} x {Xl} x {Zl}"),
              ("fish", f"{g['fish_voxels']:,} of {Zl * Yl * Xl:,} voxels (GCaMP)"),
              ("split", f"train {g['n_train']}, val {g['n_val']}, test {g['n_test']} volumes")]),
        "\\vspace{8pt}" + head("the stimulus"),
        "{\\scriptsize none known: the public deposit holds no stimulus log for f338\\par}",
        "\\vspace{8pt}" + head("the movie"),
        "{\\scriptsize max over the planes; top brightness, bottom dF/F;\\\\ "
        "GCaMP stored, GCaMP law grid, mCherry (no calcium)\\par}",
    ])
    return frame("01_wholistic_data", "f338_inspect.json, f338_b4.json, the recordings' provenance",
                 "\\playmovie{Movies/01_wholistic_data}", right)


def slide_gates():
    g = yaml.safe_load(open(os.path.join(EXP, "gates.yaml")))
    lines = ["{\\tiny\\renewcommand{\\arraystretch}{0.9}\\begin{tabular}{@{}l@{\\hspace{6pt}}r@{\\hspace{6pt}}p{5.6cm}@{\\hspace{6pt}}l@{}}",
             "gate & pts & claim & full line \\\\", "\\hline"]
    for x in g["gates"]:
        full = x["full"] if not str(x["full"]).upper().startswith("TBD") else "to be set"
        lines.append(f"{tex(x['id'])} & {x['max']:g} & \\raggedright {tex(x['claim'])} & {tex(full)} \\\\")
    lines.append("\\end{tabular}\\par}")
    body = (f"% generated by tools/exp19_slides.py from gates.yaml\n\\begin{{frame}}[t]{{{TITLE}: the gates}}\n"
            f"\\vspace*{{\\bandgap}}\\vspace*{{1\\baselineskip}}\n" + "\n".join(lines) + "\n\\end{frame}\n")
    open(os.path.join(PRES, "slides", "02_gates.tex"), "w").write(body)
    return "02_gates"


def main():
    for d in ("slides", "Movies", "figs"):
        os.makedirs(os.path.join(PRES, d), exist_ok=True)
    names = [slide_data(), slide_gates()]
    open(os.path.join(PRES, "slides", "all.tex"), "w").write("".join(f"\\input{{slides/{n}}}\n" for n in names))
    print(f"-> {PRES}/slides: {', '.join(names)}")


if __name__ == "__main__":
    sys.exit(main())
