#!/usr/bin/env python
"""exp19's deck: every content slide GENERATED from the data and result files, as tools/exp17_slides.py does exp17's.

    PYTHONPATH=src python tools/exp19_slides.py
    python presentation/fit_deck.py --dir experiments/exp19_wholistic_graphcast/presentation --deck exp19.tex

Reads experiments/exp19_wholistic_graphcast/data/{f338_inspect.json, f338_b<B>.json}, the frozen recordings'
provenance (graphs_data/redox/wholistic_f338_<channel>_recording.provenance.json), gates.yaml, and the data movie
(graphs_data/zebrafish/wholistic_f338_data/, tools/exp19_data_movie.py); writes presentation/slides/*.tex and
slides/all.tex, and copies the movie and its poster into presentation/Movies/. No number on a slide is typed here.
"""
import glob
import json
import re

import numpy as np
import os
import shutil
import sys

import yaml

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EXP = os.path.join(ROOT, "experiments", "exp19_wholistic_graphcast")
PRES = os.path.join(EXP, "presentation")
GD = os.environ.get("GNN_OUTPUT_ROOT", "/groups/saalfeld/home/allierc/GraphData")
TITLE = "multi-level GNN on a whole fish"


def tex(s):
    """LaTeX-safe text; the unit `um` (a whole word only) becomes the micro sign."""
    return re.sub(r"\bum\b", r"\\textmu m", str(s).replace("\\", "/").replace("&", "\\&").replace("%", "\\%").replace("_", "\\_")
            .replace("#", "\\#"))


def rows(pairs):
    return ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{7pt}}l@{}}\n"
            + "".join(f"{tex(a)} & {tex(b)} \\\\\n" for a, b in pairs) + "\\end{tabular}\\par}")


def frame(name, source, left, right):
    body = (f"% generated by tools/exp19_slides.py from {source}\n"
            f"\\begin{{frame}}[t]{{{TITLE}}}\n\\vspace*{{\\bandgap}}\n"
            "\\begin{columns}[T,onlytextwidth]\n\\begin{column}{0.58\\textwidth}\n"
            # the picture centred in the slide's height: a box as tall as the right column may be, its content
            # vertically centred ([c]), its top on the columns' top ([t]) so nothing climbs into the title band
            f"\\begin{{minipage}}[t][\\colheight][c]{{\\linewidth}}\n{left}\n\\end{{minipage}}\n\\end{{column}}\n\\begin{{column}}{{0.4\\textwidth}}\n\\vspace*{{2\\baselineskip}}\n"
            f"\\fitcol{{%\n{right}\n}}\n\\end{{column}}\n\\end{{columns}}\n\\end{{frame}}\n")
    open(os.path.join(PRES, "slides", f"{name}.tex"), "w").write(body)
    return name


def head(s):
    return f"{{\\normalsize\\textbf{{{tex(s)}}}}}\\\\[4pt]"


def slide_data():
    ins = json.load(open(os.path.join(EXP, "data", "f338_inspect.json")))
    st = json.load(open([p for p in glob.glob(os.path.join(EXP, "data", "f338_b*.json"))][0]))
    pv = {c: json.load(open(os.path.join(GD, "graphs_data", "redox", f"wholistic_f338_{c}_recording.provenance.json")))
          for c in ("gcamp", "mcherry")}
    s, v = ins["sizes"], ins["voxel_um"]
    T, Z, C, Y, X = s["T"], s["Z"], s["C"], s["Y"], s["X"]
    dur = ins["volume_times_s_first_last"][1] - ins["volume_times_s_first_last"][0]
    b = st["bin_factor_xy"]
    g = pv["gcamp"]
    _, Zl, Yl, Xl = g["shape_TZYX"]
    src = os.path.join(GD, "graphs_data", "zebrafish", "wholistic_f338_data")
    for ext in ("mp4", "png"):
        shutil.copy(os.path.join(src, "movie.mp4" if ext == "mp4" else "3d.png"),
                    os.path.join(PRES, "Movies", f"01_wholistic_data.{ext}"))
    right = "\n".join([
        head("the recording (WHOLISTIC f338)"),
        rows([("animal", "7 dpf larva, every cell GCaMP7f + mCherry-CAAX"),
              ("imaged", f"{T:,} volumes x {Z} planes x {C} channels"),
              ("", f"one volume every {ins['volume_interval_s_median']:.2f} s, {dur / 3600:.2f} h"),
              ("field", f"{Y * v['y']:.0f} x {X * v['x']:.0f} um, {Z * v['z']:.0f} um deep"),
              ("raw", f"{ins['file_GB']:.0f} GB, never stored: streamed once")]),
        "\\vspace{8pt}" + head("what is kept"),
        rows([("stored", f"{b} x {b} pixel means, {b * v['x']:.1f} um, {st['binned_shape_TZCYX'][3]} x "
                         f"{st['binned_shape_TZCYX'][4]} x {Z}, {ins['binned_uint16_GB']:.1f} GB"),
              ("law grid", f"{g['law_bin']} x {g['law_bin']} of those, {g['dx_um']:.1f} um, {Yl} x {Xl} x {Zl}"),
              ("fish", f"{g['fish_voxels']:,} of {Zl * Yl * Xl:,} voxels (GCaMP)"),
              ("split", f"train {g['n_train']}, val {g['n_val']}, test {g['n_test']} volumes")]),
        "\\vspace{8pt}" + head("the stimulus"),
        "{\\scriptsize none known: the public deposit holds no stimulus log for f338\\par}",
        "\\vspace{8pt}" + head("the movie"),
        "{\\scriptsize max over the planes; top brightness, bottom dF/F;\\\\ "
        "GCaMP stored, GCaMP law grid, mCherry (no calcium)\\par}",
    ])
    return frame("01_wholistic_data", "f338_inspect.json, f338_b4.json, the recordings' provenance",
                 "\\playmovie{Movies/01_wholistic_data}", right)


def slide_gates():
    g = yaml.safe_load(open(os.path.join(EXP, "gates.yaml")))
    lines = ["{\\tiny\\renewcommand{\\arraystretch}{0.9}\\begin{tabular}{@{}l@{\\hspace{6pt}}r@{\\hspace{6pt}}p{5.6cm}@{\\hspace{6pt}}l@{}}",
             "gate & pts & claim & full line \\\\", "\\hline"]
    for x in g["gates"]:
        full = x["full"] if not str(x["full"]).upper().startswith("TBD") else "to be set"
        lines.append(f"{tex(x['id'])} & {x['max']:g} & \\raggedright {tex(x['claim'])} & {tex(full)} \\\\")
    lines.append("\\end{tabular}\\par}")
    body = (f"% generated by tools/exp19_slides.py from gates.yaml\n\\begin{{frame}}[t]{{{TITLE}: the gates}}\n"
            f"\\vspace*{{\\bandgap}}\\vspace*{{1\\baselineskip}}\n" + "\n".join(lines) + "\n\\end{frame}\n")
    open(os.path.join(PRES, "slides", "02_gates.tex"), "w").write(body)
    return "02_gates"


LOG = os.path.join(GD, "log", "training", "wholistic")
BATCHES = [  # (batch, the law, what it varies, protocol, arms as (label, run))
    (1, "GraphCast law, all volumes", "a learned global forcing I(t), and the calcium-blind mCherry twin", "free rollout, 1,594 steps",
     [("no forcing", "wl_gc_all"), ("+ I(t)", "wl_gc_I"), ("mCherry, no forcing", "wl_gc_all_mc"), ("mCherry + I(t)", "wl_gc_I_mc")]),
    (2, "GraphCast law, network controls and SIREN", "no network from the start; I(t) as a SIREN of time; the held-out forecast",
     "free rollout, 1,594 steps; held out", [("+ I(t), no network", "wl_gc_I_now"), ("+ SIREN", "wl_gc_S"),
                                             ("+ SIREN, no network", "wl_gc_S_now"), ("held out, no forcing", "wl_gc_base")]),
]


def _json(run, kind):
    p = os.path.join(LOG, run, "results", f"{run}_{kind}.json")
    return json.load(open(p)) if os.path.exists(p) else None


def _ax_style(ax):
    ax.set_facecolor("black")
    for sd in ("top", "right"):
        ax.spines[sd].set_visible(False)
    for sd in ("left", "bottom"):
        ax.spines[sd].set_color("0.6")
    ax.tick_params(colors="0.8", labelsize=9)


def fig_levers(b, arms, path):
    """Brain-mean R2 (exp17's headline) and R2 against the denoised recording of each arm's free rollout; black,
    labels above (exp17's batch figure). One axis on every batch slide; a value off it is written at the edge."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, axs = plt.subplots(1, 2, figsize=(9, 3.6), facecolor="black", sharey=True)
    y = np.arange(len(arms))[::-1]
    lim = (-1.5, 1.0)
    for ax, key, lab in ((axs[0], "brain_mean_r2", "a   brain-mean R$^2$ (fish-mean trace)"),
                         (axs[1], "r2_denoised", "b   R$^2$, denoised recording, every voxel")):
        _ax_style(ax)
        ax.axvline(0, color="0.6", lw=1.0)
        for yy, (lab_a, run) in zip(y, arms):
            ab = _json(run, "ablation")
            v = ab["full"][key] if ab else None
            if v is None:
                ax.text(0.01, yy, "held out: next slides", color="0.5", va="center", fontsize=8,
                        transform=ax.get_yaxis_transform())
                continue
            ax.barh(yy, float(np.clip(v, *lim)), color="#1f77b4", height=0.6)
            txt = f"{v:+.3f}" if lim[0] <= v <= lim[1] else f"{v:+.3g} (off axis)"
            ax.text(float(np.clip(v, *lim)) + (0.03 if v >= 0 else -0.03), yy, txt, color="white", va="center",
                    ha="left" if v >= 0 else "right", fontsize=8)
        ax.set_xlim(*lim)
        ax.set_title(lab, color="white", loc="left", fontsize=11)
        ax.set_xlabel("higher is better; 0 = a constant at the recording's mean", color="0.8", fontsize=8)
    axs[0].set_yticks(y)
    axs[0].set_yticklabels([f"{a}   {i + 1}" for i, (a, _) in enumerate(arms)], color="white", fontsize=9)
    fig.tight_layout()
    fig.savefig(path, dpi=160, facecolor="black")
    plt.close(fig)


def fig_controls(rows, path, title):
    """The fish-mean trace (raw F / F0, the voxels on the mask) over the free rollout: recorded, and each control."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(9, 3.4), facecolor="black")
    _ax_style(ax)
    rec = None
    for label, run, key, col in rows:
        z = os.path.join(LOG, run, "results", f"{run}_ablation.npz")
        if not os.path.exists(z):
            continue
        d = np.load(z)
        if rec is None:
            rec = d["fish_mean_recorded"]
            t = np.arange(len(rec)) * 3.81 / 3600
            ax.plot(t, rec, color="white", lw=0.8, label="recorded")
        if key in d.files:
            ax.plot(t, d[key], color=col, lw=1.0, label=label)
    ax.set_xlabel("hours after volume 4", color="0.8", fontsize=9)
    ax.set_title(title, color="white", loc="left", fontsize=11)
    ax.legend(facecolor="black", edgecolor="0.4", labelcolor="white", fontsize=8, loc="upper left")
    fig.tight_layout()
    fig.savefig(path, dpi=160, facecolor="black")
    plt.close(fig)


def fig_heldout(path):
    """wl_gc_base's skill at h 1..10 against each voxel's best recent mean (the target's baseline), beside persistence,
    the best space-time blur, and the noise ceiling (data/baselines.json)."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    hz = _json("wl_gc_base", "horizons")
    base = json.load(open(os.path.join(EXP, "data", "baselines.json")))["gcamp"]["h"]
    hs = sorted(int(h) for h in hz["h"])
    sk = [1 - hz["h"][str(h)]["mse"] / base[str(h)]["baseline_mse"] for h in hs]
    fig, ax = plt.subplots(figsize=(7.5, 3.6), facecolor="black")
    _ax_style(ax)
    ax.axhline(0, color="0.6", lw=1.0)
    ax.plot(hs, [base[str(h)]["ceiling_skill"] for h in hs], color="0.6", ls="--", lw=1.0, label="noise ceiling")
    ax.plot(hs, [base[str(h)]["persistence_skill"] for h in hs], color="#ff7f0e", lw=1.0, label="persistence")
    ax.plot(hs, [base[str(h)]["space_time_skill"] for h in hs], color="#9467bd", lw=1.0, label="space-time blur")
    ax.plot(hs, sk, color="#1f77b4", lw=2.0, marker="o", ms=4, label="GraphCast law (wl_gc_base)")
    ax.set_xlabel("volumes ahead (1 volume = 3.81 s)", color="0.8", fontsize=9)
    ax.set_title("skill = 1 - MSE / MSE of each voxel's best recent mean (held-out last 20 %)", color="white", loc="left", fontsize=10)
    ax.legend(facecolor="black", edgecolor="0.4", labelcolor="white", fontsize=8, loc="lower left")
    fig.tight_layout()
    fig.savefig(path, dpi=160, facecolor="black")
    plt.close(fig)
    return hs, sk


def full_frame(name, source, title, body):
    open(os.path.join(PRES, "slides", f"{name}.tex"), "w").write(
        f"% generated by tools/exp19_slides.py from {source}\n\\begin{{frame}}[t]{{{tex(title)}}}\n\\vspace*{{\\bandgap}}\n"
        f"{body}\n\\end{{frame}}\n")
    return name


def movie_poster(run, stem):
    import imageio.v2 as iio
    from PIL import Image
    src = os.path.join(LOG, run, "results", "movie.mp4")
    shutil.copy(src, os.path.join(PRES, "Movies", f"{stem}.mp4"))
    Image.fromarray(iio.get_reader(src).get_data(50)).save(os.path.join(PRES, "Movies", f"{stem}.png"))


def slide_batches():
    lines = ["{\\scriptsize\\renewcommand{\\arraystretch}{0.9}\\begin{tabular}{@{}r@{\\hspace{6pt}}p{3.3cm}@{\\hspace{6pt}}p{4.6cm}@{\\hspace{6pt}}p{2.6cm}@{\\hspace{6pt}}r@{}}",
             "batch & law & what it varies & scored on & landed \\\\", "\\hline"]
    for b, law, what, prot, arms in BATCHES:
        n = sum(_json(r, "test") is not None for _, r in arms)
        lines.append(f"{b} & \\raggedright {tex(law)} & \\raggedright {tex(what)} & \\raggedright {tex(prot)} & {n}/{len(arms)} \\\\")
    lines.append("\\end{tabular}\\par}")
    return full_frame("00_batches", "the run folders", f"{TITLE}: the batches at a glance",
                      "\\vspace*{1\\baselineskip}\n" + "\n".join(lines))


def slide_law():
    right = "\n".join([head("the law, one tick (exp16's)"),
        "{\\scriptsize $h_i = \\phi_v(s_i(t-3..t), F(t))$, \\quad $e_{ij} = \\phi_e(d_{ij})$\\\\[2pt]"
        "$e_{ij} \\leftarrow e_{ij} + \\psi_l(e_{ij}, h_i, h_j)$, \\quad $h_i \\leftarrow h_i + \\chi_l(h_i, \\sum_j e_{ij})$\\\\[2pt]"
        "$s_i(t+1) = s_i(t) + \\delta(h_i)$\\par}",
        "\\vspace{6pt}" + rows([("s_i", "voxel i's F / F0, its last 4 volumes"), ("F(t)", "the forcing: I(t), free, or a SIREN of t"),
                                ("neighbours", "6 on the lattice, 2.6 x 2.6 x 9.0 um"),
                                ("weights", "latent 16, 2 layers, 4,897 (I) / 4,929 (SIREN)"),
                                ("no network", "messages off: the sum over j is 0")]),
        "\\vspace{8pt}" + head("the controls (exp17's)"),
        rows([("no network", "trained from the start without messages"), ("W = 0", "the trained law, messages zeroed"),
              ("no stimulus", "the trained law, its forcing at 0")])])
    return frame("02_law", "field_ops.py diffuse[graphcast]", "\\panel{Movies/01_wholistic_data.png}", right)


def slide_levers(b, law, arms):
    fp = os.path.join(PRES, "figs", f"batch_{b}_levers.png")
    fig_levers(b, arms, fp)
    return full_frame(f"b{b}_levers", "each run's results/<run>_ablation.json", f"batch {b} ({law}): every arm",
                      f"\\begin{{center}}\\fitgfx[0.95\\linewidth]{{figs/batch_{b}_levers.png}}\\end{{center}}")


def slide_movie(b, law, k, run):
    t, ab = _json(run, "test"), _json(run, "ablation")
    movie_poster(run, f"b{b}_{run}")
    f = ab["full"]
    right = "\n".join([head(f"batch {b}, arm {k}: {run}"),
        rows([("free rollout", f"from volume {t['origin_volume']}, {t['steps']:,} steps ({t['steps'] * 3.81 / 3600:.2f} h)"),
              ("brain-mean R2", f"{f['brain_mean_r2']:+.3f} (RMSE {f['brain_mean_rmse']:.3f} F/F0)"),
              ("fish-mean SD", f"{f['fish_mean_sd_frac']:.0%} of recorded, r {f['fish_mean_corr']:+.2f}"),
              ("R2 raw", f"{t['r2']:+.3f} (spatial {t['r2_spatial']:+.3f}), ceiling {t['ceiling_r2']:.2f}"),
              ("R2 denoised", f"{t['r2_denoised']:+.3f}, ceiling {t['ceiling_r2_denoised']:.2f}"),
              ("persistence", f"R2 {t['persistence_r2']:+.3f}")]),
        "\\vspace{6pt}{\\scriptsize the movie: recorded left, learned right, 3-D oblique\\par}"])
    return frame(f"b{b}_{run}_movie", f"{run}_test.json, {run}_ablation.json",
                 f"\\playmovie{{Movies/b{b}_{run}}}", right)


def slide_curves(b, run):
    shutil.copy(os.path.join(LOG, run, "results", f"{run}_test.png"), os.path.join(PRES, "figs", f"b{b}_{run}_test.png"))
    return full_frame(f"b{b}_{run}_curves", f"{run}_test.png", f"batch {b} · {run}: the free rollout, volume by volume",
                      f"\\vspace*{{1\\baselineskip}}\\begin{{center}}\\fitgfx[0.98\\linewidth]{{figs/b{b}_{run}_test.png}}\\end{{center}}\n"
                      "{\\scriptsize left: RMSE per volume, model against persistence; middle: the fish-mean F/F0 (the trainer's "
                      "panel title is exp16's); right: one plane, recorded | model\\par}")


def slide_controls(name, title, rows_, src, table):
    fp = os.path.join(PRES, "figs", f"{name}.png")
    fig_controls(rows_, fp, "fish-mean F / F0 over the free rollout")
    t = ["{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{}}",
         "rollout & brain-mean R$^2$ & SD / recorded & r \\\\", "\\hline"]
    for lab, run, var in table:
        ab = _json(run, "ablation")
        v = ab.get(var) if ab else None
        if v:
            r2 = v["brain_mean_r2"]
            t.append(f"{tex(lab)} & {r2:+.3f} & {100 * v['fish_mean_sd_frac']:.0f} \\% & {v['fish_mean_corr']:+.2f} \\\\"
                     if abs(r2) < 1e3 else f"{tex(lab)} & diverges & -- & -- \\\\")
    t.append("\\end{tabular}\\par}")
    return full_frame(name, src, title, f"\\begin{{center}}\\fitgfx[0.82\\linewidth]{{figs/{name}.png}}\\end{{center}}\n"
                      + "\n".join(t))


def slide_heldout():
    hs, sk = fig_heldout(os.path.join(PRES, "figs", "b2_heldout.png"))
    short, long_ = np.mean(sk[:3]), np.mean(sk[4:10])
    right = "\n".join([head("batch 2, arm 4: wl_gc_base"),
        rows([("protocol", "trained on the first 80 %, the last 20 % held out"),
              ("baseline", "each voxel's best recent mean, W = 1..6"),
              ("skill short", f"{short:+.3f} (h 1-3)"), ("skill long", f"{long_:+.3f} (h 5-10)"),
              ("beats it", f"up to h {max([h for h, v in zip(hs, sk) if v > 0], default=0)} ({max([h for h, v in zip(hs, sk) if v > 0], default=0) * 3.81:.0f} s)")]),
        "\\vspace{6pt}{\\scriptsize the target needs long skill above 0: not met\\par}"])
    return frame("b2_heldout", "wl_gc_base_horizons.json, data/baselines.json", "\\panel{figs/b2_heldout.png}", right)


def main():
    for d in ("slides", "Movies", "figs"):
        os.makedirs(os.path.join(PRES, d), exist_ok=True)
    b1, b2 = BATCHES
    names = [slide_batches(), slide_data(), slide_law(),
             slide_levers(1, b1[1], b1[4]), slide_movie(1, b1[1], 2, "wl_gc_I"), slide_curves(1, "wl_gc_I"),
             slide_controls("b1_controls", "batch 1 · wl_gc_I: W = 0 and no stimulus; the mCherry twin",
                            [("full law + I(t)", "wl_gc_I", "fish_mean_full", "#1f77b4"),
                             ("no stimulus", "wl_gc_I", "fish_mean_no_stimulus", "#d62728")],
                            "wl_gc_I_ablation.npz",
                            [("GCaMP + I(t): full", "wl_gc_I", "full"), ("GCaMP + I(t): W = 0", "wl_gc_I", "W0"),
                             ("GCaMP + I(t): no stimulus", "wl_gc_I", "no_stimulus"), ("GCaMP, no forcing", "wl_gc_all", "full"),
                             ("mCherry, no forcing", "wl_gc_all_mc", "full"), ("mCherry + I(t)", "wl_gc_I_mc", "full")]),
             slide_levers(2, b2[1], b2[4]),
             slide_controls("b2_network", "batch 2: network dynamics, not the stimulus only? -- no network, trained from the start",
                            [("full law + I(t)", "wl_gc_I", "fish_mean_full", "#1f77b4"),
                             ("no network + I(t)", "wl_gc_I_now", "fish_mean_full", "#ff7f0e")],
                            "wl_gc_I / wl_gc_I_now / wl_gc_S / wl_gc_S_now _ablation.npz",
                            [("+ I(t), network", "wl_gc_I", "full"), ("+ I(t), NO network", "wl_gc_I_now", "full"),
                             ("+ SIREN, network", "wl_gc_S", "full"), ("+ SIREN, NO network", "wl_gc_S_now", "full"),
                             ("+ SIREN, no stimulus", "wl_gc_S", "no_stimulus")]),
             slide_movie(2, b2[1], 2, "wl_gc_S"), slide_heldout(), slide_gates()]
    open(os.path.join(PRES, "slides", "all.tex"), "w").write("".join(f"\\input{{slides/{n}}}\n" for n in names))
    print(f"-> {PRES}/slides: {', '.join(names)}")


if __name__ == "__main__":
    sys.exit(main())
