"""Build the exp20 deck (a learned law on the gut-brain recordings of Chen, James, Ruetten et al. 2026): figures and
slide bodies, no number typed by hand.

    PYTHONPATH=src:tools /workspace/.conda_envs/neural-graph-linux/bin/python tools/exp20_slides.py
    python presentation/fit_deck.py --dir experiments/exp20_gutbrain_graphcast/presentation --deck exp20.tex

The template is exp17's (`tools/exp17_slides.py`, `presentation/`): the picture LEFT, the specifics -- numbers,
equations, the data's provenance -- RIGHT in a `\\fitcol`. Every number on a slide is read from the file it describes
(the deposit's listing, the exported recording and its provenance, the paper's figure values in PAPER, each with its
figure and panel). Runs in the devcontainer only (INSTRUCTION.md, the cluster rule).

    01  the paper: all-optical gut-brain interrogation                  (Fig. 1 page)
    02  the deposit: conditions, fish, what each file holds              (figure)
    03  one fish: anatomy, cells, the known inputs over the session      (figure, from the exported recording)
    04  the target of the integration gate: Fig. 3d                       (figure crop + GV/GM)
    05  the law: the neuron graph on this fish (exp17's figure, drawn from the operator)
    06  the references before training: baselines, input mask
    then per batch (exp17's structure, Cedric 2026-10-03): its levers slide, the shown run's movie and curves, Cedric's
    two controls (W = 0 on the trained law; a law trained with no network) on the gut response in the free rollout;
    90  overview of every landed run
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict

import numpy as np

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EXP = os.path.join(ROOT, "experiments", "exp20_gutbrain_graphcast")
PRES = os.path.join(EXP, "presentation")
DATA = os.path.join(EXP, "data")
PAPERS = os.path.join(EXP, "papers")
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "tools"))
DECK_TITLE = "gut-brain GNN"

# THE PAPER'S NUMBERS, each with its figure and panel (read off papers/figs/*_crop.png, +-1 on the bars)
PAPER = {
    "fig3d": {"regions": ["OT", "PBN", "nodose", "LH", "medial idMO", "DVC"],
              "GMV": [55, 35, 14, 62, 33, 30], "GM": [28, 31, 12, 48, 27, 26], "GV": [33, 9, 4, 26, 10, 7],
              "midbrain": ["OT"], "hindbrain": ["PBN", "medial idMO", "DVC"]},
    "fig2g": {"foregut": 1440, "midgut": 350, "N": 4},
    "fig2i": {"AP": (30, 165), "PBN": (25, 110), "N": 3},
    "fig1e": {"AP": 6, "PBN": 6, "DVC": 6, "medial idMO": 6, "OT": 5, "LH": 4, "nodose": 4, "N": 6},
}
COND_ORDER = ["glucose", "glutamate", "Lglucose", "fish_water", "blood_glucose"]
COND_LABEL = {"glucose": "D-glucose, gut", "glutamate": "glutamate, gut", "Lglucose": "L-glucose, gut (control)",
              "fish_water": "fish water, gut (control)", "blood_glucose": "D-glucose, blood (portal)"}
SITE_COL = {1: "#9e9e9e", 2: "#ff4040", 3: "#ffa040"}


def frame(title, left, right, src, deck_title=None):
    return (f"% generated by tools/exp20_slides.py from {src} ({title})\n"
            f"\\begin{{frame}}[t]{{{deck_title or DECK_TITLE}}}\n\\vspace*{{\\bandgap}}\n"
            "\\begin{columns}[T,onlytextwidth]\n\\begin{column}{0.58\\textwidth}\n"
            f"{left}\n\\end{{column}}\n\\begin{{column}}{{0.4\\textwidth}}\n\\vspace*{{2\\baselineskip}}\n"
            f"\\fitcol{{%\n{right}}}\n\\end{{column}}\n\\end{{columns}}\n\\end{{frame}}\n")


def head(s):
    return f"{{\\normalsize\\textbf{{{s}}}}}\\\\[4pt]\n"


def rows(pairs):
    body = "".join(f"{k} & {v} \\\\\n" for k, v in pairs)
    return ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{7pt}}l@{}}\n" + body + "\\end{tabular}\\par}\n"
            "\\vspace{8pt}")


def _black(ax):
    ax.set_facecolor("black")
    for s in ax.spines.values():
        s.set_color("0.6")
    ax.tick_params(colors="0.8", labelsize=8)
    ax.xaxis.label.set_color("0.9")
    ax.yaxis.label.set_color("0.9")
    ax.title.set_color("white")


# ============================================================================== 01 the paper
def slide_paper():
    import fitz
    pdf = os.path.join(PAPERS, "Chen_2026_NatCommun_s41467-026-76242-8_gut_vascular_interoception.pdf")
    d = fitz.open(pdf)
    pg = d[2]
    W, H = pg.rect.width, pg.rect.height
    png = os.path.join(PRES, "figs", "01_paper_fig1.png")
    pg.get_pixmap(dpi=220, clip=fitz.Rect(W * 0.07, H * 0.06, W * 0.95, H * 0.62)).save(png)
    f1 = PAPER["fig1e"]
    right = (head("Chen, James, Ruetten et al. 2026") + rows([
        ("", "Nat Commun 17:9881, Ahrens \\& Fitzgerald labs"),
        ("fish", "Tg(elavl3:H2B-jGCaMP7f), 7-8 dpf, light sheet"),
        ("rate", "1-3 whole-brain volumes per second"),
        ("inputs", "caged nutrient in the gut, released by a UV beam;"),
        ("", "a drifting grating (optomotor); fictive swimming"),
        ("controls", "UV off the fish; caged L-glucose; fish water")])
        + head("what they found (Fig. 1e, 2, 3)") + rows([
            ("D-glucose", ", ".join(f"{k} {v}/{f1['N']}" for k, v in f1.items() if k != "N") + " fish"),
            ("", "L-glucose and fish water: 0 fish (Fig. 2c,d)"),
            ("site", f"foregut {PAPER['fig2g']['foregut']:,} vs midgut {PAPER['fig2g']['midgut']:,} cells (Fig. 2g)"),
            ("integration", "hindbrain: gut + motor; midbrain: gut + visual + motor")])
        + head("their model") + "{\\scriptsize one neuron at a time: lagged linear kernels on gut UV, control UV,\\\\ "
        "visual and motor regressors, smoothness-regularised (Fig. 1d)\\par}\n")
    return ("01_paper", frame("Whole-brain imaging while a nutrient is released in the gut by light",
                              "\\panel{figs/01_paper_fig1.png}", right, os.path.basename(pdf)))


# ============================================================================== 02 the deposit
def deposit():
    j = json.load(open(os.path.join(DATA, "figshare_article.json")))
    by = defaultdict(lambda: defaultdict(float))
    fish = defaultdict(set)
    for f in j["files"]:
        m = re.match(r"(Lglucose|blood_glucose|fish_water|glucose|glutamate)_fish(\d+)_", f["name"])
        if not m:
            continue
        c, k = m.group(1), int(m.group(2))
        kind = "cells" if "cells0" in f["name"] else ("volume" if "volume0" in f["name"] else "ephys")
        by[c][kind] += f["size"] / 1e9
        fish[c].add(k)
    return j, by, fish


def slide_deposit():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    j, by, fish = deposit()
    fig, ax = plt.subplots(figsize=(7, 4.2), facecolor="black")
    _black(ax)
    x = np.arange(len(COND_ORDER))
    bot = np.zeros(len(x))
    for kind, col in (("cells", "#4fc3f7"), ("ephys", "#ffb74d"), ("volume", "#9e9e9e")):
        v = np.array([by[c][kind] for c in COND_ORDER])
        ax.bar(x, v, 0.6, bottom=bot, color=col, label=kind)
        bot += v
    for i, c in enumerate(COND_ORDER):
        ax.text(i, bot[i] + 2, f"{len(fish[c])} fish", ha="center", color="white", fontsize=9)
    ax.set_xticks(x, [COND_LABEL[c].replace(", ", "\n") for c in COND_ORDER], fontsize=8)
    ax.set_ylabel("GB in the deposit")
    leg = ax.legend(frameon=False, fontsize=8, labelcolor="white")
    fig.tight_layout()
    png = os.path.join(PRES, "figs", "02_deposit.png")
    fig.savefig(png, dpi=200, facecolor="black")
    plt.close(fig)
    tot = sum(f["size"] for f in j["files"]) / 1e9
    right = (head("the deposit") + rows([
        ("", f"Figshare 10.25378/janelia.31967640"),
        ("files", f"{len(j['files'])}, {tot:.1f} GB, downloaded unbinned"),
        ("per fish", "cells0\\_clean.hdf5: Voluseg traces of every cell"),
        ("", "volume0.hdf5: the mean volume (anatomy)"),
        ("", "*.26chFlt: 26 channels at 6 kHz -- swim L/R,"),
        ("", "light-sheet trigger, UV, beam galvo, grating")])
        + head("conditions") + rows([(COND_LABEL[c], f"{len(fish[c])} fish") for c in COND_ORDER])
        + head("not in it") + rows([("", "raw volumes; parameters.pickle; atlas registration")]))
    return ("02_deposit", frame("The deposit: five conditions, one session per fish, traces of every cell",
                                "\\panel{figs/02_deposit.png}", right, "data/figshare_article.json"))


# ============================================================================== 03 one fish
def slide_fish(cond="glucose", k=1):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from plexus.paths import graphs_data_path
    name = f"gutbrain_{cond}_f{k}"
    f = graphs_data_path("zebrafish", f"{name}_recording.npz")
    if not os.path.exists(f):
        return (f"03_{name}", "")
    z = np.load(f)
    prov = json.load(open(f.replace(".npz", ".json")))
    X, P, S, tr, t = z["dff"], z["pos_um"], z["stimulus"], z["trials"], z["t_s"] / 60
    fig = plt.figure(figsize=(7.2, 6.6), facecolor="black")
    gs = fig.add_gridspec(5, 1, height_ratios=[3.2, 0.5, 0.5, 0.5, 1.4], hspace=0.35)
    ax = fig.add_subplot(gs[0])
    _black(ax)
    sub = np.random.default_rng(0).choice(len(P), min(40000, len(P)), replace=False)
    act = X[:, sub].std(0)
    ax.scatter(P[sub, 0], P[sub, 1], s=0.15, c=act, cmap="inferno", vmin=0, vmax=np.percentile(act, 99), lw=0)
    ax.set_aspect("equal")
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_title(f"{len(P):,} cells, coloured by their dF/F's standard deviation (40,000 drawn)", fontsize=8)
    names = ["UV pulses", "grating speed", "swim power (L)"]
    for i, (nm, col) in enumerate(zip(names, (None, 3, 4))):
        a = fig.add_subplot(gs[1 + i])
        _black(a)
        if col is None:
            for r in tr:
                a.axvline(t[int(r[0])], color=SITE_COL.get(int(r[2]), "w"), lw=1.5 if r[6] else 0.8,
                          ls="-" if not r[6] else "--")
            a.set_ylim(0, 1)
        else:
            a.plot(t, S[:, col], color="#4fc3f7" if col == 3 else "#81c784", lw=0.6)
        a.set_yticks([]); a.set_xticks([])
        a.set_ylabel(nm, rotation=0, ha="right", va="center", fontsize=8)
        a.set_xlim(t[0], t[-1])
    a = fig.add_subplot(gs[4])
    _black(a)
    a.plot(t, np.median(X, 1), color="white", lw=0.6)
    for r in tr:
        a.axvline(t[int(r[0])], color=SITE_COL.get(int(r[2]), "w"), lw=0.5, alpha=0.6)
    a.set_xlim(t[0], t[-1])
    a.set_xlabel("min")
    a.set_ylabel("median\ndF/F", rotation=0, ha="right", va="center", fontsize=8)
    png = os.path.join(PRES, "figs", f"03_{name}.png")
    fig.savefig(png, dpi=200, facecolor="black", bbox_inches="tight")
    plt.close(fig)
    sites = {int(s): int((tr[:, 2] == s).sum()) for s in np.unique(tr[:, 2])}
    ext = prov["extent_um"]
    right = (head(f"{cond} fish {k}") + rows([
        ("volumes", f"{prov['frames']:,}, {prov['volume_s']:.3f} s apart, {prov['frames'] * prov['volume_s'] / 60:.1f} min"),
        ("cells", f"{prov['cells_kept']:,} of {prov['cells_in_file']:,} (baseline $\\geq$ {prov['min_signal_counts']:.0f} counts above background)"),
        ("brain", f"{ext[0]:.0f} x {ext[1]:.0f} x {ext[2]:.0f} \\textmu m (voxel inferred)"),
        ("dF/F", f"clipped to [{prov['clip'][0]}, {prov['clip'][1]}]: {prov['frac_clipped'] * 100:.2f} \\% of values")])
        + head("the known inputs (forcings)") + rows([
            ("UV", f"{len(tr)} pulses of {np.median(tr[:, 1]):.0f} ms; site 1 (grey, off the fish) {sites.get(1, 0)},"),
            ("", f"site 2 (red) {sites.get(2, 0)}, site 3 (orange) {sites.get(3, 0)}: gut"),
            ("", "the law reads the pulse and the beam's galvo x, y only"),
            ("grating", f"forward, open loop, on {np.mean(S[:, 3] > 0) * 100:.0f} \\% of volumes"),
            ("swim", f"left: bouts on {np.mean(S[:, 4] > 0.1) * 100:.1f} \\% of volumes; right: "
                     f"{'live' if prov['swim_live'][1] else 'no bouts (dead channel)'}")])
        + head("held out") + rows([
            ("", f"the last full pulse of every site (dashed): {int((z['split'] == 2).sum())} volumes"),
            ("", f"window {prov['window_volumes'][0]} before + {prov['window_volumes'][1]} after a pulse (55 s)")]))
    return (f"03_{name}", frame(f"One session: {COND_LABEL[cond]}, fish {k}, and its known inputs",
                                f"\\panel{{figs/03_{name}.png}}", right, f"{name}_recording.npz"))


# ============================================================================== 04 Fig. 3d
def slide_fig3d():
    import shutil
    src = os.path.join(PAPERS, "figs", "Chen2026_fig3d_crop.png")
    shutil.copyfile(src, os.path.join(PRES, "figs", "04_fig3d.png"))
    F = PAPER["fig3d"]
    gvgm = {r: gv / gm for r, gv, gm in zip(F["regions"], F["GV"], F["GM"])}
    mid = np.mean([gvgm[r] for r in F["midbrain"]])
    hind = np.mean([gvgm[r] for r in F["hindbrain"]])
    right = (head("what Fig. 3d measures") + "{\\scriptsize the gain in a neuron's model correlation from adding\\\\ "
             "motor (GM), visual (GV) or both (GMV) regressors\\\\ to the gut-only model, \\% (N = 6 fish)\\par}\\vspace{6pt}\n"
             + head("GV / GM per region") + rows([(r, f"{F['GV'][i]} / {F['GM'][i]} = {gvgm[r]:.2f}")
                                                  for i, r in enumerate(F["regions"])])
             + head("the gate (G-region)") + rows([
                 ("midbrain", f"OT: {mid:.2f}"), ("hindbrain", f"PBN, medial idMO, DVC: {hind:.2f}"),
                 ("ratio", f"{mid / hind:.1f}: the law's input ablations, read the same way,"),
                 ("", "against the same ruler on the recording")]))
    return ("04_fig3d", frame("The integration map the law should learn: Fig. 3d",
                              "\\panel{figs/04_fig3d.png}", right, "papers/figs/Chen2026_fig3d_crop.png"))


# ============================================================================== 05 the law, 06 the baselines
GD = os.environ.get("GNN_OUTPUT_ROOT", "/groups/saalfeld/home/allierc/GraphData")
RUNS = os.path.join(GD, "log", "training", "gutbrain")
REC1 = "gutbrain_glucose_f1"


def _tex(t):
    return str(t).replace("_", "\\_").replace("%", "\\%").replace("&", "\\&").replace("#", "\\#")


def slide_law():
    """The neuron graph on this fish, drawn by exp17's figure from the operator itself (the picture IS the graph)."""
    import exp17_slides as X17
    from plexus.paths import graphs_data_path
    png = os.path.join(PRES, "figs", "05_neuron_graph.png")
    pf = f"zebrafish/{REC1}_recording.npz"
    op = X17.neuron_graph_op(positions_file=pf)
    if not os.path.exists(png) or "--figs" in sys.argv:
        X17.figure_neuron_graph(np.load(graphs_data_path(pf))["pos_um"], png, op=op)
    E = {s: int(op._E[s][0].numel()) for s in ("short", "mid", "long") if s in op._E}
    right = (head("the law: a known ODE on a graph between the cells") + rows([
        ("cells", "one state each, dF/F; its own rate, rest and 6 input weights"),
        ("edges", ", ".join(f"{k} {v:,}" for k, v in E.items()) + ": one learned W each"),
        ("", "6 nearest, 6 at 32 \\textmu m, 6 at 128 \\textmu m (exp17 7.2's law)"),
        ("step", "$dz_i = r_i(-z_i + c_i + \\sum_j W_{ij}\\tanh z_j + B_i\\cdot u)$"),
        ("", "$r_i$ rate, $c_i$ rest, $W_{ij}$ edge weight, $B_i$ input weights"),
        ("inputs", "$u$: UV pulse, beam x, y, grating speed, swim L, R"),
        ("", "read at the step's frame only; nothing recorded after the start")])
        + head("training") + rows([("", "exp17's curriculum: horizons 1..30, every step scored"),
                                    ("", "split: the held-out trial windows never trained on")]))
    return ("05_law", frame("The law: a leaky ODE per cell, coupled by a learned graph, driven by the known inputs",
                            "\\panel{figs/05_neuron_graph.png}", right, "state_diffuse[neuron_graph] on glucose fish 1"))


def slide_baselines():
    b = json.load(open(os.path.join(DATA, f"baselines_{REC1}.json")))
    m = np.load(os.path.join(GD, "graphs_data", "zebrafish", f"input_mask_{REC1}.npz"))
    png = os.path.join(EXP, "png", f"input_mask_{REC1}.png")
    import shutil
    shutil.copyfile(png, os.path.join(PRES, "figs", "06_input_mask.png"))
    g = b["gut_window_mse_resp"]
    right = (head("the references, before any training") + rows([
        ("gut-responsive", f"{b['gut_responsive']:,} cells (the paper's selection, training frames)"),
        ("noise", f"$\\sigma^2$ {b['noise_sigma2']:.3f} dF/F$^2$ over all cells (ZAPBench 0.0005)"),
        ("held-out gut", f"window MSE ($10^{{-3}}$): STA {g['sta'] * 1e3:.0f}, regression {g['reg'] * 1e3:.0f},"),
        ("", f"best recent mean {g['mean'] * 1e3:.0f}, persistence {g['pers'] * 1e3:.0f}"),
        ("control / gut", f"{b['evoked_ratio_ctrl_over_gut']:.2f}: the brain barely answers the off-fish UV"),
        ("replicable", f"{b['top1_cells']:,} cells, held-out gut evoked {b['evoked_top1_heldout_gut']:+.3f}")])
        + head("the input mask (exp17's, per input)") + rows([
            ("", f"top 10 \\% per input, training frames: union {int(m['mask'].sum()):,} cells"),
            ("uv", "site-blind trial-locked $|t|$: holds 71 \\% of the gut-responsive cells"),
            ("visual, swim", "exp17's coherence with the input")]))
    return ("06_baselines", frame("Before training: the gut-responsive cells, the references, the input mask",
                                  "\\panel{figs/06_input_mask.png}", right, f"data/baselines_{REC1}.json"))


# ============================================================================== batches, runs, controls
BATCHES = {
    "1": ("Euler integrator, glucose fish 1", ["gb_ng_base", "gb_ng_s1", "gb_ng_mask", "gb_ng_now", "gb_ng_nol1",
                                                "gb_ng_wide", "gb_ng_h50", "gb_gc_base", "gb_ng_base_lglu"], "gb_ng_nol1", "gb_ng_now"),
    "2": ("exponential integrator", ["gb_ex_base", "gb_ex_s1", "gb_ex_nol1", "gb_ex_now", "gb_ex_mask", "gb_ex_h50",
                                     "gb_ex_base_lglu", "gb_ex_f4"], "gb_ex_nol1", "gb_ex_now"),
}


def md_rows():
    """{run: (v, what changed)} from the md's results table (the one place a run's change is written)."""
    md = open(os.path.join(ROOT, "experiments", "exp20_gutbrain_graphcast.md")).read()
    out = {}
    for line in md.splitlines():
        m = re.match(r"\\| (\\S+) \\| `training/gutbrain/(\\w+)` \\|(.*)\\|\\s*$", line)
        if m:
            cells = [c.strip() for c in m.group(3).split("|")]
            out[m.group(2)] = (m.group(1), cells[-2] if len(cells) >= 2 else "")
    return out


def landed(name):
    d = os.path.join(RUNS, name, "results")
    t = os.path.join(d, f"{name}_test.json")
    if not os.path.exists(t):
        return None
    r = {"name": name, "dir": os.path.join(RUNS, name), "test": json.load(open(t))}
    for k in ("trials", "freetrial"):
        p = os.path.join(d, f"{name}_{k}.json")
        r[k] = json.load(open(p)) if os.path.exists(p) else None
    rep = os.path.join(d, "report.json")
    r["report"] = json.load(open(rep)) if os.path.exists(rep) else {}
    return r


def numbers(r):
    """The four numbers a batch slide shows for a run, from its own result files (None where not measured)."""
    from exp_measures import exp20 as M
    out = {"short": r["test"]["skill_short"], "free_r2": r["test"]["free"]["r2_denoised"], "trial": None, "free_gut": None}
    if r["trials"]:
        g = [t for t in r["trials"]["trials"] if t["kind"] == "gut"]
        out["trial"] = M.window_skill([t["mse_resp"] for t in g], [t["mse_sta_resp"] for t in g])
    if r["freetrial"]:
        out["free_gut"] = r["freetrial"]["arms"]["full"]["evoked_gut_free_over_rec"]
        out["pattern"] = r["freetrial"]["arms"]["full"]["pattern_r_gut"]
    return out


def figure_batch(b, names, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    L = {n: landed(n) for n in names}
    N = {n: numbers(r) for n, r in L.items() if r}
    keys = [("short", "skill over the mean, h 1-3"), ("trial", "held-out trial skill over the STA"),
            ("free_gut", "free rollout: gut response / recorded"), ("free_r2", "free rollout R$^2$ (denoised)")]
    fig, ax = plt.subplots(len(keys), 1, figsize=(7, 7.5), facecolor="black", sharex=True)
    x = np.arange(len(names))
    for a, (k, lab) in zip(ax, keys):
        _black(a)
        v = [N[n][k] if n in N and N[n].get(k) is not None else np.nan for n in names]
        a.bar(x, np.clip(v, -1.0, 1.5), 0.6, color=["#4fc3f7" if np.isfinite(t) and t >= 0 else "#ff7043" for t in v])
        for i, t in enumerate(v):
            if np.isfinite(t):
                a.text(i, (min(max(t, -1.0), 1.5)) + (0.04 if t >= 0 else -0.12), f"{t:+.2f}", ha="center",
                       color="white", fontsize=7)
        a.axhline(0, color="0.6", lw=0.6)
        a.set_ylabel(lab, fontsize=7, rotation=0, ha="right", va="center")
    ax[-1].set_xticks(x, [f"{i + 1}" for i in range(len(names))], fontsize=8)
    ax[-1].set_xlabel("arm (table, right)")
    fig.tight_layout()
    fig.savefig(path, dpi=180, facecolor="black")
    plt.close(fig)
    return N


def slide_batch(b):
    title, names, shown, now = BATCHES[b]
    N = figure_batch(b, names, os.path.join(PRES, "figs", f"batch_{b}_levers.png"))
    rw = md_rows()

    def f(n, k):
        v = N.get(n, {}).get(k)
        return f"{v:+.2f}" if v is not None and np.isfinite(v) else "--"
    tab = "".join(f"{i + 1} & {_tex(n)} & {f(n, 'short')} & {f(n, 'trial')} & {f(n, 'free_gut')} & {f(n, 'free_r2')} \\\\\n"
                  if n in N else f"{i + 1} & {_tex(n)} & \\multicolumn{{4}}{{l}}{{running}} \\\\\n" for i, n in enumerate(names))
    right = (head(f"batch {b}: {title}") + "{\\scriptsize\\begin{tabular}{@{}r@{\\hspace{4pt}}l@{\\hspace{5pt}}r@{\\hspace{5pt}}r"
             "@{\\hspace{5pt}}r@{\\hspace{5pt}}r@{}}\n & arm & short & trial & free gut & free R$^2$ \\\\\n\\hline\n" + tab
             + "\\end{tabular}\\par}\\vspace{6pt}\n"
             + "{\\scriptsize short: skill over the best recent mean, h 1-3, held-out windows. trial: skill over the "
               "stimulus-triggered mean, held-out gut trials, gut-responsive cells, from the pulse. free gut: the evoked response "
               "to the held-out gut pulses INSIDE the free rollout of the whole session (stimuli and the first frame only), over "
               "the recorded one. free R$^2$: the whole session.\\par}\n")
    return (f"batch_{b}_levers", frame(f"batch {b}: every arm", f"\\panel{{figs/batch_{b}_levers.png}}", right,
                                       "the runs' _test, _trials, _freetrial json", deck_title=f"batch {b} ({_tex(title)}) $\\cdot$ every arm"))


def slides_run(name, b):
    import shutil
    r = landed(name)
    if not r:
        return []
    out, rw = [], md_rows()
    v, what = rw.get(name, ("", ""))
    dt = f"batch {b} $\\cdot$ {_tex(name)}"
    N = numbers(r)
    mv = os.path.join(r["dir"], "results", "movie.mp4")
    if os.path.exists(mv):
        shutil.copyfile(mv, os.path.join(PRES, "Movies", f"{name}.mp4"))
        shutil.copyfile(mv.replace(".mp4", ".png"), os.path.join(PRES, "Movies", f"{name}.png"))
        ft = r["freetrial"]["arms"]["full"] if r["freetrial"] else None
        right = (head(_tex(name)) + "{\\scriptsize " + _tex(what) + "\\par}\\vspace{6pt}\n" + rows(
            [("short", f"{N['short']:+.3f} over the best recent mean, h 1-3"),
             ("trial", f"{N['trial']:+.3f} over the STA (held-out gut trials)" if N["trial"] is not None else "--"),
             ("free R$^2$", f"{N['free_r2']:+.3f} (whole session, denoised)")]
            + ([("free gut", f"{ft['evoked_gut_free_over_rec']:.2f} of the recorded response, pattern r {ft['pattern_r_gut']:+.2f}"),
                ("free ctrl", f"{ft['evoked_ctrl_free_over_rec_gut']:+.2f} of the recorded gut response"),
                ("", ", ".join(f"{t['kind'][0]}{t['onset']}: {t['evoked_free']:+.3f} / {t['evoked_rec']:+.3f}" for t in ft["trials"]))]
               if ft else [])))
        out.append((f"{name}_movie", frame("the free rollout of the whole session, recorded left, learned right",
                                           f"\\playmovie{{Movies/{name}}}", right, f"{name}/results/movie.mp4", deck_title=dt)))
    cp = os.path.join(r["dir"], "results", f"{name}_test.png")
    if os.path.exists(cp):
        shutil.copyfile(cp, os.path.join(PRES, "figs", f"{name}_test.png"))
        out.append((f"{name}_curves", frame("its forecasts against the baselines, step by step",
                                            f"\\panel{{figs/{name}_test.png}}", head(_tex(name)) + "{\\scriptsize the trainer's "
                                            "test figure: MSE per step ahead on the held-out windows, the law against the best "
                                            "recent mean, persistence and the stimulus lookup; the free rollout's R$^2$ per frame.\\par}\n",
                                            f"{name}_test.png", deck_title=dt)))
    return out


def slides_controls(name, now, b):
    """CEDRIC'S TWO CONTROLS (exp17 slides 26-27): the trained law with W = 0, and a law trained with no network."""
    import shutil
    r, rn = landed(name), landed(now)
    out = []
    dt = f"batch {b} $\\cdot$ network dynamics, not a function of the stimulus"
    if r and r["freetrial"] and "W0" in r["freetrial"]["arms"]:
        full, w0 = r["freetrial"]["arms"]["full"], r["freetrial"]["arms"]["W0"]
        nw = rn["freetrial"]["arms"]["full"] if rn and rn["freetrial"] else None
        ab = os.path.join(EXP, "data", f"ablation_{name}.json")
        A = json.load(open(ab)) if os.path.exists(ab) else None
        t = lambda a: ", ".join(f"{x['kind'][0]}{x['onset']} {x['evoked_free']:+.3f}" for x in a["trials"])
        rows_ = [("recorded", ", ".join(f"{x['kind'][0]}{x['onset']} {x['evoked_rec']:+.3f}" for x in full["trials"])),
                 ("full law", t(full)), ("W = 0", t(w0))] + ([("no network", t(nw))] if nw else [])
        right = (head("1. the trained law with W = 0") + "{\\scriptsize every edge weight set to 0 after training; the "
                 "inputs kept\\par}\\vspace{4pt}\n" + head("2. trained with no network from the start")
                 + "{\\scriptsize " + _tex(now) + ": the fair control (B and the cells' constants fitted without W)\\par}\\vspace{6pt}\n"
                 + head("evoked change at the held-out pulses, free rollout") + rows(rows_)
                 + rows([("gut / recorded", f"full {full['evoked_gut_free_over_rec']:.2f}, W = 0 {w0['evoked_gut_free_over_rec']:.2f}"
                          + (f", no network {nw['evoked_gut_free_over_rec']:.2f}" if nw else "")),
                         ("pattern r", f"full {full['pattern_r_gut']:+.2f}, W = 0 {w0['pattern_r_gut']:+.2f}"
                          + (f", no network {nw['pattern_r_gut']:+.2f}" if nw else ""))]
                        + ([("free R$^2$", f"full {A['full']['r2_denoised']:+.3f}, W = 0 {A['W0']['r2_denoised']:+.3f}")] if A else [])))
        mv = os.path.join(r["dir"], "results", "movie_W0.mp4")
        left = "\\panel{figs/ablation_" + name + ".png}"
        if os.path.exists(mv):
            shutil.copyfile(mv, os.path.join(PRES, "Movies", f"{name}_W0.mp4"))
            shutil.copyfile(mv.replace(".mp4", ".png"), os.path.join(PRES, "Movies", f"{name}_W0.png"))
            left = f"\\playmovie{{Movies/{name}_W0}}"
        elif A:
            shutil.copyfile(os.path.join(EXP, "data", "figs", f"ablation_{name}.png"), os.path.join(PRES, "figs", f"ablation_{name}.png"))
        else:
            left = ""
        out.append((f"{name}_controls", frame(f"{_tex(name)} with W = 0, and a law with no network: the gut response is the network's",
                                              left, right, f"{name}_freetrial.json, ablation_{name}.json", deck_title=dt)))
    if rn:
        out += [(k.replace("_movie", "_nonet_movie"), v) for k, v in slides_run(now, b) if k.endswith("_movie")]
    return out


def slide_overview():
    rw = md_rows()
    lines = []
    for b, (title, names, _, _) in BATCHES.items():
        for n in names:
            r = landed(n)
            if not r:
                continue
            N = numbers(r)
            fmt = lambda v: f"{v:+.2f}" if v is not None and np.isfinite(v) else "--"
            lines.append(f"{b}.{names.index(n) + 1} & {_tex(n)} & {fmt(N['short'])} & {fmt(N['trial'])} & {fmt(N.get('free_gut'))} & {fmt(N['free_r2'])} \\\\")
    body = ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{8pt}}l@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{}}\n"
            "arm & run & short & trial & free gut & free R$^2$ \\\\\n\\hline\n" + "\n".join(lines) + "\n\\end{tabular}\\par}")
    return ("90_overview", (f"% generated by tools/exp20_slides.py (overview)\n\\begin{{frame}}[t]{{{DECK_TITLE} $\\cdot$ every landed run}}\n"
                            f"\\vspace*{{\\bandgap}}\n{body}\n\\end{{frame}}\n"))


def main():
    for d in ("slides", "Movies", "figs"):
        os.makedirs(os.path.join(PRES, d), exist_ok=True)
    deck = []
    for fn in (slide_paper, slide_deposit, slide_fish, slide_fig3d, slide_law, slide_baselines):
        try:
            deck.append(fn())
        except Exception as e:                      # one slide's failure must not lose the deck
            print(f"[slides] {fn.__name__} FAILED: {e}")
    for b, (_, names, shown, now) in BATCHES.items():
        if not any(landed(n) for n in names):
            continue
        deck.append(slide_batch(b))
        deck += slides_run(shown, b)
        deck += slides_controls(shown, now, b)
    deck.append(slide_overview())
    out = []
    for stem, body in deck:
        if not body:
            print(f"[slides] {stem}: no data yet, skipped")
            continue
        open(os.path.join(PRES, "slides", f"{stem}.tex"), "w").write(body)
        out.append(stem)
        print(f"[slides] {stem}")
    open(os.path.join(PRES, "slides", "all.tex"), "w").write(
        "% generated by tools/exp20_slides.py\n" + "".join(f"\\input{{slides/{s}.tex}}\n" for s in out))


if __name__ == "__main__":
    main()
