"""Build the exp20 deck (a learned law on the gut-brain recordings of Chen, James, Ruetten et al. 2026): figures and
slide bodies, no number typed by hand.

    PYTHONPATH=src:tools /workspace/.conda_envs/neural-graph-linux/bin/python tools/exp20_slides.py
    python presentation/fit_deck.py --dir experiments/exp20_gutbrain_graphcast/presentation --deck exp20.tex

The template is exp17's (`tools/exp17_slides.py`, `presentation/`): the picture LEFT, the specifics -- numbers,
equations, the data's provenance -- RIGHT in a `\\fitcol`. Every number on a slide is read from the file it describes
(the deposit's listing, the exported recording and its provenance, the paper's figure values in PAPER, each with its
figure and panel). Runs in the devcontainer only (INSTRUCTION.md, the cluster rule).

    01  the paper: all-optical gut-brain interrogation                  (Fig. 1 page)
    02  the deposit: conditions, fish, what each file holds              (figure)
    03  one fish: anatomy, cells, the known inputs over the session      (figure, from the exported recording)
    04  the target of the integration gate: Fig. 3d                       (figure crop + GV/GM)
    05  the law: the neuron graph on this fish (exp17's figure, drawn from the operator)
    06  the references before training: baselines, input mask
    then per batch (exp17's structure, Cedric 2026-10-03): its levers slide, the shown run's movie and curves, Cedric's
    two controls (W = 0 on the trained law; a law trained with no network) on the gut response in the free rollout;
    90  overview of every landed run
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict

import numpy as np

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EXP = os.path.join(ROOT, "experiments", "exp20_gutbrain_graphcast")
PRES = os.path.join(EXP, "presentation")
DATA = os.path.join(EXP, "data")
PAPERS = os.path.join(EXP, "papers")
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "tools"))
DECK_TITLE = "multi-level GNN on brain-gut fish"
HIDDEN = {"04_fig3d"}            # slides written but commented out of all.tex (Cedric, 2026-10-03: slide 6, Fig. 3d)

# THE PAPER'S NUMBERS, each with its figure and panel (read off papers/figs/*_crop.png, +-1 on the bars)
PAPER = {
    "fig3d": {"regions": ["OT", "PBN", "nodose", "LH", "medial idMO", "DVC"],
              "GMV": [55, 35, 14, 62, 33, 30], "GM": [28, 31, 12, 48, 27, 26], "GV": [33, 9, 4, 26, 10, 7],
              "midbrain": ["OT"], "hindbrain": ["PBN", "medial idMO", "DVC"]},
    "fig2g": {"foregut": 1440, "midgut": 350, "N": 4},
    "fig2i": {"AP": (30, 165), "PBN": (25, 110), "N": 3},
    "fig1e": {"AP": 6, "PBN": 6, "DVC": 6, "medial idMO": 6, "OT": 5, "LH": 4, "nodose": 4, "N": 6},
}
COND_ORDER = ["glucose", "glutamate", "Lglucose", "fish_water", "blood_glucose"]
COND_LABEL = {"glucose": "D-glucose, gut", "glutamate": "glutamate, gut", "Lglucose": "L-glucose, gut (control)",
              "fish_water": "fish water, gut (control)", "blood_glucose": "D-glucose, blood (portal)"}
SITE_COL = {1: "#9e9e9e", 2: "#ff4040", 3: "#ffa040"}


def frame(title, left, right, src, deck_title=None, left_gap=False):
    """`left_gap`: the picture moved down by 2 lines, to sit centred beside the text (Cedric, 2026-10-03)."""
    gap = (f"\\vspace*{{{left_gap if not isinstance(left_gap, bool) else 2}\\baselineskip}}\n" if left_gap else "")
    return (f"% generated by tools/exp20_slides.py from {src} ({title})\n"
            f"\\begin{{frame}}[t]{{{deck_title or DECK_TITLE}}}\n\\vspace*{{\\bandgap}}\n"
            "\\begin{columns}[T,onlytextwidth]\n\\begin{column}{0.58\\textwidth}\n"
            f"{gap}{left}\n\\end{{column}}\n\\begin{{column}}{{0.4\\textwidth}}\n\\vspace*{{2\\baselineskip}}\n"
            f"\\fitcol{{%\n{right}}}\n\\end{{column}}\n\\end{{columns}}\n\\end{{frame}}\n")


def head(s):
    return f"{{\\normalsize\\textbf{{{s}}}}}\\\\[4pt]\n"


def rows(pairs):
    body = "".join(f"{k} & {v} \\\\\n" for k, v in pairs)
    return ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{7pt}}l@{}}\n" + body + "\\end{tabular}\\par}\n"
            "\\vspace{8pt}")


def _black(ax):
    ax.set_facecolor("black")
    for s in ax.spines.values():
        s.set_color("0.6")
    ax.tick_params(colors="0.8", labelsize=8)
    ax.xaxis.label.set_color("0.9")
    ax.yaxis.label.set_color("0.9")
    ax.title.set_color("white")


# ============================================================================== 01 the paper
def slide_paper():
    import fitz
    pdf = os.path.join(PAPERS, "Chen_2026_NatCommun_s41467-026-76242-8_gut_vascular_interoception.pdf")
    d = fitz.open(pdf)
    pg = d[2]
    W, H = pg.rect.width, pg.rect.height
    png = os.path.join(PRES, "figs", "01_paper_fig1.png")
    pg.get_pixmap(dpi=220, clip=fitz.Rect(W * 0.06, H * 0.055, W * 0.95, H * 0.845)).save(png)    # the whole of Fig. 1, no body text
    f1 = PAPER["fig1e"]
    right = (head("Chen, James, Ruetten et al. 2026") + rows([
        ("", "Nat Commun 17:9881, Ahrens \\& Fitzgerald labs"),
        ("fish", "Tg(elavl3:H2B-jGCaMP7f), 7-8 dpf, light sheet"),
        ("rate", "1-3 whole-brain volumes per second"),
        ("inputs", "caged nutrient in the gut, released by a UV beam;"),
        ("", "a drifting grating (optomotor); fictive swimming"),
        ("controls", "UV off the fish; caged L-glucose; fish water")])
        + head("what they found (Fig. 1e, 2, 3)") + rows([
            ("D-glucose", ", ".join(f"{k} {v}/{f1['N']}" for k, v in f1.items() if k != "N") + " fish"),
            ("", "L-glucose and fish water: 0 fish (Fig. 2c,d)"),
            ("site", f"foregut {PAPER['fig2g']['foregut']:,} vs midgut {PAPER['fig2g']['midgut']:,} cells (Fig. 2g)"),
            ("integration", "hindbrain: gut + motor; midbrain: gut + visual + motor")])
        + head("their model") + "{\\scriptsize one neuron at a time: lagged linear kernels on gut UV, control UV,\\\\ "
        "visual and motor regressors, smoothness-regularised (Fig. 1d)\\par}\n")
    return ("01_paper", frame("Whole-brain imaging while a nutrient is released in the gut by light",
                              "\\panel{figs/01_paper_fig1.png}", right, os.path.basename(pdf),
                              deck_title="{\\fontsize{7}{8.4}\\selectfont Whole-brain, all-optical interrogation of neuronal "
                                         "dynamics underlying gut and vascular interoception in zebrafish}"))


# ============================================================================== 02 the deposit
def deposit():
    j = json.load(open(os.path.join(DATA, "figshare_article.json")))
    by = defaultdict(lambda: defaultdict(float))
    fish = defaultdict(set)
    for f in j["files"]:
        m = re.match(r"(Lglucose|blood_glucose|fish_water|glucose|glutamate)_fish(\d+)_", f["name"])
        if not m:
            continue
        c, k = m.group(1), int(m.group(2))
        kind = "cells" if "cells0" in f["name"] else ("volume" if "volume0" in f["name"] else "ephys")
        by[c][kind] += f["size"] / 1e9
        fish[c].add(k)
    return j, by, fish


SITE_NAME = {1: "off the fish (control)", 2: "gut / vessel", 3: "gut", 4: "gut / vessel", 5: "gut / vessel",
             6: "vessel", 7: "vessel"}
SITE_COLS = {1: "#9e9e9e", 2: "#ff4040", 3: "#ffa040", 4: "#ffd54f", 5: "#ba68c8", 6: "#4dd0e1", 7: "#81c784"}


def slide_deposit():
    """THE EXPERIMENTAL DESIGN (Cedric, 2026-10-03: "the title should be about the experimental design; print the total
    of fish"): one row per fish of the deposit, its session on a minutes axis, each UV pulse a tick coloured by its
    galvo site label (`ch_gpos`), from data/design.json (tools/exp20_design.py)."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    D = json.load(open(os.path.join(DATA, "design.json")))
    j, by, fish = deposit()
    fig, ax = plt.subplots(figsize=(7.2, 6.0), facecolor="black")
    _black(ax)
    y, yt, yl, prev = 0, [], [], None
    for d in D:
        if prev is not None and d["condition"] != prev:
            y += 0.8
        prev = d["condition"]
        ax.plot([0, d["minutes"]], [y, y], color="0.45", lw=3, solid_capstyle="butt")
        for p_ in d["pulses"]:
            ax.plot([p_["volume"] * d["volume_s"] / 60] * 2, [y - 0.35, y + 0.35], color=SITE_COLS.get(p_["site"], "w"), lw=1.3)
        yt.append(y)
        yl.append(f"{COND_LABEL[d['condition']].split(',')[0]} {d['fish']}")
        y += 1
    ax.set_yticks(yt, yl, fontsize=7)
    ax.invert_yaxis()
    ax.set_xlabel("minutes of the session")
    used = sorted({p_["site"] for d in D for p_ in d["pulses"] if p_["site"] in SITE_COLS})
    for k in used:
        ax.plot([], [], color=SITE_COLS[k], lw=4, label=f"site {k}: {SITE_NAME[k]}")
    ax.legend(frameon=False, fontsize=9, labelcolor="white", loc="lower right", handlelength=1.5)
    fig.tight_layout()
    fig.savefig(os.path.join(PRES, "figs", "02_design.png"), dpi=200, facecolor="black")
    plt.close(fig)
    n_f = len(D)
    per = {c: [d for d in D if d["condition"] == c] for c in COND_ORDER}
    rate = lambda ds: ", ".join(sorted({f"{d['volume_s']:.2f} s" for d in ds}))
    right = (head(f"{n_f} fish, one session each, all on disk") + rows(
        [(COND_LABEL[c], f"{len(per[c])} fish, {np.mean([d['minutes'] for d in per[c]]):.0f} min, "
                         f"{np.mean([len(d['pulses']) for d in per[c]]):.0f} pulses, volume {rate(per[c])}") for c in COND_ORDER])
        + head("a session") + rows([
            ("UV pulses", "200 ms, blocked by site: grey off the fish (control),"),
            ("", "coloured on the gut, or on the portal vessel in the"),
            ("", "blood-glucose fish (sites are the galvo's label only)"),
            ("grating", "forward or still, ~60-s blocks, open loop"),
            ("swim", "fictive, two motor-nerve electrodes")])
        + head("per fish, three files") + rows([
            ("cells", f"the traces of every segmented cell ({np.mean([d['cells'] for d in D]) / 1e3:.0f}k on average)"),
            ("ephys", "26 channels at 6 kHz: swim, triggers, UV, galvo, grating"),
            ("volume", "the mean anatomy (for pictures only)")]))
    return ("02_deposit", frame(f"The experimental design: {n_f} fish, five conditions, UV pulses on and off the gut",
                                "\\panel{figs/02_design.png}", right, "data/design.json", left_gap=0.6,
                                deck_title=f"The experimental design: {n_f} fish, five conditions, UV pulses on and off the gut"))


def slide_anatomy():
    """WHERE THE UV WAS AIMED (Cedric, 2026-10-03: "pinpoint the sites on a fish anatomy"): the WHOLISTIC whole-body
    model (tools/exp20_body_export.py, tools/exp20_body_render.py) with the paper's target regions; the deposit's site
    labels per condition with their galvo x range, from data/design.json. The label -> region mapping is NOT recorded:
    the slide says so."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D
    A = os.path.join(DATA, "anatomy")
    if not os.path.exists(os.path.join(A, "body_lateral.png")):
        return ("02b_anatomy", "")
    fig, ax = plt.subplots(2, 1, figsize=(8, 5.2), facecolor="black")
    for a_, v in zip(ax, ("lateral", "dorsal")):
        im = plt.imread(os.path.join(A, f"body_{v}.png"))
        r0, r1 = (0.12, 0.78) if v == "lateral" else (0.28, 0.72)      # full width in both: head and tail align
        a_.imshow(im[int(r0 * im.shape[0]):int(r1 * im.shape[0])])
        # SCALE BAR (Cedric, 2026-10-03): the model has no units; its skin is 19.7 units long, taken as a 3.8-mm 7-dpf
        # larva (1 unit ~ 0.19 mm; the retina then ~300 um across). The render's parallel scale (tools/exp20_body_render.py)
        # gives 23 units across the 2400-px width, so 500 um = (0.5 / 0.193) units = that many px
        px = 0.5 / (3.8 / 19.7) * 2400 / 23.0
        h_ = (r1 - r0) * im.shape[0]
        a_.plot([60, 60 + px], [h_ - 40, h_ - 40], color="white", lw=2.5)
        a_.text(60 + px / 2, h_ - 55, "\u2248 500 \u00b5m", color="white", fontsize=8, ha="center", va="bottom")
        a_.axis("off")
        a_.set_title(f"{v} view, head left", color="0.8", fontsize=9)
    marks = [("off the fish (control)", "#bdbdbd"), ("foregut", "#ff4040"), ("midgut", "#ffd54f"),
             ("hepatic portal system", "#66bb6a")]
    org = [("brain + spinal cord", "#4fc3f7"), ("gut", "#ff8a65"), ("liver", "#8d4a3a"), ("heart", "#e53935"),
           ("kidney", "#7e57c2"), ("swim bladder", "#e0e0e0")]
    h = [Line2D([], [], marker="o", ls="", color=c, markersize=9, label=l) for l, c in marks] + \
        [Line2D([], [], marker="s", ls="", color=c, markersize=7, label=l) for l, c in org]
    fig.legend(handles=h, loc="lower center", ncol=5, frameon=False, fontsize=8, labelcolor="white")
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    fig.savefig(os.path.join(PRES, "figs", "02b_anatomy.png"), dpi=200, facecolor="black")
    plt.close(fig)
    D = json.load(open(os.path.join(DATA, "design.json")))
    from collections import defaultdict
    gx = defaultdict(list)
    for d in D:
        for p_ in d["pulses"]:
            if "galvo_x" in p_:
                gx[(d["condition"], p_["site"])].append(p_["galvo_x"])
    rw = []
    for c in COND_ORDER:
        ss = sorted({k[1] for k in gx if k[0] == c and k[1] > 0})
        rw.append((COND_LABEL[c], "sites " + ", ".join(str(k) for k in ss)))
    right = (head("the paper's targets (markers)") + rows([
        ("control", "UV outside the fish, on the tail or the swim bladder"),
        ("gut", "foregut, midgut (Fig. 1b, 2e): foregut ~4x more cells"),
        ("blood", "hepatic portal system near the liver (Fig. 5a)")])
        + head("the deposit's site labels") + rows(rw)
        + head("what we can and cannot say") + rows([
            ("", "site 1 = off the fish in every session (control block)"),
            ("", "the other labels are not calibrated to the body: one"),
            ("", "site moves 0.6 V fish to fish; blood sites 2, 4, 5, 6 share"),
            ("", "one voltage. Marker positions are the paper's regions"),
            ("", "on the WHOLISTIC body model, not measured beam spots")]))
    return ("02b_anatomy", frame("Where the UV was aimed: the paper's target regions on the larval body",
                                 "\\panel{figs/02b_anatomy.png}", right, "data/anatomy, data/design.json", left_gap=1,
                                 deck_title="Where the UV was aimed: the paper's target regions on a larval zebrafish"))


# ============================================================================== 03 one fish
def slide_fish(cond="glucose", k=1):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from plexus.paths import graphs_data_path
    name = f"gutbrain_{cond}_f{k}"
    f = graphs_data_path("zebrafish", f"{name}_recording.npz")
    if not os.path.exists(f):
        return (f"03_{name}", "")
    z = np.load(f)
    prov = json.load(open(f.replace(".npz", ".json")))
    from plexus.tasks import trace_recording as TR
    X, P, S, tr, t = z["dff"], TR.load(name)["pos_view"], z["stimulus"], z["trials"], z["t_s"] / 60   # head left (exp17)
    fig = plt.figure(figsize=(7.2, 6.6), facecolor="black")
    gs = fig.add_gridspec(5, 1, height_ratios=[4.6, 0.5, 0.5, 0.5, 1.4], hspace=0.35)
    ax = fig.add_subplot(gs[0])
    _black(ax)
    # WHERE THE GUT SIGNAL REACHES (Cedric, 2026-10-03): the gut-responsive cells (tools/gutbrain_baselines.py, the
    # paper's selection on the training frames) coloured by their mean evoked change after the training gut pulses,
    # over every cell in grey; top view of the brain, no frame, a 100-um scale bar
    cz = np.load(os.path.join(DATA, f"baselines_{name}_cells.npz"))
    resp, evg = cz["responsive"], cz["evoked_gut"]
    sub = np.random.default_rng(0).choice(len(P), min(60000, len(P)), replace=False)
    ax.scatter(P[sub, 0], P[sub, 1], s=0.6, c="0.35", lw=0)
    o = np.argsort(evg[resp])
    ax.scatter(P[resp, 0][o], P[resp, 1][o], s=3.0, c=evg[resp][o], cmap="autumn", vmin=0,
               vmax=np.percentile(evg[resp], 98), lw=0)
    ax.set_aspect("equal")
    ax.axis("off")
    x0, y0 = P[:, 0].min(), P[:, 1].min() - 0.06 * np.ptp(P[:, 1])
    ax.plot([x0, x0 + 100], [y0, y0], color="white", lw=2.5)
    ax.text(x0 + 50, y0 - 0.02 * np.ptp(P[:, 1]), "100 \u00b5m", color="white", fontsize=8, ha="center", va="top")
    ax.set_title(f"the {int(resp.sum()):,} gut-responsive cells, coloured by their evoked dF/F after a gut pulse\n"
                 f"(yellow = strongest), on all {len(P):,} cells (grey); brain, top view, head left", fontsize=8)
    names = ["UV pulses", "grating speed", "swim power (L)"]
    for i, (nm, col) in enumerate(zip(names, (None, 3, 4))):
        a = fig.add_subplot(gs[1 + i])
        _black(a)
        if col is None:
            for r in tr:
                a.axvline(t[int(r[0])], color=SITE_COL.get(int(r[2]), "w"), lw=1.5 if r[6] else 0.8,
                          ls="-" if not r[6] else "--")
            a.set_ylim(0, 1)
        else:
            a.plot(t, S[:, col], color="#4fc3f7" if col == 3 else "#81c784", lw=0.6)
        a.set_yticks([]); a.set_xticks([])
        a.set_ylabel(nm, rotation=0, ha="right", va="center", fontsize=8)
        a.set_xlim(t[0], t[-1])
    a = fig.add_subplot(gs[4])
    _black(a)
    a.plot(t, np.median(X, 1), color="white", lw=0.6)
    for r in tr:
        a.axvline(t[int(r[0])], color=SITE_COL.get(int(r[2]), "w"), lw=0.5, alpha=0.6)
    a.set_xlim(t[0], t[-1])
    a.set_xlabel("min")
    a.set_ylabel("median\ndF/F", rotation=0, ha="right", va="center", fontsize=8)
    png = os.path.join(PRES, "figs", f"03_{name}.png")
    fig.savefig(png, dpi=200, facecolor="black", bbox_inches="tight")
    plt.close(fig)
    sites = {int(s): int((tr[:, 2] == s).sum()) for s in np.unique(tr[:, 2])}
    ext = prov["extent_um"]
    right = (head(f"{cond} fish {k}") + rows([
        ("volumes", f"{prov['frames']:,}, {prov['volume_s']:.3f} s apart, {prov['frames'] * prov['volume_s'] / 60:.1f} min"),
        ("cells", f"{prov['cells_kept']:,} of {prov['cells_in_file']:,} (baseline $\\geq$ {prov['min_signal_counts']:.0f} counts above background)"),
        ("brain", f"{ext[0]:.0f} x {ext[1]:.0f} x {ext[2]:.0f} \\textmu m (voxel inferred)"),
        ("dF/F", f"clipped to [{prov['clip'][0]}, {prov['clip'][1]}]: {prov['frac_clipped'] * 100:.2f} \\% of values")])
        + head("the known inputs (forcings)") + rows([
            ("UV", f"{len(tr)} pulses of {np.median(tr[:, 1]):.0f} ms; site 1 (grey, off the fish) {sites.get(1, 0)},"),
            ("", f"site 2 (red) {sites.get(2, 0)}, site 3 (orange) {sites.get(3, 0)}: gut"),
            ("", "the law reads the pulse and the beam's galvo x, y only"),
            ("grating", f"forward, open loop, on {np.mean(S[:, 3] > 0) * 100:.0f} \\% of volumes"),
            ("swim", f"left: bouts on {np.mean(S[:, 4] > 0.1) * 100:.1f} \\% of volumes; right: "
                     f"{'live' if prov['swim_live'][1] else 'no bouts (dead channel)'}")])
        + head("held out") + rows([
            ("", f"the last full pulse of every site (dashed): {int((z['split'] == 2).sum())} volumes"),
            ("", f"window {prov['window_volumes'][0]} before + {prov['window_volumes'][1]} after a pulse (55 s)")]))
    return (f"03_{name}", frame(f"One session: {COND_LABEL[cond]}, fish {k}, and its known inputs",
                                f"\\panel{{figs/03_{name}.png}}", right, f"{name}_recording.npz"))


# ============================================================================== 04 Fig. 3d
def slide_fig3d():
    import shutil
    import fitz                                            # Fig. 3d whole: its bars AND the region names under them
    d = fitz.open(os.path.join(PAPERS, "Chen_2026_NatCommun_s41467-026-76242-8_gut_vascular_interoception.pdf"))
    pg = d[5]
    W, H = pg.rect.width, pg.rect.height
    pg.get_pixmap(dpi=450, clip=fitz.Rect(W * 0.665, H * 0.262, W * 0.955, H * 0.418)).save(
        os.path.join(PRES, "figs", "04_fig3d.png"))
    F = PAPER["fig3d"]
    gvgm = {r: gv / gm for r, gv, gm in zip(F["regions"], F["GV"], F["GM"])}
    mid = np.mean([gvgm[r] for r in F["midbrain"]])
    hind = np.mean([gvgm[r] for r in F["hindbrain"]])
    right = (head("what Fig. 3d measures") + "{\\scriptsize the gain in a neuron's model correlation from adding\\\\ "
             "motor (GM), visual (GV) or both (GMV) regressors\\\\ to the gut-only model, \\% (N = 6 fish)\\par}\\vspace{6pt}\n"
             + head("GV / GM per region") + rows([(r, f"{F['GV'][i]} / {F['GM'][i]} = {gvgm[r]:.2f}")
                                                  for i, r in enumerate(F["regions"])])
             + head("the gate (G-region)") + rows([
                 ("midbrain", f"OT: {mid:.2f}"), ("hindbrain", f"PBN, medial idMO, DVC: {hind:.2f}"),
                 ("ratio", f"{mid / hind:.1f}: the law's input ablations, read the same way,"),
                 ("", "against the same ruler on the recording")]))
    return ("04_fig3d", frame("The integration map the law should learn: Fig. 3d",
                              "\\panel{figs/04_fig3d.png}", right, "the paper's Fig. 3d", left_gap=1,
                              deck_title="The target of G-region (Fig. 3d): gut + visual in the midbrain, gut + motor "
                                         "in the hindbrain"))


# ============================================================================== 05 the law, 06 the baselines
GD = os.environ.get("GNN_OUTPUT_ROOT", "/groups/saalfeld/home/allierc/GraphData")
RUNS = os.path.join(GD, "log", "training", "gutbrain")
REC1 = "gutbrain_glucose_f1"


def _tex(t):
    return str(t).replace("_", "\\_").replace("%", "\\%").replace("&", "\\&").replace("#", "\\#")


def figure_graph(op, P, path, n_show=80, seed=0, box_um=300.0):
    """The cell graph the law trains on (the operator's own edges), TOP VIEW, HEAD LEFT (pos_view): a, the whole brain,
    every cell a faint dot and the middle and long edges INTO `n_show` random cells; b, a box around one cell, the
    short edges between the cells inside it and that cell's own 18 edges drawn thick."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.collections import LineCollection
    C = {"short": "#9ecae1", "mid": "#fd8d3c", "long": "#ff4040"}
    E = {k: (op._E[k][0].cpu().numpy(), op._E[k][1].cpu().numpy()) for k in ("short", "mid", "long") if k in op._E}
    rng = np.random.default_rng(seed)
    fig, ax = plt.subplots(1, 2, figsize=(10, 4.2), facecolor="black", gridspec_kw={"width_ratios": [2.1, 1]})
    a, b = ax
    for x_ in ax:
        x_.set_facecolor("black"); x_.set_aspect("equal"); x_.axis("off")
    sub = rng.choice(len(P), min(50000, len(P)), replace=False)
    a.scatter(P[sub, 0], P[sub, 1], s=0.2, c="0.35", lw=0)
    tgt = rng.choice(len(P), n_show, replace=False)
    for k in ("mid", "long"):
        s_, r_ = E[k]
        m = np.isin(r_, tgt)
        a.add_collection(LineCollection(np.stack([P[s_[m], :2], P[r_[m], :2]], 1), colors=C[k], lw=0.5, alpha=0.8))
    a.scatter(P[tgt, 0], P[tgt, 1], s=6, c="white", lw=0, zorder=3)
    x0, y0 = P[:, 0].min(), P[:, 1].min() - 25
    a.plot([x0, x0 + 100], [y0, y0], color="white", lw=2.5)
    a.text(x0 + 50, y0 - 8, "100 \u00b5m", color="white", fontsize=8, ha="center", va="top")
    fig.text(0.02, 0.95, f"a  the whole brain, head left: middle and long edges into {n_show} cells", color="0.9",
             fontsize=12, va="top")
    c0 = int(np.argmin(np.linalg.norm(P - np.median(P, 0), axis=1)))     # a cell at the brain's centre: a full box
    inb = np.where(np.all(np.abs(P[:, :2] - P[c0, :2]) < box_um / 2, 1) & (np.abs(P[:, 2] - P[c0, 2]) < 8.0))[0]
    sset = set(inb.tolist())
    s_, r_ = E["short"]
    m = np.isin(r_, inb) & np.isin(s_, inb)
    b.scatter(P[inb, 0], P[inb, 1], s=8, c="0.6", lw=0)
    b.add_collection(LineCollection(np.stack([P[s_[m], :2], P[r_[m], :2]], 1), colors=C["short"], lw=0.4, alpha=0.5))
    for k in ("short", "mid", "long"):
        s_, r_ = E[k]
        m = r_ == c0
        b.add_collection(LineCollection(np.stack([P[s_[m], :2], P[r_[m], :2]], 1), colors=C[k], lw=1.8))
    b.scatter([P[c0, 0]], [P[c0, 1]], s=40, c="white", zorder=4)
    b.set_xlim(P[c0, 0] - box_um / 2, P[c0, 0] + box_um / 2)
    b.set_ylim(P[c0, 1] - box_um / 2, P[c0, 1] + box_um / 2)
    xb, yb = P[c0, 0] - box_um / 2 + 8, P[c0, 1] - box_um / 2 + 8
    b.plot([xb, xb + 20], [yb, yb], color="white", lw=2.5, zorder=5)
    b.text(xb + 10, yb + 3, "20 \u00b5m", color="white", fontsize=10, ha="center", va="bottom", zorder=5)
    fig.text(0.685, 0.95, "b  one cell (white) and its 18 senders,\n    in a 16-\u00b5m-deep slab around it", color="0.9",
             fontsize=12, va="top")
    for i_, (k, c) in enumerate(C.items()):
        fig.text(0.70 + 0.09 * i_, 0.06, k, color=c, fontsize=10, ha="center", weight="bold")
    fig.tight_layout(rect=(0, 0.08, 1, 0.84))               # both panels under one title line, tops aligned
    pa, pb = a.get_position(), b.get_position()
    b.set_position([pb.x0, pa.y0, pb.width, pa.height])
    fig.savefig(path, dpi=200, facecolor="black")
    plt.close(fig)


def slide_law():
    """The neuron graph on this fish, from the operator itself (the picture IS the graph trained), head left."""
    import exp17_slides as X17
    from plexus.tasks import trace_recording as TR
    png = os.path.join(PRES, "figs", "05_neuron_graph.png")
    pf = f"zebrafish/{REC1}_recording.npz"
    op = X17.neuron_graph_op(positions_file=pf)
    rec = TR.load(REC1)
    figure_graph(op, rec["pos_view"], png)
    E = {s: int(op._E[s][0].numel()) for s in ("short", "mid", "long") if s in op._E}
    right = (head("the law: a known ODE on a cell graph") + rows([
        ("state", "one per cell: dF/F"),
        ("cell", "its own time constant $\\tau_i$, rest $c_i$, 6 input weights $B_i$"),
        ("edges", ", ".join(f"{k} {v / 1e6:.2f}M" for k, v in E.items()) + ", one $W$ each"),
        ("", "6 nearest, 6 at 32 \\textmu m, 6 at 128 \\textmu m"),
        ("step", "$\\tau_i\\, dz_i/dt = -z_i + c_i + \\sum_j W_{ij}\\tanh z_j + B_i\\cdot u$"),
        ("inputs", "$u$: UV pulse, beam x, y, grating, swim L, R"),
        ("", "nothing recorded is read after the start")])
        + head("training") + rows([("", "horizons 1..30, every step scored (exp17)"),
                                    ("", "held-out trial windows never trained on")]))
    return ("05_law", frame("The law: a leaky ODE per cell, coupled by a learned graph, driven by the known inputs",
                            "\\panel{figs/05_neuron_graph.png}", right, "state_diffuse[neuron_graph] on glucose fish 1",
                            left_gap=3, deck_title="The law: a known ODE per cell, coupled by a learned graph, driven "
                                                   "by the known inputs"))


def slide_baselines():
    b = json.load(open(os.path.join(DATA, f"baselines_{REC1}.json")))
    m = np.load(os.path.join(GD, "graphs_data", "zebrafish", f"input_mask_{REC1}.npz"))
    png = os.path.join(EXP, "png", f"input_mask_{REC1}.png")
    import shutil
    shutil.copyfile(png, os.path.join(PRES, "figs", "06_input_mask.png"))
    g = b["gut_window_mse_resp"]
    right = (head("the references, before any training") + rows([
        ("gut-responsive", f"{b['gut_responsive']:,} cells (the paper's selection, training frames)"),
        ("noise", f"$\\sigma^2$ {b['noise_sigma2']:.3f} dF/F$^2$ over all cells (ZAPBench 0.0005)"),
        ("held-out gut", f"window MSE ($10^{{-3}}$): STA {g['sta'] * 1e3:.0f}, regression {g['reg'] * 1e3:.0f},"),
        ("", f"best recent mean {g['mean'] * 1e3:.0f}, persistence {g['pers'] * 1e3:.0f}"),
        ("control / gut", f"{b['evoked_ratio_ctrl_over_gut']:.2f}: the brain barely answers the off-fish UV"),
        ("replicable", f"{b['top1_cells']:,} cells, held-out gut evoked {b['evoked_top1_heldout_gut']:+.3f}")])
        + head("the input mask (exp17's, per input)") + rows([
            ("", f"top 10 \\% per input, training frames: union {int(m['mask'].sum()):,} cells"),
            ("uv", "site-blind trial-locked $|t|$: holds 71 \\% of the gut-responsive cells"),
            ("visual, swim", "exp17's coherence with the input")]))
    return ("06_baselines", frame("Before training: the gut-responsive cells, the references, the input mask",
                                  "\\panel{figs/06_input_mask.png}", right, f"data/baselines_{REC1}.json",
                                  deck_title="Before training: the references, and the input mask (the cells each "
                                             "input enters)"))


def slides_kymo(rec_name=REC1, n_rows=100):
    """ONE SLIDE PER INPUT (Cedric, 2026-10-03: "a kymograph as in exp17's slide 32, one slide per stimulus, the fish
    vertical"): left, the input over the session and the n_rows cells most locked to it (the input mask's own score:
    uv |t|, visual / swim coherence), dF/F rows z-scored, sorted by the lag of their response; the UV pulses (site
    colours) and the held-out windows (red) drawn through; right, the brain HEAD UP, that input's mask cells coloured on
    every cell in grey."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from plexus.tasks import trace_recording as TR
    rec = TR.load(rec_name)
    X, S, tr, sp = rec["dff"], rec["stimulus"], rec["trials"], rec["split"]
    t = rec["t_s"] / 60
    dt = float(np.median(np.diff(rec["t_s"])))
    M = np.load(os.path.join(GD, "graphs_data", "zebrafish", f"input_mask_{rec_name}.npz"))
    Pv = rec["pos_view"]
    up = np.stack([Pv[:, 1], -Pv[:, 0]], 1)                 # head left -> head UP
    INP = [("uv", "UV pulse", M["score_uv"], S[:, 0], "#ff4040", "trial-locked |t| over the training pulses"),
           ("visual", "grating speed", M["score_visual"], S[:, 3], "#4fc3f7", "coherence with the grating"),
           ("swim", "swim power (left)", M["score_swim"], S[:, 4], "#81c784", "coherence with the swim power")]
    out = []
    for key, label, score, u, col, how in INP:
        top = np.argsort(score)[::-1][:n_rows]
        Z = X[:, top]
        Z = (Z - Z.mean(0)) / (Z.std(0) + 1e-9)
        if key == "uv":                                     # lag = the time to peak of the trial-locked mean response
            on = [int(f) for f, h in zip(tr[:, 0], tr[:, 6]) if not h and f + 50 < len(X)]
            resp = np.mean([Z[f:f + 50] for f in on], 0)
            lag = resp.argmax(0)
        else:                                               # lag of the largest cross-correlation within 20 s
            uu = (u - u.mean()) / (u.std() + 1e-9)
            L = int(20 / dt)
            cc = np.stack([(uu[:len(uu) - k][:, None] * Z[k:]).mean(0) for k in range(L)], 0)
            lag = np.abs(cc).argmax(0)
        Z = Z[:, np.argsort(lag)]
        fig = plt.figure(figsize=(12, 6.2), facecolor="black")
        gs = fig.add_gridspec(2, 2, width_ratios=[3.2, 1], height_ratios=[0.6, 4], hspace=0.12, wspace=0.05)
        a0, a1, b_ = fig.add_subplot(gs[0, 0]), fig.add_subplot(gs[1, 0]), fig.add_subplot(gs[:, 1])
        _black(a0); _black(a1)
        a0.plot(t, u, color=col, lw=0.7)
        a0.set_xlim(t[0], t[-1]); a0.set_xticks([]); a0.set_yticks([])
        a0.set_title(f"{label} over the session", fontsize=10, loc="left", color="white")
        im = a1.imshow(Z.T, aspect="auto", cmap="inferno", vmin=-1, vmax=3, extent=[t[0], t[-1], n_rows, 0],
                       interpolation="nearest")
        for a_ in (a0, a1):
            for f, site, held in zip(tr[:, 0], tr[:, 2], tr[:, 6]):
                a_.axvline(t[int(f)], color=SITE_COLS.get(int(site), "w"), lw=0.6, alpha=0.8, ls="--" if held else "-")
            for f0 in np.where(np.diff(np.r_[0, (sp == 2).astype(int)]) == 1)[0]:
                f1 = f0 + int(np.argmax(sp[f0:] != 2)) if (sp[f0:] != 2).any() else len(sp)
                a_.axvspan(t[f0], t[min(f1, len(t) - 1)], color="#d62728", alpha=0.18, lw=0)
        a1.set_xlabel("time since the session's start, min", color="white")
        a1.set_ylabel(f"the {n_rows} cells most locked to the {label}\n(z-scored dF/F, sorted by lag)", fontsize=9)
        a1.set_title(f"rows: {how}; red bands: held-out trial windows", fontsize=9, loc="left", color="white")
        b_.set_facecolor("black"); b_.axis("off"); b_.set_aspect("equal")
        m = M["mask_by_input"][:, {"uv": 0, "visual": 3, "swim": 4}[key]] > 0
        b_.scatter(up[::8, 0], up[::8, 1], s=0.3, c="0.3", lw=0)
        b_.scatter(up[m, 0], up[m, 1], s=0.5, c=col, lw=0)
        b_.scatter(up[top, 0], up[top, 1], s=9, c="white", lw=0)
        b_.set_title(f"its input cells: top 10 % ({int(m.sum()):,}),\nthe {n_rows} rows in white; head up", fontsize=9,
                     color="white")
        y0 = up[:, 1].min() - 20
        b_.plot([up[:, 0].min(), up[:, 0].min() + 100], [y0, y0], color="white", lw=2)
        b_.text(up[:, 0].min() + 50, y0 - 8, "100 \u00b5m", color="white", fontsize=8, ha="center", va="top")
        png = f"06_kymo_{key}.png"
        fig.savefig(os.path.join(PRES, "figs", png), dpi=180, facecolor="black", bbox_inches="tight")
        plt.close(fig)
        right_rows = [("input", label), ("score", how), ("cells", f"top 10 %: {int(m.sum()):,} of {len(m):,}"),
                      ("rows", f"the {n_rows} highest scores, sorted by lag")]
        body = (f"% generated by tools/exp20_slides.py (input kymograph {key})\n\\begin{{frame}}[t]{{{DECK_TITLE} "
                f"$\\cdot$ the input cells of the {_tex(label)}}}\n\\vspace*{{\\bandgap}}\n"
                f"\\begin{{center}}\\includegraphics[width=0.98\\textwidth,height=0.80\\textheight,keepaspectratio]"
                f"{{figs/{png}}}\\end{{center}}\n\\end{{frame}}\n")
        out.append((f"06_kymo_{key}", body))
    return out


# ============================================================================== batches, runs, controls
BATCHES = {
    "1": ("which levers carry the gut response", ["gb_ng_base", "gb_ng_s1", "gb_ng_mask", "gb_ng_now", "gb_ng_nol1",
                                                "gb_ng_wide", "gb_ng_h50", "gb_gc_base", "gb_ng_base_lglu"], "gb_ng_nol1", "gb_ng_now"),
    "2": ("the same levers, without runaway cells", ["gb_ex_base", "gb_ex_s1", "gb_ex_nol1", "gb_ex_now", "gb_ex_mask", "gb_ex_h50",
                                     "gb_ex_base_lglu", "gb_ex_f4"], "gb_ex_nol1", "gb_ex_now"),
}


def md_rows():
    """{run: (v, what changed)} from the md's results table (the one place a run's change is written)."""
    md = open(os.path.join(ROOT, "experiments", "exp20_gutbrain_graphcast.md")).read()
    out = {}
    for line in md.splitlines():
        m = re.match(r"\\| (\\S+) \\| `training/gutbrain/(\\w+)` \\|(.*)\\|\\s*$", line)
        if m:
            cells = [c.strip() for c in m.group(3).split("|")]
            out[m.group(2)] = (m.group(1), cells[-2] if len(cells) >= 2 else "")
    return out


def landed(name):
    d = os.path.join(RUNS, name, "results")
    t = os.path.join(d, f"{name}_test.json")
    if not os.path.exists(t):
        return None
    r = {"name": name, "dir": os.path.join(RUNS, name), "test": json.load(open(t))}
    for k in ("trials", "freetrial"):
        p = os.path.join(d, f"{name}_{k}.json")
        r[k] = json.load(open(p)) if os.path.exists(p) else None
    rep = os.path.join(d, "report.json")
    r["report"] = json.load(open(rep)) if os.path.exists(rep) else {}
    return r


def brain_r2(d, stem):
    """THE BRAIN-MEAN R2 (exp17's headline, Cedric 2026-10-03): 1 - sum_t (pbar_t - obar_t)^2 / sum_t (obar_t - mean)^2
    over the free rollout's frames, obar / pbar the recorded / learned mean over the alive cells (trainer
    `_brain_mean_metrics`, read from the rollout's own movie npz)."""
    from plexus import trainer as T
    p = os.path.join(d, "results", f"{stem}_movie.npz")
    if not os.path.exists(p):
        return None
    z = np.load(p)
    return T._brain_mean_metrics(z["mean_obs_all"], z["mean_pred_all"])["brain_mean_r2"]


def cell_r2(d, stem):
    """The per-cell R2: R2 per frame over the alive cells against the denoised recording, the mean over the free
    rollout's frames (results/<stem>_free.npz, the trainer's `_trace_free` or a rollout variant)."""
    p = os.path.join(d, "results", f"{stem}_free.npz")
    return float(np.nanmean(np.load(p)["r2_denoised"])) if os.path.exists(p) else None


def control_table(name, now):
    """THE CONTROLS TABLE on every results slide (Cedric, 2026-10-03): the full model, the same model with W = 0 at
    inference, and the batch's model trained with no network -- brain-mean R2 and per-cell R2 of each free rollout.
    A row is left out when its rollout does not exist yet."""
    r, rn = landed(name), landed(now) if now else None
    f = lambda v: f"{v:+.2f}" if v is not None and np.isfinite(v) else "--"
    rws = [(f"full model ({_tex(name)})", brain_r2(r["dir"], name), cell_r2(r["dir"], name))]
    if os.path.exists(os.path.join(r["dir"], "results", f"{name}_W0_movie.npz")):
        rws.append(("W = 0 at inference", brain_r2(r["dir"], f"{name}_W0"), cell_r2(r["dir"], f"{name}_W0")))
    if rn and now != name:
        rws.append((f"trained with no network ({_tex(now)})", brain_r2(rn["dir"], now), cell_r2(rn["dir"], now)))
    body = "".join(f"{a} & {f(b_)} & {f(c)} \\\\\n" for a, b_, c in rws)
    return ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{}}\n"
            "free rollout, whole session & brain-mean R$^2$ & per-cell R$^2$ \\\\\n\\hline\n" + body
            + "\\end{tabular}\\par}\\vspace{6pt}\n")


def numbers(r):
    """The four numbers a batch slide shows for a run, from its own result files (None where not measured)."""
    from exp_measures import exp20 as M
    out = {"short": r["test"]["skill_short"], "free_r2": r["test"]["free"]["r2_denoised"], "trial": None, "free_gut": None,
           "brain_r2": brain_r2(r["dir"], r["name"])}
    if r["trials"]:
        g = [t for t in r["trials"]["trials"] if t["kind"] == "gut"]
        out["trial"] = M.window_skill([t["mse_resp"] for t in g], [t["mse_sta_resp"] for t in g])
    if r["freetrial"]:
        out["free_gut"] = r["freetrial"]["arms"]["full"]["evoked_gut_free_over_rec"]
        out["pattern"] = r["freetrial"]["arms"]["full"]["pattern_r_gut"]
    return out


def figure_batch(b, names, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    L = {n: landed(n) for n in names}
    N = {n: numbers(r) for n, r in L.items() if r}
    keys = [("short", "skill over the mean, h 1-3"), ("trial", "held-out trial skill over the STA"),
            ("free_gut", "free rollout: gut response / recorded"), ("brain_r2", "free rollout: brain-mean R$^2$")]
    fig, ax = plt.subplots(len(keys), 1, figsize=(7, 7.5), facecolor="black", sharex=True)
    x = np.arange(len(names))
    for a, (k, lab) in zip(ax, keys):
        _black(a)
        v = [N[n][k] if n in N and N[n].get(k) is not None else np.nan for n in names]
        a.bar(x, np.clip(v, -1.0, 1.5), 0.6, color=["#4fc3f7" if np.isfinite(t) and t >= 0 else "#ff7043" for t in v])
        for i, t in enumerate(v):
            if np.isfinite(t):
                a.text(i, (min(max(t, -1.0), 1.5)) + (0.04 if t >= 0 else -0.12), f"{t:+.2f}", ha="center",
                       color="white", fontsize=7)
        a.axhline(0, color="0.6", lw=0.6)
        a.set_ylabel(lab, fontsize=7, rotation=0, ha="right", va="center")
    ax[-1].set_xticks(x, [f"{i + 1}" for i in range(len(names))], fontsize=8)
    ax[-1].set_xlabel("arm (table, right)")
    fig.tight_layout()
    fig.savefig(path, dpi=180, facecolor="black")
    plt.close(fig)
    return N


def slide_batch(b):
    title, names, shown, now = BATCHES[b]
    N = figure_batch(b, names, os.path.join(PRES, "figs", f"batch_{b}_levers.png"))
    rw = md_rows()

    def f(n, k):
        v = N.get(n, {}).get(k)
        return f"{v:+.2f}" if v is not None and np.isfinite(v) else "--"
    tab = "".join(f"{i + 1} & {_tex(n)} & {f(n, 'short')} & {f(n, 'trial')} & {f(n, 'free_gut')} & {f(n, 'brain_r2')} \\\\\n"
                  if n in N else f"{i + 1} & {_tex(n)} & \\multicolumn{{4}}{{l}}{{running}} \\\\\n" for i, n in enumerate(names))
    right = (head(f"batch {b}: {title}") + "{\\scriptsize\\begin{tabular}{@{}r@{\\hspace{4pt}}l@{\\hspace{5pt}}r@{\\hspace{5pt}}r"
             "@{\\hspace{5pt}}r@{\\hspace{5pt}}r@{}}\n & arm & short & trial & free gut & brain R$^2$ \\\\\n\\hline\n" + tab
             + "\\end{tabular}\\par}\\vspace{6pt}\n"
             + "{\\scriptsize short: skill over the best recent mean, h 1-3, held-out windows. trial: skill over the "
               "stimulus-triggered mean, held-out gut trials, gut-responsive cells, from the pulse. free gut: the evoked response "
               "to the held-out gut pulses INSIDE the free rollout of the whole session (stimuli and the first frame only), over "
               "the recorded one. brain R$^2$: the whole session's brain-mean dF/F, learned against recorded (exp17's headline).\\par}\n")
    return (f"batch_{b}_levers", frame(f"batch {b}: every arm", f"\\panel{{figs/batch_{b}_levers.png}}", right,
                                       "the runs' _test, _trials, _freetrial json", deck_title=f"batch {b} ({_tex(title)}) $\\cdot$ every arm"))


def slides_run(name, b, now=None):
    import shutil
    r = landed(name)
    if not r:
        return []
    out, rw = [], md_rows()
    v, what = rw.get(name, ("", ""))
    dt = f"batch {b} $\\cdot$ {_tex(name)}"
    N = numbers(r)
    mv = os.path.join(r["dir"], "results", "movie.mp4")
    if os.path.exists(mv):
        shutil.copyfile(mv, os.path.join(PRES, "Movies", f"{name}.mp4"))
        shutil.copyfile(mv.replace(".mp4", ".png"), os.path.join(PRES, "Movies", f"{name}.png"))
        ft = r["freetrial"]["arms"]["full"] if r["freetrial"] else None
        right = (head(_tex(name)) + "{\\scriptsize " + _tex(what) + "\\par}\\vspace{6pt}\n" + rows(
            [("short", f"{N['short']:+.3f} over the best recent mean, h 1-3"),
             ("trial", f"{N['trial']:+.3f} over the STA (held-out gut trials)" if N["trial"] is not None else "--"),
             ("free R$^2$", f"{N['free_r2']:+.3f} (whole session, denoised)")]
            + ([("free gut", f"{ft['evoked_gut_free_over_rec']:.2f} of the recorded response, pattern r {ft['pattern_r_gut']:+.2f}"),
                ("free ctrl", f"{ft['evoked_ctrl_free_over_rec_gut']:+.2f} of the recorded gut response"),
                ("", ", ".join(f"{t['kind'][0]}{t['onset']}: {t['evoked_free']:+.3f} / {t['evoked_rec']:+.3f}" for t in ft["trials"]))]
               if ft else [])) + control_table(name, now))
        out.append((f"{name}_movie", frame("the free rollout of the whole session, recorded left, learned right",
                                           f"\\playmovie{{Movies/{name}}}", right, f"{name}/results/movie.mp4", deck_title=dt)))
    cp = os.path.join(r["dir"], "results", f"{name}_test.png")
    if os.path.exists(cp):
        shutil.copyfile(cp, os.path.join(PRES, "figs", f"{name}_test.png"))
        out.append((f"{name}_curves", frame("its forecasts against the baselines, step by step",
                                            f"\\panel{{figs/{name}_test.png}}", head(_tex(name)) + "{\\scriptsize the trainer's "
                                            "test figure: MSE per step ahead on the held-out windows, the law against the best "
                                            "recent mean, persistence and the stimulus lookup; the free rollout's R$^2$ per frame.\\par}\n",
                                            f"{name}_test.png", deck_title=dt)))
    return out


def slides_controls(name, now, b):
    """CEDRIC'S TWO CONTROLS (exp17 slides 26-27): the trained law with W = 0, and a law trained with no network."""
    import shutil
    r, rn = landed(name), landed(now)
    out = []
    dt = f"batch {b} $\\cdot$ network dynamics, not a function of the stimulus"
    if r and r["freetrial"] and "W0" in r["freetrial"]["arms"]:
        full, w0 = r["freetrial"]["arms"]["full"], r["freetrial"]["arms"]["W0"]
        nw = rn["freetrial"]["arms"]["full"] if rn and rn["freetrial"] else None
        ab = os.path.join(EXP, "data", f"ablation_{name}.json")
        A = json.load(open(ab)) if os.path.exists(ab) else None
        t = lambda a: ", ".join(f"{x['kind'][0]}{x['onset']} {x['evoked_free']:+.3f}" for x in a["trials"])
        rows_ = [("recorded", ", ".join(f"{x['kind'][0]}{x['onset']} {x['evoked_rec']:+.3f}" for x in full["trials"])),
                 ("full law", t(full)), ("W = 0", t(w0))] + ([("no network", t(nw))] if nw else [])
        right = (head("1. the trained law with W = 0") + "{\\scriptsize every edge weight set to 0 after training; the "
                 "inputs kept\\par}\\vspace{4pt}\n" + head("2. trained with no network from the start")
                 + "{\\scriptsize " + _tex(now) + ": the fair control (B and the cells' constants fitted without W)\\par}\\vspace{6pt}\n"
                 + head("evoked change at the held-out pulses, free rollout") + rows(rows_)
                 + rows([("gut / recorded", f"full {full['evoked_gut_free_over_rec']:.2f}, W = 0 {w0['evoked_gut_free_over_rec']:.2f}"
                          + (f", no network {nw['evoked_gut_free_over_rec']:.2f}" if nw else "")),
                         ("pattern r", f"full {full['pattern_r_gut']:+.2f}, W = 0 {w0['pattern_r_gut']:+.2f}"
                          + (f", no network {nw['pattern_r_gut']:+.2f}" if nw else ""))]
                        + ([("free R$^2$", f"full {A['full']['r2_denoised']:+.3f}, W = 0 {A['W0']['r2_denoised']:+.3f}")] if A else [])))
        mv = os.path.join(r["dir"], "results", "movie_W0.mp4")
        left = "\\panel{figs/ablation_" + name + ".png}"
        if os.path.exists(mv):
            shutil.copyfile(mv, os.path.join(PRES, "Movies", f"{name}_W0.mp4"))
            shutil.copyfile(mv.replace(".mp4", ".png"), os.path.join(PRES, "Movies", f"{name}_W0.png"))
            left = f"\\playmovie{{Movies/{name}_W0}}"
        elif A:
            shutil.copyfile(os.path.join(EXP, "data", "figs", f"ablation_{name}.png"), os.path.join(PRES, "figs", f"ablation_{name}.png"))
        else:
            left = ""
        out.append((f"{name}_controls", frame(f"{_tex(name)} with W = 0, and a law with no network: the gut response is the network's",
                                              left, right, f"{name}_freetrial.json, ablation_{name}.json", deck_title=dt)))
    if rn:
        out += [(k.replace("_movie", "_nonet_movie"), v) for k, v in slides_run(now, b, now) if k.endswith("_movie")]
    return out


def figure_network(name, now, path):
    """CEDRIC'S CLAIM IN ONE FIGURE: top, the gut-responsive cells' mean dF/F around each held-out pulse inside the free
    rollout of the whole session (recorded, the full law, the same law with W = 0, the law trained with no network);
    bottom, the whole brain's mean dF/F over the session (exp17's white trace), the same four."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    r, rn = landed(name), landed(now)
    ft = r["freetrial"]
    nw = rn["freetrial"]["arms"]["full"] if rn and rn["freetrial"] else None
    pre, post = ft["window"]
    dt = float(np.median(np.diff(np.load(os.path.join(GD, "graphs_data", "zebrafish",
                                                      f"{ft['recording']}_recording.npz"))["t_s"])))
    COL = {"rec": "#4caf50", "full": "white", "W0": "#ff5252", "now": "#42a5f5"}
    LAB = {"rec": "recorded", "full": "network law", "W0": "same law, W = 0", "now": "trained with no network"}
    trials = ft["arms"]["full"]["trials"]
    fig = plt.figure(figsize=(8.6, 6.4), facecolor="black")
    gs = fig.add_gridspec(2, len(trials), height_ratios=[1.25, 1], hspace=0.45, wspace=0.28)
    tt = (np.arange(-pre, post + 1)) * dt
    for j, t0 in enumerate(trials):
        a = fig.add_subplot(gs[0, j])
        _black(a)
        cur = {"rec": t0["trace_rec"], "full": t0["trace_free"],
               "W0": ft["arms"]["W0"]["trials"][j]["trace_free"]}
        if nw:
            cur["now"] = nw["trials"][j]["trace_free"]
        for k, y in cur.items():
            a.plot(tt, y, color=COL[k], lw=2.0 if k in ("rec", "full") else 1.4, label=LAB[k])
        a.axvline(0, color="#ffd54f", lw=0.8, ls=":")
        a.set_title(f"{'control (off the fish)' if t0['kind'] == 'control' else 'gut'} pulse, held out\n"
                    f"volume {t0['onset']}", fontsize=8)
        a.set_xlabel("s from the UV pulse", fontsize=7)
        if j == 0:
            a.set_ylabel(f"mean dF/F, {ft['responsive_cells']:,}\ngut-responsive cells", fontsize=7)
    h, l = a.get_legend_handles_labels()
    fig.legend(h, l, loc="upper center", ncol=4, frameon=False, fontsize=8, labelcolor="white")
    b = fig.add_subplot(gs[1, :])
    _black(b)
    mf = np.load(os.path.join(r["dir"], "results", f"{name}_movie.npz"))
    m0 = np.load(os.path.join(r["dir"], "results", f"{name}_W0_movie.npz"))
    T = mf["r2_t"] * dt / 60
    b.plot(T, mf["mean_obs_all"], color=COL["rec"], lw=1.0, label=LAB["rec"])
    b.plot(T, mf["mean_pred_all"], color=COL["full"], lw=1.0)
    b.plot(T, m0["mean_pred_all"], color=COL["W0"], lw=1.0)
    if rn:
        mn = np.load(os.path.join(rn["dir"], "results", f"{now}_movie.npz"))
        b.plot(T, mn["mean_pred_all"], color=COL["now"], lw=1.0)
    tr = np.load(os.path.join(GD, "graphs_data", "zebrafish", f"{ft['recording']}_recording.npz"))["trials"]
    for f, site, held in zip(tr[:, 0], tr[:, 2], tr[:, 6]):
        b.axvline(f * dt / 60, color="#9e9e9e" if site == 1 else "#ffd54f", lw=1.2 if held else 0.5,
                  ls="--" if held else "-", alpha=0.8)
    b.set_xlabel("min (free rollout from the first volume; UV pulses: grey off the fish, yellow gut; dashed held out)", fontsize=7)
    b.set_ylabel("whole-brain\nmean dF/F", fontsize=7)
    fig.savefig(path, dpi=200, facecolor="black", bbox_inches="tight")
    plt.close(fig)


def slide_network(name, now, b):
    r, rn = landed(name), landed(now)
    if not (r and r["freetrial"] and "W0" in r["freetrial"]["arms"]):
        return ("", "")
    png = f"batch_{b}_network.png"
    figure_network(name, now, os.path.join(PRES, "figs", png))
    full, w0 = r["freetrial"]["arms"]["full"], r["freetrial"]["arms"]["W0"]
    nw = rn["freetrial"]["arms"]["full"] if rn and rn["freetrial"] else None
    ab = os.path.join(EXP, "data", f"ablation_{name}.json")
    A = json.load(open(ab)) if os.path.exists(ab) else None
    lk = os.path.join(EXP, "data", f"leak_{name}.json")
    LK = json.load(open(lk)) if os.path.exists(lk) else None
    fr = lambda a: f"{a['evoked_gut_free_over_rec']:.2f}"
    right = (head("the claim") + "{\\scriptsize the response to a held-out gut pulse is made by the network: "
             "remove it, after training or from the start, and the response is gone\\par}\\vspace{6pt}\n"
             + head("gut response / recorded (free rollout)") + rows(
                 [("network law", f"{fr(full)}, pattern r {full['pattern_r_gut']:+.2f} over the cells"),
                  ("W = 0", f"{fr(w0)}, pattern r {w0['pattern_r_gut']:+.2f}")]
                 + ([("no network", f"{fr(nw)}, pattern r {nw['pattern_r_gut']:+.2f}")] if nw else []))
             + head("whole session: brain-mean R$^2$ (per-cell R$^2$)") + rows(
                 [("network law", f"{brain_r2(r['dir'], name):+.2f} ({A['full']['r2_denoised']:+.2f})" if A else "--"),
                  ("W = 0", f"{brain_r2(r['dir'], name + '_W0'):+.2f} ({A['W0']['r2_denoised']:+.2f})" if A else "--")]
                 + ([("no network", f"{brain_r2(rn['dir'], now):+.2f} ({rn['test']['free']['r2_denoised']:+.2f}): the drift, "
                                    "no response")] if rn else []))
             + head("driven by the stimuli only") + rows(
                 [("start", "one recorded volume, then the inputs only"),
                  ("leak check", (f"recording after the start zeroed or noise: max {max(x['max_abs_zeroed'] for x in LK['rows']):.1e} dF/F, "
                                  f"= run-to-run {max(x['max_abs_self'] for x in LK['rows']):.1e}") if LK else "--"),
                  ("caveat", "swim power is still an input here (batch 3: none)")]))
    return (f"batch_{b}_network", frame("Network dynamics, not a function of the stimulus",
                                        f"\\panel{{figs/{png}}}", right, f"{name}_freetrial.json, {now}_freetrial.json, ablation_{name}.json",
                                        deck_title=f"batch {b} $\\cdot$ network dynamics, not a function of the stimulus"))


def slide_overview():
    rw = md_rows()
    lines = []
    for b, (title, names, _, _) in BATCHES.items():
        for n in names:
            r = landed(n)
            if not r:
                continue
            N = numbers(r)
            fmt = lambda v: f"{v:+.2f}" if v is not None and np.isfinite(v) else "--"
            lines.append(f"{b}.{names.index(n) + 1} & {_tex(n)} & {fmt(N['short'])} & {fmt(N['trial'])} & {fmt(N.get('free_gut'))} & {fmt(N['brain_r2'])} \\\\")
    body = ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{8pt}}l@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{\\hspace{8pt}}r@{}}\n"
            "arm & run & short & trial & free gut & brain R$^2$ \\\\\n\\hline\n" + "\n".join(lines) + "\n\\end{tabular}\\par}")
    return ("90_overview", (f"% generated by tools/exp20_slides.py (overview)\n\\begin{{frame}}[t]{{{DECK_TITLE} $\\cdot$ every landed run}}\n"
                            f"\\vspace*{{\\bandgap}}\n{body}\n\\end{{frame}}\n"))


def main():
    for d in ("slides", "Movies", "figs"):
        os.makedirs(os.path.join(PRES, d), exist_ok=True)
    deck = []
    for fn in (slide_paper, slide_deposit, slide_anatomy, slide_fish, slide_fig3d, slide_law, slide_baselines):
        try:
            deck.append(fn())
        except Exception as e:                      # one slide's failure must not lose the deck
            print(f"[slides] {fn.__name__} FAILED: {e}")
    try:
        deck += slides_kymo()
    except Exception as e:
        print(f"[slides] slides_kymo FAILED: {e}")
    for b, (_, names, shown, now) in BATCHES.items():
        if not any(landed(n) for n in names):
            continue
        deck.append(slide_batch(b))
        deck += slides_run(shown, b, now)
        deck.append(slide_network(shown, now, b))
        deck += slides_controls(shown, now, b)
    deck.append(slide_overview())
    out = []
    for stem, body in deck:
        if not body:
            print(f"[slides] {stem}: no data yet, skipped")
            continue
        open(os.path.join(PRES, "slides", f"{stem}.tex"), "w").write(body)
        out.append(stem)
        print(f"[slides] {stem}")
    open(os.path.join(PRES, "slides", "all.tex"), "w").write(
        "% generated by tools/exp20_slides.py\n" + "".join(f"{'% ' if s in HIDDEN else ''}\\input{{slides/{s}.tex}}\n"
                                                           for s in out))


if __name__ == "__main__":
    main()
