"""Build the exp20 deck (a learned law on the gut-brain recordings of Chen, James, Ruetten et al. 2026): figures and
slide bodies, no number typed by hand.

    PYTHONPATH=src:tools /workspace/.conda_envs/neural-graph-linux/bin/python tools/exp20_slides.py
    python presentation/fit_deck.py --dir experiments/exp20_gutbrain_graphcast/presentation --deck exp20.tex

The template is exp17's (`tools/exp17_slides.py`, `presentation/`): the picture LEFT, the specifics -- numbers,
equations, the data's provenance -- RIGHT in a `\\fitcol`. Every number on a slide is read from the file it describes
(the deposit's listing, the exported recording and its provenance, the paper's figure values in PAPER, each with its
figure and panel). Runs in the devcontainer only (INSTRUCTION.md, the cluster rule).

    01  the paper: all-optical gut-brain interrogation                  (Fig. 1 page)
    02  the deposit: conditions, fish, what each file holds              (figure)
    03  one fish: anatomy, cells, the known inputs over the session      (figure, from the exported recording)
    04  the target of the integration gate: Fig. 3d                       (figure crop + GV/GM)
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict

import numpy as np

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
EXP = os.path.join(ROOT, "experiments", "exp20_gutbrain_graphcast")
PRES = os.path.join(EXP, "presentation")
DATA = os.path.join(EXP, "data")
PAPERS = os.path.join(EXP, "papers")
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "tools"))
DECK_TITLE = "gut-brain GNN"

# THE PAPER'S NUMBERS, each with its figure and panel (read off papers/figs/*_crop.png, +-1 on the bars)
PAPER = {
    "fig3d": {"regions": ["OT", "PBN", "nodose", "LH", "medial idMO", "DVC"],
              "GMV": [55, 35, 14, 62, 33, 30], "GM": [28, 31, 12, 48, 27, 26], "GV": [33, 9, 4, 26, 10, 7],
              "midbrain": ["OT"], "hindbrain": ["PBN", "medial idMO", "DVC"]},
    "fig2g": {"foregut": 1440, "midgut": 350, "N": 4},
    "fig2i": {"AP": (30, 165), "PBN": (25, 110), "N": 3},
    "fig1e": {"AP": 6, "PBN": 6, "DVC": 6, "medial idMO": 6, "OT": 5, "LH": 4, "nodose": 4, "N": 6},
}
COND_ORDER = ["glucose", "glutamate", "Lglucose", "fish_water", "blood_glucose"]
COND_LABEL = {"glucose": "D-glucose, gut", "glutamate": "glutamate, gut", "Lglucose": "L-glucose, gut (control)",
              "fish_water": "fish water, gut (control)", "blood_glucose": "D-glucose, blood (portal)"}
SITE_COL = {1: "#9e9e9e", 2: "#ff4040", 3: "#ffa040"}


def frame(title, left, right, src, deck_title=None):
    return (f"% generated by tools/exp20_slides.py from {src} ({title})\n"
            f"\\begin{{frame}}[t]{{{deck_title or DECK_TITLE}}}\n\\vspace*{{\\bandgap}}\n"
            "\\begin{columns}[T,onlytextwidth]\n\\begin{column}{0.58\\textwidth}\n"
            f"{left}\n\\end{{column}}\n\\begin{{column}}{{0.4\\textwidth}}\n\\vspace*{{2\\baselineskip}}\n"
            f"\\fitcol{{%\n{right}}}\n\\end{{column}}\n\\end{{columns}}\n\\end{{frame}}\n")


def head(s):
    return f"{{\\normalsize\\textbf{{{s}}}}}\\\\[4pt]\n"


def rows(pairs):
    body = "".join(f"{k} & {v} \\\\\n" for k, v in pairs)
    return ("{\\scriptsize\\begin{tabular}{@{}l@{\\hspace{7pt}}l@{}}\n" + body + "\\end{tabular}\\par}\n"
            "\\vspace{8pt}")


def _black(ax):
    ax.set_facecolor("black")
    for s in ax.spines.values():
        s.set_color("0.6")
    ax.tick_params(colors="0.8", labelsize=8)
    ax.xaxis.label.set_color("0.9")
    ax.yaxis.label.set_color("0.9")
    ax.title.set_color("white")


# ============================================================================== 01 the paper
def slide_paper():
    import fitz
    pdf = os.path.join(PAPERS, "Chen_2026_NatCommun_s41467-026-76242-8_gut_vascular_interoception.pdf")
    d = fitz.open(pdf)
    pg = d[2]
    W, H = pg.rect.width, pg.rect.height
    png = os.path.join(PRES, "figs", "01_paper_fig1.png")
    pg.get_pixmap(dpi=220, clip=fitz.Rect(W * 0.07, H * 0.06, W * 0.95, H * 0.62)).save(png)
    f1 = PAPER["fig1e"]
    right = (head("Chen, James, Ruetten et al. 2026") + rows([
        ("", "Nat Commun 17:9881, Ahrens \\& Fitzgerald labs"),
        ("fish", "Tg(elavl3:H2B-jGCaMP7f), 7-8 dpf, light sheet"),
        ("rate", "1-3 whole-brain volumes per second"),
        ("inputs", "caged nutrient in the gut, released by a UV beam;"),
        ("", "a drifting grating (optomotor); fictive swimming"),
        ("controls", "UV off the fish; caged L-glucose; fish water")])
        + head("what they found (Fig. 1e, 2, 3)") + rows([
            ("D-glucose", ", ".join(f"{k} {v}/{f1['N']}" for k, v in f1.items() if k != "N") + " fish"),
            ("", "L-glucose and fish water: 0 fish (Fig. 2c,d)"),
            ("site", f"foregut {PAPER['fig2g']['foregut']:,} vs midgut {PAPER['fig2g']['midgut']:,} cells (Fig. 2g)"),
            ("integration", "hindbrain: gut + motor; midbrain: gut + visual + motor")])
        + head("their model") + "{\\scriptsize one neuron at a time: lagged linear kernels on gut UV, control UV,\\\\ "
        "visual and motor regressors, smoothness-regularised (Fig. 1d)\\par}\n")
    return ("01_paper", frame("Whole-brain imaging while a nutrient is released in the gut by light",
                              "\\panel{figs/01_paper_fig1.png}", right, os.path.basename(pdf)))


# ============================================================================== 02 the deposit
def deposit():
    j = json.load(open(os.path.join(DATA, "figshare_article.json")))
    by = defaultdict(lambda: defaultdict(float))
    fish = defaultdict(set)
    for f in j["files"]:
        m = re.match(r"(Lglucose|blood_glucose|fish_water|glucose|glutamate)_fish(\d+)_", f["name"])
        if not m:
            continue
        c, k = m.group(1), int(m.group(2))
        kind = "cells" if "cells0" in f["name"] else ("volume" if "volume0" in f["name"] else "ephys")
        by[c][kind] += f["size"] / 1e9
        fish[c].add(k)
    return j, by, fish


def slide_deposit():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    j, by, fish = deposit()
    fig, ax = plt.subplots(figsize=(7, 4.2), facecolor="black")
    _black(ax)
    x = np.arange(len(COND_ORDER))
    bot = np.zeros(len(x))
    for kind, col in (("cells", "#4fc3f7"), ("ephys", "#ffb74d"), ("volume", "#9e9e9e")):
        v = np.array([by[c][kind] for c in COND_ORDER])
        ax.bar(x, v, 0.6, bottom=bot, color=col, label=kind)
        bot += v
    for i, c in enumerate(COND_ORDER):
        ax.text(i, bot[i] + 2, f"{len(fish[c])} fish", ha="center", color="white", fontsize=9)
    ax.set_xticks(x, [COND_LABEL[c].replace(", ", "\n") for c in COND_ORDER], fontsize=8)
    ax.set_ylabel("GB in the deposit")
    leg = ax.legend(frameon=False, fontsize=8, labelcolor="white")
    fig.tight_layout()
    png = os.path.join(PRES, "figs", "02_deposit.png")
    fig.savefig(png, dpi=200, facecolor="black")
    plt.close(fig)
    tot = sum(f["size"] for f in j["files"]) / 1e9
    right = (head("the deposit") + rows([
        ("", f"Figshare 10.25378/janelia.31967640"),
        ("files", f"{len(j['files'])}, {tot:.1f} GB, downloaded unbinned"),
        ("per fish", "cells0\\_clean.hdf5: Voluseg traces of every cell"),
        ("", "volume0.hdf5: the mean volume (anatomy)"),
        ("", "*.26chFlt: 26 channels at 6 kHz -- swim L/R,"),
        ("", "light-sheet trigger, UV, beam galvo, grating")])
        + head("conditions") + rows([(COND_LABEL[c], f"{len(fish[c])} fish") for c in COND_ORDER])
        + head("not in it") + rows([("", "raw volumes; parameters.pickle; atlas registration")]))
    return ("02_deposit", frame("The deposit: five conditions, one session per fish, traces of every cell",
                                "\\panel{figs/02_deposit.png}", right, "data/figshare_article.json"))


# ============================================================================== 03 one fish
def slide_fish(cond="glucose", k=1):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from plexus.paths import graphs_data_path
    name = f"gutbrain_{cond}_f{k}"
    f = graphs_data_path("zebrafish", f"{name}_recording.npz")
    if not os.path.exists(f):
        return (f"03_{name}", "")
    z = np.load(f)
    prov = json.load(open(f.replace(".npz", ".json")))
    X, P, S, tr, t = z["dff"], z["pos_um"], z["stimulus"], z["trials"], z["t_s"] / 60
    fig = plt.figure(figsize=(7.2, 6.6), facecolor="black")
    gs = fig.add_gridspec(5, 1, height_ratios=[3.2, 0.5, 0.5, 0.5, 1.4], hspace=0.35)
    ax = fig.add_subplot(gs[0])
    _black(ax)
    sub = np.random.default_rng(0).choice(len(P), min(40000, len(P)), replace=False)
    act = X[:, sub].std(0)
    ax.scatter(P[sub, 0], P[sub, 1], s=0.15, c=act, cmap="inferno", vmin=0, vmax=np.percentile(act, 99), lw=0)
    ax.set_aspect("equal")
    ax.set_xticks([]); ax.set_yticks([])
    ax.set_title(f"{len(P):,} cells, coloured by their dF/F's standard deviation (40,000 drawn)", fontsize=8)
    names = ["UV pulses", "grating speed", "swim power (L)"]
    for i, (nm, col) in enumerate(zip(names, (None, 3, 4))):
        a = fig.add_subplot(gs[1 + i])
        _black(a)
        if col is None:
            for r in tr:
                a.axvline(t[int(r[0])], color=SITE_COL.get(int(r[2]), "w"), lw=1.5 if r[6] else 0.8,
                          ls="-" if not r[6] else "--")
            a.set_ylim(0, 1)
        else:
            a.plot(t, S[:, col], color="#4fc3f7" if col == 3 else "#81c784", lw=0.6)
        a.set_yticks([]); a.set_xticks([])
        a.set_ylabel(nm, rotation=0, ha="right", va="center", fontsize=8)
        a.set_xlim(t[0], t[-1])
    a = fig.add_subplot(gs[4])
    _black(a)
    a.plot(t, np.median(X, 1), color="white", lw=0.6)
    for r in tr:
        a.axvline(t[int(r[0])], color=SITE_COL.get(int(r[2]), "w"), lw=0.5, alpha=0.6)
    a.set_xlim(t[0], t[-1])
    a.set_xlabel("min")
    a.set_ylabel("median\ndF/F", rotation=0, ha="right", va="center", fontsize=8)
    png = os.path.join(PRES, "figs", f"03_{name}.png")
    fig.savefig(png, dpi=200, facecolor="black", bbox_inches="tight")
    plt.close(fig)
    sites = {int(s): int((tr[:, 2] == s).sum()) for s in np.unique(tr[:, 2])}
    ext = prov["extent_um"]
    right = (head(f"{cond} fish {k}") + rows([
        ("volumes", f"{prov['frames']:,}, {prov['volume_s']:.3f} s apart, {prov['frames'] * prov['volume_s'] / 60:.1f} min"),
        ("cells", f"{prov['cells_kept']:,} of {prov['cells_in_file']:,} (baseline $\\geq$ {prov['min_signal_counts']:.0f} counts above background)"),
        ("brain", f"{ext[0]:.0f} x {ext[1]:.0f} x {ext[2]:.0f} \\textmu m (voxel inferred)"),
        ("dF/F", f"clipped to [{prov['clip'][0]}, {prov['clip'][1]}]: {prov['frac_clipped'] * 100:.2f} \\% of values")])
        + head("the known inputs (forcings)") + rows([
            ("UV", f"{len(tr)} pulses of {np.median(tr[:, 1]):.0f} ms; site 1 (grey, off the fish) {sites.get(1, 0)},"),
            ("", f"site 2 (red) {sites.get(2, 0)}, site 3 (orange) {sites.get(3, 0)}: gut"),
            ("", "the law reads the pulse and the beam's galvo x, y only"),
            ("grating", f"forward, open loop, on {np.mean(S[:, 3] > 0) * 100:.0f} \\% of volumes"),
            ("swim", f"left: bouts on {np.mean(S[:, 4] > 0.1) * 100:.1f} \\% of volumes; right: "
                     f"{'live' if prov['swim_live'][1] else 'no bouts (dead channel)'}")])
        + head("held out") + rows([
            ("", f"the last full pulse of every site (dashed): {int((z['split'] == 2).sum())} volumes"),
            ("", f"window {prov['window_volumes'][0]} before + {prov['window_volumes'][1]} after a pulse (55 s)")]))
    return (f"03_{name}", frame(f"One session: {COND_LABEL[cond]}, fish {k}, and its known inputs",
                                f"\\panel{{figs/03_{name}.png}}", right, f"{name}_recording.npz"))


# ============================================================================== 04 Fig. 3d
def slide_fig3d():
    import shutil
    src = os.path.join(PAPERS, "figs", "Chen2026_fig3d_crop.png")
    shutil.copyfile(src, os.path.join(PRES, "figs", "04_fig3d.png"))
    F = PAPER["fig3d"]
    gvgm = {r: gv / gm for r, gv, gm in zip(F["regions"], F["GV"], F["GM"])}
    mid = np.mean([gvgm[r] for r in F["midbrain"]])
    hind = np.mean([gvgm[r] for r in F["hindbrain"]])
    right = (head("what Fig. 3d measures") + "{\\scriptsize the gain in a neuron's model correlation from adding\\\\ "
             "motor (GM), visual (GV) or both (GMV) regressors\\\\ to the gut-only model, \\% (N = 6 fish)\\par}\\vspace{6pt}\n"
             + head("GV / GM per region") + rows([(r, f"{F['GV'][i]} / {F['GM'][i]} = {gvgm[r]:.2f}")
                                                  for i, r in enumerate(F["regions"])])
             + head("the gate (G-region)") + rows([
                 ("midbrain", f"OT: {mid:.2f}"), ("hindbrain", f"PBN, medial idMO, DVC: {hind:.2f}"),
                 ("ratio", f"{mid / hind:.1f}: the law's input ablations, read the same way,"),
                 ("", "against the same ruler on the recording")]))
    return ("04_fig3d", frame("The integration map the law should learn: Fig. 3d",
                              "\\panel{figs/04_fig3d.png}", right, "papers/figs/Chen2026_fig3d_crop.png"))


def main():
    for d in ("slides", "Movies", "figs"):
        os.makedirs(os.path.join(PRES, d), exist_ok=True)
    out = []
    for fn in (slide_paper, slide_deposit, slide_fish, slide_fig3d):
        stem, body = fn()
        if not body:
            print(f"[slides] {stem}: no data yet, skipped")
            continue
        open(os.path.join(PRES, "slides", f"{stem}.tex"), "w").write(body)
        out.append(stem)
        print(f"[slides] {stem}")
    open(os.path.join(PRES, "slides", "all.tex"), "w").write(
        "% generated by tools/exp20_slides.py\n" + "".join(f"\\input{{slides/{s}.tex}}\n" for s in out))


if __name__ == "__main__":
    main()
