#!/usr/bin/env python
"""Write the three minisite scenes as declared specs under `config/atlas/`.

WHY THESE ARE THE ONLY NEW SPECS IN THE PROMOTION. Everything else reuses `config/okuda/`, because a
comparison against a spec neither side has ever run proves nothing. These three are different: they
are the scenes the minisite PUBLISHES, and until now they existed only as pictures and a paragraph.
Writing them down is what makes "the promoted core reproduces the minisite" a claim that can fail.

    vertex_spheroid       the growth line alone: 200 cells -> a spheroid, 401 frames
    turing_coral          Gray-Scott on the cell graph, on a mesh that does not grow
    turing_grow_divide    the two composed: the pattern drives the growth

THEY ARE GENERATED FROM THE GATE SPECS, not written fresh, for the same reason gate 01's arms are:
`vertex_spheroid` IS gate 00's model, and a hand-copied second version of a 100-line spec differs
from it within a week. What each scene adds is its own `general:` and, for the two chemistry ones,
the reaction block.

    python tools/make_atlas_scenes.py
"""
from __future__ import annotations

import copy
import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GATES = os.path.join(ROOT, "config", "gates")
ATLAS = os.path.join(ROOT, "config", "atlas")

# Gray-Scott on the cell graph, as `coral_fixed_ball` and `b_gs_plain_soft_lo` run it. `chi` is the
# CROSS-DIFFUSION that makes the pattern follow the surface rather than the index order.
CHEM = [
    {"op": "cell_chem_seed", "at": "cell", "seed": 0, "before_frame": 3,
     "mode": "scatter", "seed_frac": 0.06},
    {"op": "cell_neighbours", "at": "cell", "vertex_set": "vertex"},
    {"op": "cell_chem_diffuse", "at": "cell", "implementation": "graph_laplacian",
     "d_a": 0.08, "d_h": 0.16, "chi": 1.3},
    {"op": "cell_chem_react", "at": "cell", "model": "gray_scott",
     "F": 0.046, "kk": 0.062, "rate": 1.0},
]
CHEM_SCHED = ["cell_chem_seed", "cell_neighbours", "cell_chem_diffuse", "cell_chem_react"]

HDR = """# {name} -- {what}
#
# ONE OF THE THREE MINISITE SCENES, generated by `tools/make_atlas_scenes.py` from
# `config/gates/{parent}.yaml` so the mechanics is the gated one and not a second copy of it.
#
{extra}"""


def write(name, what, parent, extra, edit):
    base = yaml.safe_load(open(os.path.join(GATES, f"{parent}.yaml")))
    c = copy.deepcopy(base)
    c.pop("_gate", None)
    c["general"] = dict(c["general"])
    c["general"]["name"] = name
    edit(c)
    os.makedirs(ATLAS, exist_ok=True)
    p = os.path.join(ATLAS, f"{name}.yaml")
    with open(p, "w") as f:
        f.write(HDR.format(name=name, what=what, parent=parent, extra=extra))
        yaml.safe_dump(c, f, sort_keys=False)
    print(f"  wrote {os.path.relpath(p, ROOT)}  ({len(c['operators'])} operators, "
          f"{c['general']['n_frames']} frames)")


def main():
    # ---------------------------------------------------------------- 1. the spheroid
    write(
        "vertex_spheroid",
        "the growth line alone: 200 cells become a spheroid over 401 frames",
        "gate_00_spheroid",
        """# THE MINISITE'S PUBLISHED NUMBERS FOR THIS SCENE ARE THE BUG'S, and this spec does not
# reproduce them on purpose. The page reports 200 -> 6,076 cells, apical radius x3.56, aspect 1.02,
# 1,384 T1s. Those are the `_PRESYNC` tissue's: measured on that cache, the per-junction myosin array
# is MISALIGNED with the half-edge table on 56 of its 200 meshes, by up to 1,356 entries -- so on 28%
# of frames the belt pulled on junctions it was not indexing. `junction_sync` re-keys it, and with the
# re-key the same model reaches 6,914 cells at x3.8606, aspect 1.0193, 1,499 T1s. That is what this
# scene produces and what `gate_00_spheroid` asserts; the published figure predates the fix.
""",
        lambda c: None,
    )

    # ---------------------------------------------------------------- 2. the coral
    def coral(c):
        c["general"]["n_frames"] = 6000
        c["general"]["record_cap"] = 602            # 6000 frames strided to ~600 rows
        c["sets"]["vertex"]["n"] = 24000            # 4,000 cells x ~2 vertices, x3 headroom
        c["sets"]["cell"]["n"] = 12000
        seed = next(o for o in c["operators"] if o["op"] == "mesh_seed")
        seed["n_cells"] = 4000
        # NO GROWTH AND NO DIVISION: this scene is the PATTERN, on a surface that holds still. The
        # cell count is fixed, so what moves is chemistry and nothing else -- which is the only way
        # to see whether the Turing pattern is a property of the reaction or of the remeshing.
        drop = {"cell_grow", "cell_divide", "junction_myosin", "junction_sync",
                "medioapical_myosin", "cytokinetic_ring"}
        c["operators"] = [o for o in c["operators"] if o["op"] not in drop]
        c["schedule"] = [x for x in c["schedule"] if x not in drop]
        i = c["schedule"].index("cell_mechanics")
        c["operators"] = c["operators"][:1] + CHEM + c["operators"][1:]
        c["schedule"] = c["schedule"][:i] + CHEM_SCHED + c["schedule"][i:]
    write(
        "turing_coral",
        "Gray-Scott on the cell graph, 4,000 cells, on a surface that does not grow",
        "gate_00_spheroid",
        """# THE DIFFUSION IS ON THE CELL GRAPH, NOT ON A LATTICE. The cells are the nodes,
# `cell_neighbours` is the graph, and the Laplacian runs over shared faces -- so the domain is the
# tissue's own topology. `chi` is the CROSS-DIFFUSION that makes the pattern follow the surface
# rather than the index order, and it is the parameter that separates this from a Gray-Scott on a
# sphere-shaped array.
#
# GROWTH AND DIVISION ARE REMOVED, and that is the scene. With a fixed cell count the only thing
# moving is the chemistry, which is the one way to see whether the pattern is a property of the
# REACTION or of the remeshing that a growing tissue does underneath it.
""",
        coral,
    )

    # ---------------------------------------------------------------- 3. the two composed
    def both(c):
        c["general"]["n_frames"] = 1800
        c["general"]["record_cap"] = 602
        seed = next(o for o in c["operators"] if o["op"] == "mesh_seed")
        seed["n_cells"] = 2000
        c["sets"]["vertex"]["n"] = 120000
        c["sets"]["cell"]["n"] = 60000
        drop = {"junction_myosin", "junction_sync", "medioapical_myosin", "cytokinetic_ring"}
        c["operators"] = [o for o in c["operators"] if o["op"] not in drop]
        c["schedule"] = [x for x in c["schedule"] if x not in drop]
        # the chemistry, plus the coupling that makes it DRIVE the growth
        shape = {"op": "cell_chem_from_shape", "at": "cell", "model": "curvature",
                 "vertex_set": "vertex", "beta": 0.5, "F0": 0.046, "rate": 1.0}
        i = c["schedule"].index("cell_mechanics")
        c["operators"] = c["operators"][:1] + CHEM + [shape] + c["operators"][1:]
        c["schedule"] = c["schedule"][:i] + CHEM_SCHED + ["cell_chem_from_shape"] + c["schedule"][i:]
        g = next(o for o in c["operators"] if o["op"] == "cell_grow")
        # GROWTH KEYED ON THE ACTIVATOR, which is the whole composition: `a_sw` is the switch and
        # `rho` the floor, so a cell grows where the pattern is red and creeps where it is not.
        g.update({"rate": 0.000866, "a_sw": 0.35, "hill": 4.0, "rho": 0.1,
                  "after_frame": 100, "conserve_amount": False})
    write(
        "turing_grow_divide",
        "the two composed: the Turing pattern drives where the tissue grows",
        "gate_00_spheroid",
        """# THE COMPOSITION IS THE POINT, and it is one parameter: `cell_grow.a_sw`. The activator is a
# per-cell field, `a_sw` is the switch on it and `rho` the floor, so a cell grows where the pattern
# is red and creeps where it is not. Neither operator knows about the other -- the coupling is that
# they read and write the same block, which is what the algebra is for.
#
# `cell_chem_from_shape[curvature]` closes the loop the other way: the surface's curvature feeds back
# into the reaction's F, so a bud that forms changes the chemistry that made it.
""",
        both,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
