"""Write `plotting.renderer` explicitly into every hand-written spec.

WHY A TOOL AND NOT A ONE-OFF. The renderer a spec gets was decided by four unrelated signals --
`plotting.panels`, the presence of a mesh set in the OUTPUT, the dimension, and whether the run went
through `-o generate` or `-o plot` -- and none of them appeared in the spec. `plexus.plot`
now resolves one key and prints its choice, but a default that has to be inferred is still a default
nobody can see by reading the file. This writes it down.

WHAT IT DOES NOT TOUCH: config/okuda. Those 1,374 specs are GENERATED by the discovery loop and have
no `plotting:` block at all; adding one would be churn the generator overwrites, and their default
(`vtk_mesh`, from the mesh set they all produce) is already the right answer.

ruamel round-trips, so the comments survive. Every file is re-parsed with plain yaml afterwards and
compared key-for-key against what it held before: the only permitted difference is the key this tool
adds. A spec whose comments carry the reasoning -- and in this repo most of them do -- must not lose
them to a mechanical edit.
"""
from __future__ import annotations

import glob
import io
import os
import sys

import math
import re

import yaml
from ruamel.yaml import YAML

SKIP_DIRS = ("config/okuda/",)


def implied(spec: dict) -> str:
    """The renderer this spec's data will imply, by the same rules `plot._resolve_renderer` uses."""
    pl = spec.get("plotting") or {}
    if isinstance(pl, dict) and pl.get("panels"):
        return "panels"
    ops = spec.get("operators") or []
    names = {str(o.get("op", "")) if isinstance(o, dict) else str(o) for o in ops}
    # BOTH NAMES. `seed_mesh` is registered with the alias `mesh_seed` and the corpus uses each
    # about half the time (1,042 / 1,184 occurrences), so matching one name silently mislabelled
    # every promotion spec -- 47 mesh runs that would have been handed the point renderer.
    if names & {"seed_mesh", "mesh_seed"}:
        return "vtk_mesh"
    if int((spec.get("general") or {}).get("dim", 2)) == 2:
        return "mpl2d"
    return "vtk_points"


def same(a, b) -> bool:
    """Equal, with floats compared by value rather than by their last bit.

    A round trip re-serialises 7.440476190476191e-07 as 7.44047619047619e-07 -- a relative change of
    1.3e-16, which is nothing physically and everything to `==`. Refusing on that would reject every
    generated spec while letting no real difference through, so the tolerance is 1e-12: far above
    float64 round-tripping and far below any edit a person would make on purpose.
    """
    if isinstance(a, float) or isinstance(b, float):
        try:
            return math.isclose(float(a), float(b), rel_tol=1e-12, abs_tol=1e-300)
        except (TypeError, ValueError):
            return False
    if isinstance(a, dict) and isinstance(b, dict):
        return set(a) == set(b) and all(same(a[k], b[k]) for k in a)
    if isinstance(a, list) and isinstance(b, list):
        return len(a) == len(b) and all(same(x, y) for x, y in zip(a, b))
    return a == b


def textual(raw: str, want: str) -> str | None:
    """Insert the key WITHOUT reserialising, for the files a round trip would damage.

    Two damage the round trip: a `plotting: {...}` flow mapping with comments inside it (ruamel
    drops those -- the galaxy specs keep the reason for every camera key there), and a file carrying
    a duplicate `descriptions:` block, where ruamel keeps the first and `safe_load` keeps the last,
    so a round trip would silently swap which caption survives. Editing the text touches neither.
    """
    m = re.search(r"^(?P<i>[ \t]+)renderer:[ \t]*\S+[ \t]*$", raw, re.M)
    if m:                                       # already there, block style: replace the value
        return raw[:m.start()] + f"{m.group('i')}renderer: {want}" + raw[m.end():]
    m = re.search(r"(?<=[{,] )renderer: \S+?(?=[,}])", raw)
    if m:                                       # already there, flow style
        return raw[:m.start()] + f"renderer: {want}" + raw[m.end():]
    m = re.search(r"^plotting:[ \t]*(#[^\n]*)?$", raw, re.M)
    if m:                                       # block style: a new line under it, two-space indent
        i = m.end()
        return raw[:i] + f"\n  renderer: {want}" + raw[i:]
    m = re.search(r"^plotting:[ \t]*\{", raw, re.M)
    if m:                                       # flow style: first entry inside the brace
        i = m.end()
        return raw[:i] + f"renderer: {want}, " + raw[i:]
    if re.search(r"^plotting:", raw, re.M):
        return None                             # some other shape -- do not guess
    return raw.rstrip("\n") + f"\nplotting: {{renderer: {want}}}\n"


def main(argv):
    apply = "--apply" in argv
    rt = YAML()
    rt.preserve_quotes = True
    rt.width = 4096                      # do NOT re-wrap long lines: that is a diff nobody asked for
    # DUPLICATE KEYS ARE ALREADY IN THE CORPUS. The auto-captioner appends a `descriptions:` block
    # and some specs carry two; `yaml.safe_load` keeps the last and says nothing, ruamel refuses the
    # file outright. Tolerating it here keeps this tool from being blocked by a defect it did not
    # cause -- and the round trip then writes ONE block, which is the repair.
    rt.allow_duplicate_keys = True
    changed = tally = skipped = 0
    fails = []
    for path in sorted(glob.glob("config/**/*.yaml", recursive=True)):
        if any(path.startswith(s) for s in SKIP_DIRS):
            continue
        raw = open(path).read()
        try:
            before = yaml.safe_load(raw)
        except Exception:
            continue
        if not isinstance(before, dict) or "general" not in before:
            continue
        tally += 1
        want = implied(before)
        pl = before.get("plotting")
        if isinstance(pl, dict) and str(pl.get("renderer", "")) == want:
            skipped += 1
            continue
        def check(out):
            """Nothing but the new key may have moved, and no comment may have been lost."""
            try:
                after = yaml.safe_load(out)
            except Exception as e:
                return f"no longer parses: {type(e).__name__}"
            if (after.get("plotting") or {}).get("renderer") != want:
                return "the key did not land"
            probe = dict(after)
            probe["plotting"] = {k: v for k, v in (after.get("plotting") or {}).items()
                                 if k != "renderer"}
            ref = dict(before)
            ref["plotting"] = {k: v for k, v in (before.get("plotting") or {}).items()
                               if k != "renderer"}
            if not same(probe, ref):
                return "content changed beyond plotting.renderer"
            if raw.count("#") != out.count("#"):
                return f"comment count {raw.count('#')} -> {out.count('#')}"
            return None

        # TEXT FIRST, ROUND TRIP ONLY AS A FALLBACK -- and the order matters more than it looks.
        # ruamel reserialises the WHOLE document to add one key, and on this corpus that is not a
        # neutral operation: it strips the alignment whitespace people put in flow mappings
        # (`{op: decay,   at: ...}`), re-wraps every caption paragraph, and on one spec emitted the
        # new key AFTER a section comment, so `# --- auto: video descriptions ---` ended up inside
        # the plotting block. 588 files, 5,749 deletions, to add 634 lines. Editing the bytes adds
        # exactly the line asked for and changes nothing else.
        out = textual(raw, want)
        why = check(out) if out else "no plotting: block this tool understands"
        if why:
            try:
                doc = rt.load(io.StringIO(raw))
                if "plotting" not in doc or doc["plotting"] is None:
                    doc["plotting"] = {}
                doc["plotting"]["renderer"] = want
                buf = io.StringIO()
                rt.dump(doc, buf)
                out = buf.getvalue()
                why = check(out)
            except Exception as e:
                why = f"{type(e).__name__}: {e}"
        if why:
            fails.append((path, why))
            continue
        changed += 1
        if apply:
            open(path, "w").write(out)
    print(f"{tally} hand-written specs   {changed} {'written' if apply else 'would change'}   "
          f"{skipped} already correct   {len(fails)} refused")
    for p, why in fails[:20]:
        print(f"  REFUSED {p}: {why}")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
