"""Regenerate `config/tissue/INDEX.md`: one row per spec, read from the specs themselves.

A DIRECTORY INDEX HAS TO BE GENERATED OR IT LIES. `AB_TISSUE_README.md` is prose and explains WHY
each run exists; it also went stale twice in one day -- it documented a run deleted two commits
earlier and said "THE EIGHT" for thirteen -- because a hand-written list is a second copy of the
directory and the two drift the moment one is edited. This reads the specs, so it cannot.

    PYTHONPATH=src python tools/tissue_index.py [--group tissue]
"""
import argparse
import glob
import os

import yaml

# WHAT EACH GROUP IS, keyed by filename prefix. The prefix is the only grouping the filesystem
# itself can express, which is why the specs were renamed to carry one.
GROUPS = [
    ("ab_",     "the apico-basal ladder, in order -- each rung adds one thing"),
    ("shape_",  "seed geometry: one hypothesis, several surfaces"),
    ("cycle_",  "the cell cycle as per-cell state"),
    ("apop",    "the okuda apoptosis series, re-seeded on a flat sheet"),
    ("",        "pre-existing okuda runs, left as they were found"),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--group", default="tissue")
    a = ap.parse_args()
    root = f"config/{a.group}"
    specs = {}
    for p in sorted(glob.glob(f"{root}/*.yaml")):
        s = yaml.safe_load(open(p)) or {}
        g = s.get("general", {}) or {}
        ops = [o.get("op") for o in (s.get("operators") or [])]
        seed = (s.get("seed") or [{}])[0]
        mech = next((o for o in (s.get("operators") or [])
                     if o.get("op") == "cell_mechanics"), {})
        specs[os.path.basename(p)[:-5]] = dict(
            frames=g.get("n_frames"), cells=seed.get("n_cells"),
            shape=seed.get("shape", "sphere"),
            model=mech.get("model", "default" if mech else "--"),
            sep=("frozen" if mech.get("sep_mu", None) == 0 else
                 "free" if mech.get("sep_mu") else "--"),
            ops=[o for o in ops if o not in ("cell_geometry", "topo_record")])
    used, lines = set(), ["# `config/tissue` -- index", "",
                          "Generated by `tools/tissue_index.py`; do not hand-edit.",
                          "Prose and reasons are in `AB_TISSUE_README.md`.", ""]
    for pre, blurb in GROUPS:
        names = [n for n in sorted(specs) if n.startswith(pre) and n not in used]
        if not names:
            continue
        used.update(names)
        lines += [f"## `{pre}*` -- {blurb}" if pre else f"## {blurb}", "",
                  "| spec | frames | cells | shape | mechanics | sep | operators |",
                  "|---|---|---|---|---|---|---|"]
        for n in names:
            d = specs[n]
            lines.append(f"| `{n}` | {d['frames']} | {d['cells']} | {d['shape']} | "
                         f"{d['model']} | {d['sep']} | {', '.join(d['ops'])} |")
        lines.append("")
    open(f"{root}/INDEX.md", "w").write("\n".join(lines) + "\n")
    print(f"{len(specs)} specs -> {root}/INDEX.md")


if __name__ == "__main__":
    main()
