"""diff oracle for regulate:connectionist -- the reference GeneNetworkConnectionist ODE.

GENERATED by _gen_gene_network_connectionist.py; do not hand-edit. Runs the shipped
jax_morph.control.GeneNetworkConnectionist (diffrax Dopri5, PIDController rtol=1e-4 atol=1e-6)
for 20 macro-steps of dt=1.0 on a homogeneous batch of 6 cells and writes the gene
trajectory g(0), g(dt), ..., g(20*dt). The Plexus spec config/atlas/gene_network_connectionist.yaml
integrates the IDENTICAL ODE from the IDENTICAL initial condition with regulate:connectionist.
"""
import json, os
import numpy as np
import jax, jax.numpy as jnp
import jax_morph as jxm
from jax_morph.control import GeneNetworkConnectionist
from jax_morph.core.state import StateFieldSpec, build_state_from_model

OUT_DIR = os.environ["OUT"]
SEED, N, HIDDEN, OUT, IN, NG = 20250731, 6, 2, 3, 2, 5
N_STEPS, DT = 20, 1.0

gene0  = np.array(json.loads(r'''[1.7869452689106105, 0.3941819567693617, 0.20563401882673552, 0.9866250879552911, 1.4251028808660415]'''), dtype=np.float64)
u_vec  = np.array(json.loads(r'''[0.15107255707685097, -0.5591667686625554]'''), dtype=np.float64)
W_gene = np.array(json.loads(r'''[[0.38521648935475494, 0.4374054252259725, -0.6990928762717888, 0.08976711483277322, 0.1589168809621553], [-0.038044226302965584, 0.21344554099041715, 0.016173528915322942, 0.0275433673425082, -0.39530291537067697], [0.1981855872624858, 0.6930483505339626, -0.0641086153224373, 0.8431536397378818, -0.4144875865744719], [0.18016012608150525, -0.49787412803549513, -0.5532294729556506, 0.15692072876041052, -0.08561993906429279], [0.16821294508905874, -0.44512919765112235, 0.829809680308377, -0.20021880545233584, -0.05370395584975083]]'''), dtype=np.float64)
W_in   = np.array(json.loads(r'''[[0.17303795748728978, 0.0341148522012284], [0.5903687041198714, 0.3237141941661136], [0.8798742446548456, 0.49385652203101454], [-0.19680769370561316, -0.22738923261626864], [0.18796637882090103, -0.310009361155414]]'''), dtype=np.float64)
b      = np.array(json.loads(r'''[0.5091374000074812, 0.10418919108619994, 0.2263471778268916, 0.5530646075725886, 0.13374424649997138]'''), dtype=np.float64)
gamma  = np.array(json.loads(r'''[0.11454240457935093, 0.10397731547159664, 0.09098023859797849, 0.13594272865927215, 0.09721191470344026]'''), dtype=np.float64)

u_spec = StateFieldSpec("u_drive", shape=(IN,))
o_spec = StateFieldSpec("gout", shape=(OUT,))
ctrl = GeneNetworkConnectionist(
    (u_spec,), (o_spec,), hidden_size=HIDDEN,
    W_gene=jnp.asarray(W_gene), W_in=jnp.asarray(W_in), b=jnp.asarray(b), gamma=jnp.asarray(gamma),
)
model = jxm.Model([ctrl])
State = build_state_from_model(model)


def seed_state():
    s = State.init_empty(capacity=N, n_space_dim=2, n_types=1)
    return s.update(
        alive=s.alive.at[:N].set(True),
        celltype=s.celltype.at[:N, 0].set(1.0),
        gene_hidden=s.gene_hidden.at[:N].set(jnp.asarray(gene0[:HIDDEN])),
        gout=s.gout.at[:N].set(jnp.asarray(gene0[HIDDEN:])),
        u_drive=s.u_drive.at[:N].set(jnp.asarray(u_vec)),
    )


def rollout():
    return jxm.simulate(model, seed_state(), n_steps=N_STEPS, dt=DT, history=True)


h1 = rollout()
h2 = rollout()

hid1, out1 = np.asarray(h1.gene_hidden), np.asarray(h1.gout)
hid2, out2 = np.asarray(h2.gene_hidden), np.asarray(h2.gout)
same = bool(np.array_equal(hid1, hid2) and np.array_equal(out1, out2))
if not same:
    raise SystemExit("ORACLE IS NOT DETERMINISTIC at a fixed input -- a differential test would "
                     "measure the reference's own noise. Stop here.")

gene = np.concatenate([hid1, out1], axis=-1)          # [T, N, NG] = concat([hidden, outputs])
udrive = np.asarray(h1.u_drive)
t = np.asarray(h1.t)

np.savez_compressed(
    os.path.join(OUT_DIR, "reference.npz"),
    t=t, gene=gene, gene_hidden=hid1, gout=out1, u_drive=udrive,
    gene0=gene0, u=u_vec, W_gene=W_gene, W_in=W_in, b=b, gamma=gamma,
)

# the input must stay a frozen snapshot across the whole rollout (the contract);
# a violation here would silently change what the Plexus side has to match.
u_frozen = bool(np.allclose(udrive, udrive[0]))
cell_spread = float(gene.std(axis=1).max())           # ~float32 noise for a homogeneous batch

summary = {
    "seed": SEED, "n_cells": N, "hidden_size": HIDDEN, "out_size": OUT, "in_size": IN,
    "n_gene": NG, "n_steps": N_STEPS, "dt": DT, "n_frames": int(gene.shape[0]),
    "deterministic_at_fixed_input": same,
    "u_frozen_across_rollout": u_frozen,
    "max_cell_spread": cell_spread,
    "gene0_cell0": gene[0, 0].tolist(),
    "gene_final_cell0": gene[-1, 0].tolist(),
    "gene_min": float(gene.min()), "gene_max": float(gene.max()),
}
with open(os.path.join(OUT_DIR, "summary.json"), "w") as f:
    json.dump(summary, f, indent=2)
print(json.dumps(summary, indent=2))

if not u_frozen:
    raise SystemExit("input drift detected -- u is not a frozen snapshot; the scenario is invalid.")

# --- one figure: cell-0 gene trajectories on a common scale -------------------------------- #
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(6.0, 3.6))
for i in range(NG):
    label = ("hidden " + str(i)) if i < HIDDEN else ("output " + str(i - HIDDEN))
    ax.plot(t, gene[:, 0, i], marker="o", ms=3, label=label)
ax.set_xlabel("t"); ax.set_ylabel("gene concentration")
ax.set_title("oracle: GeneNetworkConnectionist  dg/dt = sigma(W_gene g + W_in u + b) - gamma g")
ax.legend(fontsize=8, ncol=2)
fig.tight_layout()
fig.savefig(os.path.join(OUT_DIR, "reference.png"), dpi=130)
print("wrote reference.npz, summary.json, reference.png")
