#!/usr/bin/env python
"""minisite_section -- add the "Vertex + MPM" section to index.qmd, and copy its two clips.

    python minisite_section.py                    # insert (idempotent: replaces its own block)

WHY A SCRIPT AND NOT A HAND EDIT. The section carries the two runs' ACTUAL `spec_run.yaml`, which is
the site's convention -- every clip on the page opens the spec that produced it -- and a spec pasted by
hand is a spec that silently stops matching the run the next time either changes. This reads the specs
off disk, escapes them, and rewrites the block between two markers, so re-running it after a re-run
updates the page instead of duplicating it.
"""
from __future__ import annotations

import html
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
LOG = os.path.join(ROOT, "log", "okuda_ECM")
QMD = os.path.join(ROOT, "index.qmd")
GAL = os.path.join(ROOT, "gallery")
# THE RENDERED SITE IS COMMITTED, and quarto is not installed in this container. `index.qmd` is the
# source of truth and stays so; `docs/index.html` is patched with the EQUIVALENT block so the page goes
# live without a render, and the next `quarto render` reproduces it rather than changing it. The two
# differences quarto makes to this markup are mechanical and applied here: `class="anchored"` on the
# heading, and `&#x27;` normalised back to a literal apostrophe inside the spec blocks.
DOCS = os.path.join(ROOT, "docs", "index.html")
DOCS_GAL = os.path.join(ROOT, "docs", "gallery")

BEGIN = "<!-- BEGIN vertex-mpm (generated by discovery_okuda/ops/minisite_section.py) -->"
END = "<!-- END vertex-mpm -->"
# The SECOND row of the Vertex + Turing section, which is a different experiment in the same
# section rather than a section of its own: same shell, same RD machinery, one more field.
BEGIN2 = ("<!-- BEGIN vertex-turing-second-field "
          "(generated by discovery_okuda/ops/minisite_section.py) -->")
END2 = "<!-- END vertex-turing-second-field -->"
# The name this block had while the row was apoptosis only. Kept so the one already committed to
# `docs/index.html` can be found and removed rather than left behind as a second, stale row -- and
# because a marker that says "death" over a row about inhibition is the same defect as a comment
# that has stopped describing its code.
BEGIN2_OLD = "<!-- BEGIN vertex-turing-death (generated by discovery_okuda/ops/minisite_section.py) -->"
END2_OLD = "<!-- END vertex-turing-death -->"
# The THIRD block: the three-entity model -- spheroid, basement membrane, matrix -- which is the
# subject of `discovery_okuda/note_spheroid_bm_ecm.pdf` and of the whole `05` ladder. It goes after
# Vertex + MPM, because it is what that interface was built for.
BEGIN3 = ("<!-- BEGIN spheroid-bm-ecm "
          "(generated by discovery_okuda/ops/minisite_section.py) -->")
END3 = "<!-- END spheroid-bm-ecm -->"
# The THIRD row of Vertex + Turing: what one operator graph does at two chemistries, and what it
# does with the purse-string taken out. Its own block, because "second field" is not what it is.
BEGIN4 = ("<!-- BEGIN vertex-turing-shapes "
          "(generated by discovery_okuda/ops/minisite_section.py) -->")
END4 = "<!-- END vertex-turing-shapes -->"
# The FOURTH row: the same growth-driven composition at two reaction rates. Between the shapes row
# and the two-morphogen row, because it is still one morphogen.
BEGIN5 = ("<!-- BEGIN vertex-turing-rate "
          "(generated by discovery_okuda/ops/minisite_section.py) -->")
END5 = "<!-- END vertex-turing-rate -->"
LOG_OKUDA = os.path.join(ROOT, "log", "okuda")

# The heading this section goes after, and its new name. The old one said "Turing x vertex"; the page
# now has two vertex-model couplings on it, so both are named the same way round.
ANCHOR_OLD = "<h3>Turing × vertex — patterning &amp; shaping a growing tissue</h3>"
ANCHOR_NEW = "<h3>Vertex + Turing — patterning &amp; shaping a growing tissue</h3>"
# The section Vertex + MPM now follows: the interface reads better once MLS-MPM has been introduced.
MPM_SECTION = "<h3>Continuum mechanics — MLS-MPM</h3>"


def _run_dir(name, need=()):
    """A run's directory, live or archived, preferring one that HOLDS the files `need` names.

    Rounds 1-22 were moved into `log/okuda/_archive_r001-r022_<date>/` on 12 August, which is why
    two rows of the Vertex + Turing section quietly stopped rebuilding: the runs had not been
    deleted, they had been filed. Their artefacts -- `traj.npz`, `diag.json`, the `vtk_*` clips --
    moved with them, so a card only needs to know where to look.

    `need` exists because the discovery loop RE-USES slot names: a fresh `r013_05` appears in
    `log/okuda/` for a different simulation, carrying no `vtk_*` clips, and taking it on name
    alone dropped four cards off the page at once. When `need` is given, the first candidate
    holding all of it wins -- live, then archives newest-named first -- so the card keeps both
    the clip and the `spec_run.yaml` of the run the clip was rendered from, not a namesake's.
    """
    import glob as _glob
    live = os.path.join(LOG_OKUDA, name)
    cands = ([live] if os.path.isdir(live) else []) + \
        sorted(_glob.glob(os.path.join(LOG_OKUDA, "_archive_*", name)), reverse=True)
    for c in cands:
        if all(os.path.exists(os.path.join(c, f)) for f in need):
            return c
    return cands[0] if cands else live


def _find_block(s, name):
    """(start, end) of the block called `name`, whatever path its marker names -- or None.

    Matched on the NAME alone: the generator's own path used to be part of the marker string, so
    moving this file made every block on the page unrecognisable and each run appended another
    copy of it. Fourteen copies of one section is what that cost.
    """
    m = re.search(r"<!-- BEGIN " + re.escape(name) + r" \(generated by [^)]*\) -->", s)
    if not m:
        return None
    e = s.find(f"<!-- END {name} -->", m.end())
    if e < 0:
        return None
    return m.start(), e + len(f"<!-- END {name} -->")


def _content_box(src, x0, wid, hei, n=9, thresh=14, skip_top=0.0, skip_bot=0.0, y0=0):
    """The bounding box of everything that is not background, in a REGION of the frame.

    Both panels of these movies are drawn on black with matplotlib's own margins around them, and
    the margins are not symmetric -- the 3D axes sit left of centre and the 2D section right of it,
    which is exactly what a viewer sees as "the first half is a bit to the left and the second a bit
    to the right". Centring is therefore a property of the CONTENT, not of the frame, and it has to
    be measured rather than nudged.

    Sampled over `n` frames and unioned, because the content MOVES: a box measured on one frame
    crops away the part of the run that happens later. Threshold on the max channel, so a dim strand
    counts as content and JPEG-ish ringing around the border does not.
    """
    import glob
    import tempfile
    import numpy as _np
    import matplotlib.image as _mpimg
    d = tempfile.mkdtemp(prefix="mscrop_")
    subprocess.check_call([_exe("ffmpeg"), "-y", "-loglevel", "error", "-i", src,
                           "-vf", "select='not(mod(n\\," + str(max(1, _nframes(src) // n))
                           + "))'",
                           "-vsync", "vfr", os.path.join(d, "f%03d.png")])
    xs0, xs1, ys0, ys1 = wid, 0, hei, 0
    for f in sorted(glob.glob(os.path.join(d, "*.png"))):
        a = _mpimg.imread(f)
        # `y0` as well as `x0`, because a panel is not always in the top row: the four-panel
        # proteolysis movie has two, and a box measured from row 0 for a bottom-row panel is a box
        # around the panel above it.
        a = (a[:, :, :3].max(axis=2)
             * (255 if a.dtype.kind == "f" else 1))[y0:y0 + hei, x0:x0 + wid]
        # THE PRINTED LABEL IS NOT CONTENT. Every one of these movies stamps the run name, the frame
        # and the cell count in the top-left corner, in white on black -- so a bounding box that
        # measures brightness puts the box around the TEXT as well as around the tissue, and the
        # crop that follows keeps the text and shrinks the subject. `skip_top` is the fraction of
        # the panel the label occupies; measured below it, the box is the tissue's.
        if skip_top:
            a = a[int(skip_top * hei):]
        # AND THE SCALE BAR IS NOT CONTENT EITHER. The okuda movies draw a white rule and its length
        # in the bottom margin of every panel; a box that includes it is a box around the bar, and
        # the square crop that follows then keeps the bar and shrinks the tissue.
        if skip_bot:
            a = a[:max(1, a.shape[0] - int(skip_bot * hei))]
        m = a > thresh
        if not m.any():
            continue
        cols, rows = _np.nonzero(m.any(0))[0], _np.nonzero(m.any(1))[0]
        xs0, xs1 = min(xs0, int(cols[0])), max(xs1, int(cols[-1]))
        ys0, ys1 = min(ys0, int(rows[0])), max(ys1, int(rows[-1]))
    import shutil as _sh
    _sh.rmtree(d, ignore_errors=True)
    if xs1 <= xs0 or ys1 <= ys0:
        return wid // 2, hei // 2, min(wid, hei)
    return (xs0 + xs1) // 2, (ys0 + ys1) // 2, max(xs1 - xs0, ys1 - ys0)


def _nframes(src):
    out = subprocess.check_output([_exe("ffprobe"), "-v", "error", "-select_streams", "v",
                                   "-count_frames", "-show_entries", "stream=nb_read_frames",
                                   "-of", "csv=p=0", src]).decode().strip()
    return max(1, int(out.split(",")[0]))


def split_concat(src, dst, recentre=True, skip_top=0.0):
    """Cut the two-panel movie in half and play the halves in SEQUENCE: 3D first, then the section.

    ONE CLIP PER RUN, NOT TWO. A gallery card is a square block, and the movie is 2:1 -- shown whole it
    letterboxes to a third of the card's height and neither panel is legible. Two cards per run would fit
    but would spend six of the row's slots on three runs, and the confinement SERIES is the thing the row
    exists to show. Concatenating in time gives one square card per run that shows both views.

    CUT, NOT RE-RENDERED. The halves are the same pixels the movie has, so the page cannot end up
    disagreeing with the artefact it was made from.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    half = (w // 2) - (w // 2) % 2
    ax, ay, aw = 0, 0, half
    bx, by, bw = w - half, 0, half
    side = h
    if recentre:
        # EACH HALF CENTRED ON ITS OWN CONTENT, and both cropped to ONE size, because `concat`
        # requires it. The window is the larger of the two contents plus a fifth, so neither panel
        # is cut and the smaller one is not blown up past the other.
        cxa, cya, sa = _content_box(src, 0, half, h, skip_top=skip_top)
        cxb, cyb, sb = _content_box(src, w - half, half, h, skip_top=skip_top)
        cya += int(skip_top * h); cyb += int(skip_top * h)      # back into full-frame rows
        side = min(h, half, int(1.2 * max(sa, sb)))
        side -= side % 2
        ax = min(max(cxa - side // 2, 0), half - side)
        ay = min(max(cya - side // 2, 0), h - side)
        bx = (w - half) + min(max(cxb - side // 2, 0), half - side)
        by = min(max(cyb - side // 2, 0), h - side)
        aw = bw = side
        print(f"[minisite]   recentred: {side}x{side} windows at ({ax},{ay}) and ({bx},{by}) "
              f"of {w}x{h}", flush=True)
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-filter_complex",
           f"[0:v]crop={aw}:{side}:{ax}:{ay}[a];[0:v]crop={bw}:{side}:{bx}:{by}[b];"
           f"[a][b]concat=n=2:v=1[o]",
           "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "21", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg split+concat failed for {dst}")



def panels_concat(src, dst, panels, skip_top=0.0, skip_bot=0.0, pad=1.16, side=460):
    """Cut a grid movie into named panels and play them in SEQUENCE, each square on its own content.

    A GRID DOES NOT SURVIVE A GALLERY CARD. These runs are drawn to be READ -- three or four views
    of the same frame side by side, at a size that suits a page -- and a card is one square block,
    so the whole grid arrives at a third or a quarter of its linear size and the fibres, which are
    one pixel wide to begin with, arrive at none. Played one after another, each panel gets the
    whole card.

    `panels` is a list of (x0, y0, w, h) in FRACTIONS of the frame, in the order they should play.
    Each is cropped to a square window centred on what is drawn INSIDE it -- panels of these movies
    are not filled evenly, and one of 04d's three is a sphere in the corner of its quadrant with an
    inset beside it -- and all the windows are then made the same size, because `concat` requires
    it. The window is the largest content plus `pad`, so the smallest panel is not blown up to fill
    a card the others earned.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    boxes = []
    for (fx, fy, fw, fh) in panels:
        x0, y0 = int(fx * w), int(fy * h)
        pw, ph = int(fw * w), int(fh * h)
        cx, cy, sz = _content_box(src, x0, pw, ph, y0=y0, skip_top=skip_top, skip_bot=skip_bot)
        boxes.append((x0, y0, pw, ph, x0 + cx, y0 + int(skip_top * ph) + cy, sz))
    # THE MARGINS BIND THE WINDOW, NOT ONLY THE MEASUREMENT. Skipping the text while measuring puts
    # the box around the right thing and then the square window, being larger, reaches back over the
    # label anyway -- which is how the first cut of 04d came out with the run name still burnt into
    # its first sequence. The window is capped at the panel MINUS both margins and clamped between
    # them, so a printed label cannot re-enter through the padding.
    tpx = int(skip_top * min(b[3] for b in boxes))
    bpx = int(skip_bot * min(b[3] for b in boxes))
    side = min(min(b[2] for b in boxes), min(b[3] for b in boxes) - tpx - bpx,
               int(pad * max(b[6] for b in boxes)))
    side -= side % 2
    parts, labels = [], []
    for n, (x0, y0, pw, ph, cx, cy, _sz) in enumerate(boxes):
        x = min(max(cx - side // 2, x0), x0 + pw - side)
        y = min(max(cy - side // 2, y0 + tpx), y0 + ph - bpx - side)
        x, y = max(0, min(x, w - side)), max(0, min(y, h - side))
        parts.append(f"[0:v]crop={side}:{side}:{x}:{y}[p{n}]")
        labels.append(f"[p{n}]")
        print(f"[minisite]   panel {n}: {side}x{side} at ({x},{y}) of {w}x{h}", flush=True)
    fc = ";".join(parts) + ";" + "".join(labels) + f"concat=n={len(boxes)}:v=1[o]"
    # SCALED TO THE PAGE'S OWN SIZE. The VTK sources are 1,568 px square; concatenating four of
    # their quadrants unscaled put a single card at 17.8 MB, which is more than the rest of the
    # gallery put together.
    fc = fc.replace("[o]", "[c]") + f";[c]scale={side}:{side}:flags=lanczos[o]"
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-filter_complex", fc,
           "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "24",
           "-movflags", "+faststart", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg panels+concat failed for {dst}")


def vtk_sequence(run_dir, dst, side=460, kb_seconds=5.0, crop=24, kinds=("evolve", "kburns")):
    """The VTK sequence as one clip: without the mesh, then with it, each grown then turned.

    FOUR MOVEMENTS, ONE CARD. `vtk_render --seq 3` writes evolve/kburns x nomesh/mesh. Played in
    that order the card answers both questions a shape raises -- what it did (time moves, camera
    still) and what it is (camera moves, time still) -- first as a surface and then as cells.

    THE ROTATION IS RETIMED AND THE GROWTH IS NOT. Four clips at their own pace are 46 s, twice
    what any other card on the page runs; and of the four, the two turns are the redundant pair --
    the same revolution twice, once per style. Compressing those to `kb_seconds` each and leaving
    the growth alone puts the card at 20 s without touching the part that only happens once.

    THE LABEL IS CROPPED, not disabled: `vtk_render` stamps "<run> <style>" in the top-left, rows
    5-20 of an 896 px frame, and the page writes its own captions. `crop` is taken off all four
    sides so the frame stays square; at full zoom that costs the tissue about 3% of its height,
    which is the price of not having a run name burnt into a gallery card.
    """
    ff = _exe("ffmpeg")
    # `kinds` drops a movement for the runs that do not need it: a turntable earns its place on a
    # shape with arms pointing at the lens, and adds nothing to a sphere that shrinks.
    parts = [(k, st) for st in ("nomesh", "mesh") for k in ("evolve", "kburns") if k in kinds]
    srcs = [os.path.join(run_dir, f"vtk_{k}_{st}.mp4") for k, st in parts]
    missing = [os.path.basename(p) for p in srcs if not os.path.exists(p)]
    if missing:
        print(f"[minisite] {os.path.basename(run_dir)}: missing {missing} -- clip not rebuilt")
        return False
    w, h = _size(srcs[0])
    c = min(crop, (min(w, h) - 2) // 2)
    fc, labels = [], []
    for n, ((kind, _st), src) in enumerate(zip(parts, srcs)):
        # `setpts` before `fps`: retime first, then resample, or the frames are dropped at the old
        # rate and the clip stutters.
        rt = ""
        if kind == "kburns":
            dur = float(subprocess.check_output(
                [_exe("ffprobe"), "-v", "error", "-show_entries", "format=duration",
                 "-of", "csv=p=0", src]).decode().strip())
            rt = f"setpts={kb_seconds / dur:.5f}*PTS,"
        fc.append(f"[{n}:v]crop={w - 2 * c}:{h - 2 * c}:{c}:{c},{rt}fps=25,"
                  f"scale={side}:{side}:flags=lanczos,setsar=1[v{n}]")
        labels.append(f"[v{n}]")
    cmd = [ff, "-y", "-loglevel", "error"]
    for src in srcs:
        cmd += ["-i", src]
    cmd += ["-filter_complex",
            ";".join(fc) + ";" + "".join(labels) + f"concat=n={len(parts)}:v=1[o]",
            "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "26",
            "-movflags", "+faststart", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg vtk sequence failed for {dst}")
    print(f"[minisite]   {os.path.basename(run_dir)}: {len(parts)} VTK clips -> {side}x{side}, "
          f"{_nframes(dst)} frames")
    return True


def evolve_then_kburns(run_dir, dst, panel="left", pad=1.26, skip_top=0.09, skip_bot=0.14):
    """The run through time, then the finished specimen turned on the spot -- one clip.

    TWO MOVIES THAT ANSWER DIFFERENT QUESTIONS. `movie.mp4` holds the camera still and moves
    through time, which is the only way growth reads as growth (a per-frame autofit rescaled the
    box 4.6x over a run and hid it). `kburns.mp4` holds time still at the last frame and moves the
    camera, which is the only way an arm pointing at the lens reads as an arm. A card that plays
    one of them is missing the other, and side by side they are two small movies; in sequence they
    are the run and then its specimen, at one size.

    BOTH HALVES ARE CROPPED OFF THEIR OWN TEXT. The Ken Burns render stamps the run name and a
    scale bar -- correct for a figure, wrong for a card whose caption the page writes -- so it is
    cropped square about its content between the same margins the evolve half uses.

    ONE SIZE is the difficulty `concat` imposes: the Ken Burns half is scaled to whatever square
    the evolve half measured, so the tissue stays the size the rest of the row draws it.
    """
    import shutil as _sh
    import tempfile
    mv = os.path.join(run_dir, "movie.mp4")
    kb = os.path.join(run_dir, "kburns.mp4")
    name = os.path.basename(run_dir)
    ready = os.path.exists(kb)
    if ready:
        try:
            _nframes(kb)
        except Exception:
            ready = False
    if not ready:
        print(f"[minisite] {name}: kburns.mp4 missing or still being written -- evolve only")
        crop_panel(mv, dst, panel=panel, pad=pad, skip_top=skip_top, skip_bot=skip_bot)
        return False
    d = tempfile.mkdtemp(prefix="evkb_")
    a, b = os.path.join(d, "a.mp4"), os.path.join(d, "b.mp4")
    crop_panel(mv, a, panel=panel, pad=pad, skip_top=skip_top, skip_bot=skip_bot)
    # MEASURED, NOT GUESSED: in a 770-px Ken Burns frame the run label occupies rows 104-119 and
    # the scale bar 629-654, so the window has to start below 0.156 of the height and end above
    # 0.185 from the bottom. The first pass used 0.08/0.12 and kept the label.
    panels_concat(kb, b, [(0, 0, 1.0, 1.0)], skip_top=0.157, skip_bot=0.186, pad=1.02)
    side = _size(a)[0]
    na, nb = _nframes(a), _nframes(b)
    ff = _exe("ffmpeg")
    # `setsar=1` and one fps on both: concat refuses streams that disagree on either, and the two
    # renderers never had to agree.
    fc = (f"[0:v]fps=20,scale={side}:{side},setsar=1[a];"
          f"[1:v]fps=20,scale={side}:{side},setsar=1[b];[a][b]concat=n=2:v=1[o]")
    cmd = [ff, "-y", "-loglevel", "error", "-i", a, "-i", b, "-filter_complex", fc,
           "-map", "[o]", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "24", dst]
    ok = subprocess.call(cmd) == 0 and os.path.exists(dst)
    _sh.rmtree(d, ignore_errors=True)
    if not ok:
        sys.exit(f"ffmpeg evolve+kburns concat failed for {dst}")
    print(f"[minisite]   {name}: evolve {na} frames + ken burns {nb}, {side}x{side}")
    return True


def crop_panel(src, dst, panel="left", skip_top=0.09, skip_bot=0.14, pad=1.20):
    """Keep the LEFT panel only, as a square window centred on what is drawn in it.

    THE MOVIE IS A CONTACT SHEET, NOT A CLIP. `log/okuda/*/movie.mp4` is drawn for reading a run:
    two views side by side, each labelled with its elevation, each with a scale bar, and a section
    inset in the corner. A gallery card is one square block, so the page takes one panel -- the side
    view -- and the crop has to be measured rather than guessed, because the tissue GROWS: a window
    fitted to the first frame cuts the last one off.

    `skip_top` / `skip_bot` are the fractions of the panel its printed text occupies -- the "side
    elev 18" label above and the scale bar below. Measured between them, the box is the tissue's;
    the window is then clamped to stay inside those margins, so no frame of the result carries a
    caption the page has not written itself.

    `panel="right"` takes the top view instead, for a run whose interesting face is on top. THE BOX
    IS STILL MEASURED ON THE LEFT PANEL, and deliberately: the right one carries the section-ring
    inset in its bottom corner, which is bright, is not the tissue, and drags any box measured
    around it out to the frame edge. Both panels draw the same tissue at the same axes scale and
    the same centre, so the left panel's window is the right one's window plus the offset.
    """
    ff = _exe("ffmpeg")
    w, h = _size(src)
    half = (w // 2) - (w // 2) % 2
    top, bot = int(skip_top * h), int(skip_bot * h)
    cx, cy, sz = _content_box(src, 0, half, h, skip_top=skip_top, skip_bot=skip_bot)
    cy += top
    side = min(half, h - top - bot, int(pad * sz))
    side -= side % 2
    x = min(max(cx - side // 2, 0), half - side)
    y = min(max(cy - side // 2, top), h - bot - side)
    if panel == "right":
        x += w - half
    print(f"[minisite]   panel crop: {side}x{side} at ({x},{y}) of {w}x{h}", flush=True)
    cmd = [ff, "-y", "-loglevel", "error", "-i", src, "-vf", f"crop={side}:{side}:{x}:{y}",
           "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "20", dst]
    if subprocess.call(cmd) != 0 or not os.path.exists(dst):
        sys.exit(f"ffmpeg panel crop failed for {dst}")


def _exe(name):
    """Next to the interpreter, not on PATH -- the conda env ships ffmpeg but the shell does not see it."""
    p = os.path.join(os.path.dirname(sys.executable), name)
    if os.path.exists(p):
        return p
    import shutil as _sh
    return _sh.which(name) or name


def _size(path):
    out = subprocess.check_output([_exe("ffprobe"), "-v", "error", "-select_streams", "v",
                                   "-show_entries", "stream=width,height",
                                   "-of", "csv=p=0", path]).decode().strip()
    w, h = (int(v) for v in out.split(",")[:2])
    return w, h


def card(video, name, spec_path, cap):
    spec = html.escape(open(spec_path).read().rstrip(), quote=False).replace("'", "&#x27;")
    return f"""  <figure class="sim-card">
    <video src="gallery/{video}" autoplay loop muted playsinline preload="metadata"></video>
    <figcaption>
      <span class="sim-name" tabindex="0">{name}<span class="sim-spec"><pre>{spec}</pre></span></span>
      <span class="sim-cap">{cap}</span>
    </figcaption>
  </figure>"""



def replace_card(video, name, spec_path, cap, files=(), new_video=None):
    """Rewrite ONE hand-written gallery card in place, matched on the clip it plays.

    The generated block below owns the Vertex + MPM section; the cards in the older sections are
    part of the page's own prose and are not in it. Rewriting one by hand would break the same rule
    this file exists to enforce -- that a card's spec is READ from the run that produced it rather
    than pasted -- so it is done here, keyed on the video filename, which is the one thing about a
    card that does not change when its content does.
    """
    # THE CLIP A CARD PLAYS AND THE CLIP IT IS FOUND BY ARE NOT THE SAME QUESTION. Two cards on
    # this page play `tyssue_grow_divide.mp4` -- the vertex model's own, and the growth phase of the
    # Turing section -- so overwriting that FILE changes both, and the second one's spec then
    # describes a run its clip no longer shows. A new card gets a new filename and only the card
    # named here is repointed.
    blk = card(new_video or video, name, spec_path, cap)
    for path, rendered in files:
        if not os.path.exists(path):
            continue
        s = open(path).read()
        i = s.find(f'<video src="gallery/{video}"')
        if i < 0:
            print(f"[minisite] {os.path.basename(path)}: no card plays {video} -- not replaced")
            continue
        # `<figure` AND NOT `<figure class="sim-card">`. Quarto renders the class list as
        # `sim-card figure`, so matching the bare class found nothing in the rendered page, `rfind`
        # returned -1, and the "replacement" was appended at the END OF THE FILE -- a second card
        # four thousand lines below the gallery it belongs to, with the original still in place.
        a = s.rfind("<figure", 0, i)
        b = s.index("</figure>", i) + len("</figure>")
        out = blk if not rendered else blk.replace("&#x27;", "'")
        open(path, "w").write(s[:a] + out.lstrip() + s[b:])
        print(f"[minisite] {os.path.basename(path)}: card for {video} replaced ({name})")


def build(runs):
    """One row: the interface under the three loadings it has to survive -- press, drag, breach.

    SHORT, LIKE THE REST OF THE PAGE. The first version of this section ran to 1,200 characters of
    prose against 140-400 everywhere else, and 400-character captions against 40-160: it read as a
    note rather than as a card. What the loadings mean belongs in the run's spec, which every card
    already opens; the caption's job is the one number that says whether it worked.
    """
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    return f"""{BEGIN}
<h3>Vertex + MPM</h3>
<p class="opk">Two Levels, two solvers, one interface: a <b>triangulated surface</b> with mass and
springs, pressed into a <b>block of MPM material</b> and coupled particle-to-face, so the reaction
returns to the mesh and not only to the material. Three loadings — <b>press</b>, <b>drag</b>,
<b>breach</b>. Each clip plays the 3D view, then a cross-section.</p>
<p class="opk-ref">Reference — contact:
<a href="https://doi.org/10.1016/j.cma.2015.04.005">ICFEMP, Chen et&nbsp;al. (2015)</a>, chosen over
grid-node coupling (<a href="https://doi.org/10.1016/j.cma.2011.07.014">Lian et&nbsp;al. 2011</a>),
which needs mesh and grid cells of a size ours are not; solid:
<a href="https://doi.org/10.1145/3197517.3201293">MLS-MPM, Hu et&nbsp;al. (2018)</a>; surface: the
vertex mesh of
<a href="https://www.nature.com/articles/s41598-018-20678-6">Okuda et&nbsp;al. (2018)</a>. Rig and
operators ours (<code>discovery_okuda/ops</code>).</p>
<div class="sim-gallery g3">
{cards}
</div>
{END}"""


def _measured(run):
    """The run's own `metrics.json`, so a number in a caption is a number the run reported.

    The same rule as the specs: the page quotes runs, and a quantity typed by hand is one that stops
    being true the next time the run changes without anybody noticing.
    """
    return json.load(open(os.path.join(LOG, run, "metrics.json")))


def build2(runs):
    """The second row of Vertex + Turing: two Turing fields, one growing the tissue and one killing
    cells in it. No heading of its own -- it is the same section with one more field in it."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    return f"""{BEGIN2}
<div class="sim-gallery g3">
{cards}
</div>
{END2}"""


def build5(runs):
    """Vertex + Turing, fourth row: one composition, two reaction rates."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    return f"""{BEGIN5}
<div class="sim-gallery g3">
{cards}
</div>
{END5}"""


def build4(runs):
    """Vertex + Turing, third row: the shapes one composition makes."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    return f"""{BEGIN4}
<div class="sim-gallery g3">
{cards}
</div>
{END4}"""


def build3(runs, runs2=()):
    """Spheroid + basement membrane + matrix, and the second row when there is one to show."""
    cards = "\n".join(card(v, n, sp, c) for _, v, n, sp, c in runs)
    row2 = "" if not runs2 else f"""
<p class="opk">And with a random source rather than a cap \u2014 arrested, then not:</p>
<div class="sim-gallery g3">
{chr(10).join(card(v, n, sp, c) for _, v, n, sp, c in runs2)}
</div>"""
    return f"""{BEGIN3}
<h3>Spheroid + basement membrane + extracellular matrix</h3>
<p class="opk">Cells grow a spheroid, deform its basement membrane, and interact with the surrounding matrix. At the lowest level, these interactions are governed by proteases, integrins and myosins dynamics.</p>
<p class="opk-ref">Reference — load path,
<a href="https://doi.org/10.1083/jcb.104.3.611">Keene et&nbsp;al. (1987)</a>; adhesions are clusters
at ~555&nbsp;nm, <a href="https://doi.org/10.1002/bies.201600123">Changede &amp; Sheetz (2017)</a>;
protease network, <a href="https://doi.org/10.1074/jbc.M403627200">Karagiannis &amp; Popel
(2004)</a>, with the inhibitor held in the matrix rather than dissolved in it,
<a href="https://doi.org/10.1074/jbc.M000907200">Yu et&nbsp;al. (2000)</a>. Note:
<code>discovery_okuda/note_spheroid_bm_ecm.pdf</code>.</p>
<div class="sim-gallery g3">
{cards}
</div>{row2}
{END3}"""


def main():
    sh, br = _measured("03f_mesh_shear"), _measured("03g_mesh_breach")
    pr = _measured("03_mesh_contact")
    # A NEW CLIP GETS A NEW FILENAME. `vertex_mpm_free.mp4` was named for the
    # frictionless control it once played; when this card was repointed at a different
    # run under the same name, every browser that had the page open kept serving the
    # OLD bytes from cache and the swap looked like it had not happened. The name also
    # now says what the card says.
    R3 = [
        # A NEW CLIP GETS A NEW FILENAME. `vertex_mpm_free.mp4` was named for the frictionless
        # control it once played; when this card was repointed at a different run under the same
        # name, every browser that had the page open kept serving the OLD bytes from cache and the
        # swap looked like it had not happened. The name also now says what the card says.
        ("03_mesh_contact", "vertex_mpm_press", "press",
         f"a free block, indented and released. {pr['contacts_max']} particles in contact at the "
         f"deepest; momentum balances to {pr['momentum_residual_max']:.1e} of the applied force, "
         f"and friction cuts the slip "
         f"{pr['slip_frictionless'] / pr['slip_friction']:.1f}-fold against \u03bc = 0"),
        ("03f_mesh_shear", "vertex_mpm_shear", "drag",
         f"pressed {sh['indent_cells']:.1f} cells in, then dragged {sh['drag_box_units']:.2f} box "
         f"units at that depth over a pinned base: it ploughs and shears. Von Mises, because a "
         f"drag changes shape at constant volume"),
        ("03g_mesh_breach", "vertex_mpm_breach", "breach",
         f"closed on all four sides and nearly incompressible, so the matrix leaves through the "
         f"hole: a plug {br['plug_above_surface_cells']:.1f} cells proud of a plate that has "
         f"descended {br['indent_cells']:.1f}"),
    ]
    def _spec(d):
        """`spec_run.yaml` where the engine wrote one, `spec.yaml` where the rig did.

        The rigs (`test_03`, `test_04`) write their own `spec.yaml`, the `06` three-body runs write
        a `what.yaml`; only runs that went through `run_ecm.run` leave a `spec_run.yaml`.
        Hard-coding the latter is why the live page opened
        `30_epi2_soft_E5`'s spec under the interface clip -- a spec belonging to a different run
        entirely, which is the one thing the site's convention exists to prevent.
        """
        for nm in ("spec_run.yaml", "spec.yaml", "what.yaml"):
            q = os.path.join(LOG, d, nm)
            if os.path.exists(q):
                return q
        # NO CARD, RATHER THAN A CARD WITHOUT ITS SPEC. The rule holds either way -- what changed is
        # that one run still in flight no longer kills the whole regeneration. A run writes its
        # spec last, so "movie ready, spec not yet" is a state this script meets routinely.
        print(f"[minisite] {d}: no spec beside it yet -- card skipped (a clip on the page must "
              f"open the spec that made it)")
        return None

    runs = [(d, f"{v}.mp4", lbl, _spec(d), cap) for d, v, lbl, cap in R3]
    missing = [r for r, *_ in runs if not os.path.exists(os.path.join(LOG, r, "movie.mp4"))]
    if missing:
        sys.exit(f"no movie.mp4 for {missing} -- run them before writing the page")

    os.makedirs(GAL, exist_ok=True)
    for d, v, *_ in runs:
        src = os.path.join(LOG, d, "movie.mp4")
        split_concat(src, os.path.join(GAL, v))
        print(f"[minisite] gallery/{v} <- {d}/movie.mp4  "
              f"({os.path.getsize(os.path.join(GAL, v)) / 1e6:.1f} MB, 3D then section)")

    # ---- the Vertex + Turing second row: division AND death, from two independent RD fields ----
    # WHICH THREE, AND WHY NOT THE OTHER TWO. The sweep has five runs; `tsd_cap10` and `tsd_cap25`
    # lost the pattern -- both species end up high in every cell, the shell renders as a flat
    # magenta ball and neither growth spots nor death patches can be told apart on it (cap10's own
    # summary reports n_spots_final 0 and red_frac_final 0.0). A clip that shows nothing is not a
    # third point of a sweep, so the row is the three runs whose pattern survived.
    # (run, clip, label, which panel of the two-view movie). `sc_antiphase` is the ONE-field
    # control and its death network is drawn on the pole, so the top view is the one that shows it;
    # the two-field runs are read from the side like every other clip on the page.
    R2 = [
        ("tsd_max", "turing_death_v5", "cell death", "left"),
        ("sc_antiphase", "turing_antiphase_v5", "one field, in antiphase", "right"),
    ]
    def _cap2(run):
        s = json.load(open(os.path.join(LOG_OKUDA, run, "diag.json")))["summary"]
        # SHORT. Each caption is one measured number and one sentence about what the clip shows;
        # the mechanism is in the paragraph above the row and does not need repeating three times.
        extra = {
            # NAMED, not lower-cased: `B` is the second Gray-Scott species, so the sentence is
            # reworded to open on an ordinary word instead of demoting the species to "b".
            "tsd_max": "the second field marks cells to die instead, from frame 180 — under half "
                       "the cells the inhibited run keeps, from the same growth law",
            "sc_antiphase": "one field: death fires where growth's own chemical is low, so it can "
                            "only land between the spots. Top view, where the network is",
        }[run]
        return f"{extra}. {s['cells_final']:,} cells from 2,000 seeded"
    runs2 = [(d, f"{v}.mp4", lbl,
              os.path.join(LOG_OKUDA, d, "spec_run.yaml"), _cap2(d)) for d, v, lbl, _p in R2]
    for d, v, _lbl, panel in R2:
        src = os.path.join(LOG_OKUDA, d, "movie.mp4")
        if not os.path.exists(src):
            sys.exit(f"no movie.mp4 for {d} -- run it before writing the page")
        vtk_sequence(os.path.join(LOG_OKUDA, d), os.path.join(GAL, v + ".mp4"))
        print(f"[minisite] gallery/{v}.mp4 <- okuda/{d}  "
              f"({os.path.getsize(os.path.join(GAL, v + '.mp4')) / 1e6:.1f} MB, {panel} panel, "
              f"square, no label)")

    # ---- Vertex + Turing, third row: two chemistries and one ablation ----
    VTK = ("vtk_evolve_mesh.mp4",)          # what a vtk card needs, and how its run is resolved
    def _sum(run, rd=None):
        return json.load(open(os.path.join(rd or _run_dir(run), "diag.json")))["summary"]
    R4 = [
        ("r013_05", "turing_flower_v3", "purse-string, k = 0.062"),
        ("r016_01", "turing_lobes_v3", "purse-string, k = 0.031"),
        ("r017_00_ctrl", "turing_noline_v3", "no purse-string"),
    ]
    CAP4 = {
        "r013_05": "eight arms from one activator: {cells:,} cells, protrusion peak {pk}",
        "r016_01": "the same graph at half the Gray–Scott k, and it lobes and branches instead: "
                   "{cells:,} cells",
        "r017_00_ctrl": "the interface tension removed, so growth acts alone: {cells:,} cells and "
                        "the longest arms of the three, peak {pk}",
    }
    runs4 = []
    for d, v, lbl in R4:
        rd = _run_dir(d, need=VTK)
        if not os.path.exists(os.path.join(rd, "vtk_evolve_mesh.mp4")):
            print(f"[minisite] {d}: no vtk_* clips -- card skipped")
            continue
        sm = _sum(d, rd)
        vtk_sequence(rd, os.path.join(GAL, f"{v}.mp4"))
        print(f"[minisite] gallery/{v}.mp4 <- okuda/{d}  "
              f"({os.path.getsize(os.path.join(GAL, v + '.mp4')) / 1e6:.1f} MB, side view, square)")
        cap = CAP4[d].format(cells=sm["cells_final"], pk=f"{sm['protr_peak']:.2f}")
        runs4.append((d, f"{v}.mp4", lbl, os.path.join(rd, "spec_run.yaml"), cap))

    # ---- Vertex + Turing, fourth row: the same composition at two reaction rates ----
    # THE ROW IS THE CHEMISTRY-TO-GROWTH RATIO, read left to right. It is NOT a one-knob pair:
    # the middle card also has `interface_tension` (purse-string, K_purse 1.0) on and twice the
    # growth rate, which its own title and caption say, so the row is not read as rate alone.
    R5r = [
        ("r020_01", "turing_folds_v3", "reaction rate 0.75"),
        ("r020_00_ctrl", "turing_arms_r020ctrl", "rate 0.5, purse-string on"),
        ("r021_06", "turing_spikes_v3", "rate 0.25, growth doubled"),
    ]
    # ORDERED BY CHEMISTRY AGAINST GROWTH, fastest first, because that ratio is what the row is:
    # 0.75/8.66e-4, then 0.5/8.66e-4, then 0.25/1.73e-3 -- a sixfold range, and the shape goes from
    # folded to thick-armed to thin-armed across it. The third run also reseeds, which is why its
    # caption says to read the ratio rather than the shape.
    CAP5 = {
        "r020_01": "chemistry fast against growth: the shell folds rather than forming arms, and "
                   "carries {cells:,} cells",
        # `diag.json` leaves `cells_final` unset on this run, so the count comes from
        # `progress.json` -- the same number the renderer prints on the last frame.
        "r020_00_ctrl": "the same reaction rate with the purse-string on: {cells:,} cells drawn "
                        "into {tubes} arms, protrusion peak {peak}",
        "r021_06": "slower still, with growth doubled: five long thin arms, {cells:,} cells. This "
                   "one reseeds as well, so it is the ratio that compares and not the shape",
    }
    runs5r = []
    for d, v, lbl in R5r:
        rd = _run_dir(d, need=VTK)
        if not os.path.exists(os.path.join(rd, "vtk_evolve_mesh.mp4")):
            print(f"[minisite] {d}: no vtk_* clips -- card skipped")
            continue
        sm = _sum(d, rd)
        vtk_sequence(rd, os.path.join(GAL, f"{v}.mp4"))
        print(f"[minisite] gallery/{v}.mp4 <- okuda/{d}  "
              f"({os.path.getsize(os.path.join(GAL, v + '.mp4')) / 1e6:.1f} MB, side view, square)")
        cells = sm.get("cells_final")
        if not cells:
            cells = json.load(open(os.path.join(rd, "progress.json")))["n_cells"]
        runs5r.append((d, f"{v}.mp4", lbl, os.path.join(rd, "spec_run.yaml"),
                       CAP5[d].format(cells=cells, tubes=sm.get("n_tubes_final"),
                                      peak=f"{sm['protr_peak']:.2f}")))

    # ---- the three-entity section: spheroid, basement membrane, matrix ----
    # PANEL GEOMETRY IS A PROPERTY OF THE RUN'S RENDERER, so it is written down beside the run.
    # The 06 runs draw one 2x2 with the run label in the top-left corner and the membrane
    # panel's own title just under the halfway line; 05h_1 draws four, each with two lines of
    # title above it and the run label under the first.
    q = dict(tl=(0, 0, 0.5, 0.5), tr=(0.5, 0, 0.5, 0.5),
             bl=(0, 0.5, 0.5, 0.5), br=(0.5, 0.5, 0.5, 0.5))
    def _metrics_or_none(run):
        """A run that is being RE-RUN has a directory and not yet a `metrics.json`.

        Caught rather than crashed for the same reason `_clip` tolerates a half-written movie:
        this script is run while runs are in flight, and the failure mode of not tolerating it is
        that a page which is 90% ready cannot be regenerated at all. The card is dropped and the
        reason is printed -- never dropped silently.
        """
        try:
            return json.load(open(os.path.join(LOG, run, "metrics.json")))
        except (OSError, ValueError):
            print(f"[minisite] {run}: no readable metrics.json (running?) -- its card is skipped")
            return None

    def _census(run):
        """`census.py`'s per-entity min/mean/max/last, or None. The numbers in the first card's
        caption are counted from the store at every kept frame -- quoting them from here rather
        than typing them is the same rule the specs follow."""
        try:
            return json.load(open(os.path.join(LOG, run, "census.json")))["entities"]
        except (OSError, ValueError, KeyError):
            print(f"[minisite] {run}: no census.json -- its card cannot quote counts")
            return None

    def _clip(d, v, panels, kw):
        """Build one card's clip, or say plainly that the run is not ready.

        A HALF-WRITTEN MP4 IS NOT A MISSING ONE: these runs are often still encoding when the page
        is regenerated, and a file without its `moov` atom cuts into a broken clip rather than
        failing. `_nframes` reads the container, so a movie that cannot be counted is treated as
        absent -- and SAID to be absent, because a row that silently drops a card looks like a row
        that was only ever meant to be short.

        DEFINED BEFORE THE ROW LISTS. Three times now an edit that replaced a row list from its
        first line to the loop has taken this function with it.
        """
        src = next((x for x in (os.path.join(LOG, d, "movie_vtk.mp4"),
                                os.path.join(LOG, d, "movie.mp4")) if os.path.exists(x)), None)
        if src is None:
            print(f"[minisite] {d}: no movie.mp4 or movie_vtk.mp4 yet -- card skipped")
            return None
        try:
            n = _nframes(src)
        except Exception:
            print(f"[minisite] {d}: movie is still being written (no moov atom) -- card skipped")
            return None
        panels_concat(src, os.path.join(GAL, f"{v}.mp4"), panels, **kw)
        print(f"[minisite] gallery/{v}.mp4 <- {d}/{os.path.basename(src)}  "
              f"({os.path.getsize(os.path.join(GAL, v + '.mp4')) / 1e6:.1f} MB, {n} frames, "
              f"{len(panels)} panel{'s' if len(panels) > 1 else ''} in sequence, square, no label)")
        return True

    cen = _census("07i_ramp")

    def _hole(run):
        """`hole_metrics.json`: how much of the sheet is gone, in how many pieces, and whether it
        stopped. Read per run so a caption cannot outlive the run that earned it -- the 06 cards
        this replaces said "still stops" and every 07 run reports `arrested: false`."""
        try:
            return json.load(open(os.path.join(LOG, run, "hole_metrics.json")))
        except (OSError, ValueError):
            print(f"[minisite] {run}: no hole_metrics.json -- card skipped")
            return None

    QUAD = [q["tl"], q["tr"], q["bl"], q["br"]]
    R5 = [("07i_ramp", "spheroid_bm_ecm_07i2", "from tissue to cells to proteins", QUAD,
           dict(skip_top=0.0),
           "cells, basement membrane and matrix grow together")]
    # THE MEMBRANE PANEL ALONE for the three breach cards: their other three panels are the tissue
    # and the matrix, which the first card already shows.
    # A RIM LOOP IS ONE OPENING, so `torn_frac_final / rim_loops_final` is how much of the sheet
    # each opening took: that ratio, not the total loss, is what separates "many small holes" from
    # "one larger hole". 07j loses LESS of the membrane than 07k_breach_hole and still earns the
    # word larger, because it loses it through six openings instead of fifty-four.
    breach = {r: _hole(r) for r in ("07k_breach_hole", "07j_hole_tiny", "07k_breach_torn")}
    def _per_loop(run):
        hm = breach.get(run)
        return None if not hm or not hm["rim_loops_final"] else \
            hm["torn_frac_final"] / hm["rim_loops_final"]
    ratio = (_per_loop("07j_hole_tiny") / _per_loop("07k_breach_hole")
             if _per_loop("07j_hole_tiny") and _per_loop("07k_breach_hole") else None)
    for run, clip, label, capfn in (
            ("07k_breach_hole", "bm_07k_breach_hole", "small holes in the membrane",
             lambda hm: (f"the sheet perforates wherever the enzyme sits: "
                         f"{100 * hm['torn_frac_final']:.1f}% of its faces gone by frame "
                         f"{hm['frames']}, through {hm['rim_loops_final']} separate openings, the "
                         f"first at frame {hm['first_torn_frame']}")),
            ("07j_hole_tiny", "bm_07j_hole_tiny", "larger hole in the membrane",
             lambda hm: (f"one localised source instead: {100 * hm['torn_frac_final']:.1f}% of the "
                         f"faces gone, but through only {hm['rim_loops_final']} openings — "
                         + (f"{ratio:.1f}x as much of the sheet per opening as the card at left"
                            if ratio else "far fewer, each far bigger"))),
            ("07k_breach_torn", "bm_07k_breach_torn", "membrane tears apart",
             lambda hm: (f"the same chemistry with nothing holding it: "
                         f"{100 * hm['torn_frac_final']:.0f}% of the faces gone by frame "
                         f"{hm['frames']}, the first as early as frame "
                         f"{hm['first_torn_frame']}, and still tearing at the end"))):
        hm = breach.get(run)
        if hm is None:
            continue
        R5.append((run, clip, label, [q["bl"]], dict(skip_top=0.0), capfn(hm)))
    R5b = []
    runs5, runs5b = [], []
    for out, rows in ((runs5, R5), (runs5b, R5b)):
        for d, v, lbl, panels, kw, cap in rows:
            sp = _spec(d)
            if sp and _clip(d, v, panels, kw):
                out.append((d, f"{v}.mp4", lbl, sp, cap))

    import shutil
    for tgt, rendered in ((QMD, False), (DOCS, True)):
        if rendered and not os.path.exists(DOCS):
            print("[minisite] no docs/index.html -- source updated only; run `quarto render`")
            continue
        _patch(tgt, build(runs), rendered=rendered)
        _patch2(tgt, build2(runs2), rendered=rendered)
        _patch4(tgt, build4(runs4), rendered=rendered)
        _patch5(tgt, build5(runs5r), rendered=rendered)
        _patch3(tgt, build3(runs5, runs5b), rendered=rendered)
    # AND THE ONE HAND-WRITTEN CARD THIS SESSION REPLACED: "grow & divide" now plays the vertex
    # model on its own (`00_spheroid`), cropped to the tissue so the printed label is out of frame,
    # 3D first and the true cross-section second.
    gd = os.path.join(LOG, "00_spheroid")
    if os.path.exists(os.path.join(gd, "movie.mp4")):
        split_concat(os.path.join(gd, "movie.mp4"), os.path.join(GAL, "tyssue_spheroid_00.mp4"),
                     skip_top=0.16)
        print(f"[minisite] gallery/tyssue_spheroid_00.mp4 <- 00_spheroid/movie.mp4 "
              f"({os.path.getsize(os.path.join(GAL, 'tyssue_spheroid_00.mp4')) / 1e6:.1f} MB)")
        replace_card("tyssue_grow_divide.mp4", "grow &amp; divide", os.path.join(gd, "spec.yaml"),
                     "the vertex model on its own: 200 cells and 396 vertices to 6,076 and ~12,000 "
                     "over 402 frames, the apical radius x3.56 and the shell still round "
                     "(aspect 1.02), through 1,384 T1 neighbour exchanges. 3D first, then the true "
                     "cross-section -- one cell deep, hollow",
                     files=((QMD, False), (DOCS, True)),
                     new_video="tyssue_spheroid_00.mp4")
        import shutil as _sh
        # THREE CARDS THAT NEVER HAD A SPEC. `apop_patch_big`, `apop_rings9` and `apop_half` were
    # written by hand with a bare <span class="sim-name">: no `tabindex`, no spec, so their titles
    # are the only ones on the page that open nothing when you click them. The page's rule is that
    # every clip opens the spec that produced it, and these three are the exception, not a choice.
    # `apop_half` plays `apopgeo_half` -- identified by its own number, 400 - 285 extruded = the
    # 115 cells that run's diagnostics report, and not by the clip's name.
    for vid, nm, run, cap in (
        ("apop_patch_big", "a dying big patch", "apop_patch_big",
         "seen from the pole: 293 cells (blue) are marked to die, and the surface is drawn "
         "<b>inward</b> where they go — an invagination, the one deformation growth cannot make"),
        ("apop_rings9", "nine dying rings", "apop_rings9",
         "895 deaths in nine bands: the vesicle does not fall apart, it closes over every gap and "
         "shrinks"),
        ("apop_half", "half the sheet", "apopgeo_half",
         "285 of 400 cells extruded — the topology survives, and what is left is an ellipsoid "
         "pulled from a sphere"),
    ):
        sp = os.path.join(LOG_OKUDA, run, "spec_run.yaml")
        if os.path.exists(sp):
            # THE CLIP TOO, not only the spec: these three now play the VTK sequence like the
            # Turing rows, under a new name because their content changed.
            new_v = f"{vid}_v5"
            built = vtk_sequence(os.path.join(LOG_OKUDA, run), os.path.join(GAL, f"{new_v}.mp4"),
                                 kinds=("evolve",))
            for old_v in (f"{vid}.mp4", f"{vid}_vtk.mp4", f"{vid}_v2.mp4", f"{vid}_v3.mp4",
                          f"{new_v}.mp4"):
                if any(f'<video src="gallery/{old_v}"' in open(f).read() for f, _ in
                       ((QMD, False), (DOCS, True))):
                    replace_card(old_v, nm, sp, cap, files=((QMD, False), (DOCS, True)),
                                 new_video=f"{new_v}.mp4" if built else None)
                    break
            if built and os.path.isdir(DOCS_GAL):
                shutil.copy2(os.path.join(GAL, f"{new_v}.mp4"),
                             os.path.join(DOCS_GAL, f"{new_v}.mp4"))
        else:
            print(f"[minisite] {run}: no spec_run.yaml -- {vid} keeps its bare title")

    # ROW 1 OF Vertex + Turing, on runs that can be re-rendered. Both cards played
    # `discovery_okuda/ops` archives that hold movies and specs and NO trajectory, so no renderer
    # since could redraw them; `b_gs_gated_shaping` stood in for coral for one commit and is
    # replaced here by the run Cedric picked, which is a labyrinth rather than patches.
    for clip, run, label, cap_fn, olds in (
        ("turing_coral_v4", "r021_12", "coral",
         lambda m: (f"a Gray–Scott pattern riding a growing shell: red stripes wander across "
                    f"{m['cells_final']:,} cells and the shell stays round (protrusion peak "
                    f"{m['protr_peak']:.2f})"),
         ("tyssue_vh_rd_coral.mp4", "turing_coral_v2.mp4", "turing_coral_v3.mp4",
          "turing_coral_v4.mp4")),
        # `grow_divide` is `r001_00_ctrl` with growth that no morphogen gates (the operator's own
        # `rho: 1, a_sw: 0`). The control has cell_divide and NO cell_grow, so 2 of its 2,001 cells ever
        # divided and the card drew a sphere doing nothing; this one reaches 25,079 cells of which
        # 25,054 divided.
        ("turing_grow_divide_v4", "grow_divide", "grow &amp; divide",
         lambda m: (f"growth that no morphogen gates, and division following it: 2,000 cells to "
                    f"{m['cells_final']:,}, and the shell stays a sphere (reduced volume "
                    f"{m['reduced_volume_final']:.2f})"),
         ("tyssue_vh_grow_divide.mp4", "turing_grow_divide_v3.mp4", "turing_grow_divide_v4.mp4")),
        # `r005_06`, re-run 13 August: growth gated by the activator, and the arms are where the
        # activator sits. `diag.json` reports `cells_final: null` on this run -- the analysis pass
        # left it unset -- so the count is read from `progress.json`, which is the same number the
        # renderer prints on the last frame (4,764).
        ("turing_morphogen_v6", "r005_06", "morphogen + growth",
         lambda m: (f"Growth gated by the activator, and the arms grow where it sits: "
                    f"{m['cells']:,} cells with {m['tubes']} of them counted as tubes, "
                    f"protrusion peak {m['peak']}"),
         ("tyssue_okuda_lobed.mp4", "turing_morphogen_v3.mp4", "turing_morphogen_v4.mp4",
          "turing_morphogen_v5.mp4", "turing_morphogen_v6.mp4")),
    ):
        rd = _run_dir(run, need=("traj.npz", "vtk_evolve_mesh.mp4"))
        if not os.path.exists(os.path.join(rd, "traj.npz")):
            print(f"[minisite] {run}: no traj.npz -- {label} card left as it is")
            continue
        sm = json.load(open(os.path.join(rd, "diag.json")))["summary"]
        if run == "r005_06":
            pr = json.load(open(os.path.join(rd, "progress.json")))
            sm = {"cells": sm.get("cells_final") or pr["n_cells"],
                  "tubes": sm.get("n_tubes_final"), "peak": f"{sm['protr_peak']:.2f}"}
        if not vtk_sequence(rd, os.path.join(GAL, f"{clip}.mp4")):
            continue
        for old_v in olds:
            if f'<video src="gallery/{old_v}"' in open(QMD).read():
                replace_card(old_v, label, os.path.join(rd, "spec_run.yaml"), cap_fn(sm),
                             files=((QMD, False), (DOCS, True)), new_video=f"{clip}.mp4")
                break
        if os.path.isdir(DOCS_GAL):
            shutil.copy2(os.path.join(GAL, f"{clip}.mp4"), os.path.join(DOCS_GAL, f"{clip}.mp4"))

    if os.path.isdir(DOCS_GAL):
                shutil.copy2(os.path.join(GAL, "turing_coral_v4.mp4"),
                             os.path.join(DOCS_GAL, "turing_coral_v4.mp4"))

    if os.path.isdir(DOCS_GAL):
        # EVERY CARD'S CLIP, not just the ones that are new this time. Copying a subset once left
        # clips out of docs/gallery while the page that referenced them was patched -- cards
        # pointing at files the site did not have.
        n = 0
        for d, v, *_ in runs + runs2 + runs4 + runs5r + runs5 + runs5b:
            src = os.path.join(GAL, v)
            if not os.path.exists(src):
                print(f"[minisite] {v}: not in gallery/ -- NOT copied to docs/")
                continue
            shutil.copy2(src, os.path.join(DOCS_GAL, v))
            n += 1
        print(f"[minisite] {n} videos copied into docs/gallery/")
        # AND THEN CHECK: every clip the rendered page asks for has to be there. Copying is the
        # last step and the one whose failure is invisible until the site 404s.
        page = open(DOCS).read()
        want = set(re.findall(r'gallery/([A-Za-z0-9_]+\.mp4)', page))
        gone = sorted(w for w in want if not os.path.exists(os.path.join(DOCS_GAL, w)))
        if gone:
            sys.exit(f"docs/gallery is missing {len(gone)} clip(s) the page plays: {gone}")
    return


def _patch(path, block, rendered=False):
    if rendered:
        block = block.replace("<h3>", '<h3 class="anchored">').replace("&#x27;", "'")
    s = open(path).read()
    anchor_old = ANCHOR_OLD if not rendered else ANCHOR_OLD.replace("<h3>", '<h3 class="anchored">')
    anchor_new = ANCHOR_NEW if not rendered else ANCHOR_NEW.replace("<h3>", '<h3 class="anchored">')
    _b = _find_block(s, "vertex-mpm")
    if _b:
        i, j = _b
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        # AFTER THE MLS-MPM SECTION, not after Vertex + Turing: the interface is read once the
        # solver it couples to has been introduced. A section is placed after another by finding
        # the NEXT h3 -- a section ends where the following one begins, and inserting straight
        # after a heading would land inside that section's own prose.
        anchor = MPM_SECTION if not rendered else MPM_SECTION.replace("<h3>", '<h3 class="anchored">')
        if anchor not in s:
            sys.exit(f"the MLS-MPM heading was not found in {path}")
        k = s.index(anchor)
        tag = "<h3" if rendered else "<h3>"
        nxt = s.find(tag, k + len(anchor))
        nxt = len(s) if nxt < 0 else nxt
        s = s[:nxt] + block + "\n\n" + s[nxt:]
        what = "inserted"
    s = s.replace(anchor_old, anchor_new)
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: {what}; heading renamed to 'Vertex + Turing'")


def _patch2(path, block, rendered=False):
    """The Vertex + Turing second row, inserted BETWEEN that section and the Vertex + MPM one.

    Anchored on the `BEGIN` marker of the Vertex + MPM block rather than on a heading, because it
    belongs to the section ABOVE that marker and has no heading of its own -- and because the two
    blocks then cannot be inserted in the wrong order however many times this runs.
    """
    if rendered:
        block = block.replace("&#x27;", "'")
    s = open(path).read()
    if BEGIN2_OLD in s:                       # one-time: drop the block under its former name
        a, b = s.index(BEGIN2_OLD), s.index(END2_OLD) + len(END2_OLD)
        s = s[:a] + s[b:]
        open(path, "w").write(s)
        print(f"[minisite] {os.path.relpath(path, ROOT)}: legacy 'vertex-turing-death' block removed")
    _b = _find_block(s, "vertex-turing-second-field")
    if _b:
        i, j = _b
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        if BEGIN not in s:
            sys.exit(f"vertex-mpm marker not found in {path} -- run the first patch before this one")
        k = s.index(BEGIN)
        s = s[:k] + block + "\n\n" + s[k:]
        what = "inserted"
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: Vertex + Turing second-field row {what}")


def _patch5(path, block, rendered=False):
    """The reaction-rate row, between the shapes row and the two-morphogen row.

    Inserted before `BEGIN2` like the shapes row and AFTER it in the same pass, so it lands
    between the two -- the order the two calls run in is the order the rows appear in.
    """
    if rendered:
        block = block.replace("&#x27;", "'")
    s = open(path).read()
    _b = _find_block(s, "vertex-turing-rate")
    if _b:
        i, j = _b
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        if BEGIN2 not in s:
            sys.exit(f"second-field marker not found in {path}")
        k = s.index(BEGIN2)
        s = s[:k] + block + "\n\n" + s[k:]
        what = "inserted"
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: Vertex + Turing rate row {what}")


def _patch4(path, block, rendered=False):
    """The shapes row, straight after the second-field row it extends."""
    if rendered:
        block = block.replace("&#x27;", "'")
    s = open(path).read()
    _b = _find_block(s, "vertex-turing-shapes")
    if _b and (not _find_block(s, "vertex-turing-second-field")
               or _b[0] < _find_block(s, "vertex-turing-second-field")[0]):
        i, j = _b
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        _b = _find_block(s, "vertex-turing-shapes")
        if _b:                               # it exists, but after the row it should precede
            i, j = _b
            s = s[:i].rstrip("\n") + "\n" + s[j:].lstrip("\n")
        if BEGIN2 not in s:
            sys.exit(f"second-field marker not found in {path}")
        k = s.index(BEGIN2)
        s = s[:k] + block + "\n\n" + s[k:]
        what = "inserted"
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: Vertex + Turing shapes row {what}")


def _patch3(path, block, rendered=False):
    """The three-entity section, AFTER the Vertex + MPM block it depends on.

    Anchored on that block's END marker for the same reason `_patch2` anchors on its BEGIN: the
    section is placed relative to the thing it follows, so re-running cannot reorder the page.
    """
    if rendered:
        block = block.replace("<h3>", '<h3 class="anchored">').replace("&#x27;", "'")
    s = open(path).read()
    _b = _find_block(s, "spheroid-bm-ecm")
    if _b:
        i, j = _b
        s = s[:i] + block + s[j:]
        what = "replaced"
    else:
        # ANCHORED ON THE MLS-MPM HEADING, not on the Vertex + MPM block: that block has moved
        # after MLS-MPM, and chaining to it would drag this section along behind it.
        anchor = MPM_SECTION if not rendered else MPM_SECTION.replace("<h3>", '<h3 class="anchored">')
        if anchor not in s:
            sys.exit(f"the MLS-MPM heading was not found in {path}")
        k = s.index(anchor)
        s = s[:k] + block + "\n\n" + s[k:]
        what = "inserted"
    open(path, "w").write(s)
    print(f"[minisite] {os.path.relpath(path, ROOT)}: spheroid/BM/matrix section {what}")


if __name__ == "__main__":
    main()
